### ISSUE TITLE
Beispiel Fehler!

### ISSUE THREAD

**Issue by lostdesign** [LSS-Manager/lss-manager-v3#1]
## Fehlermeldung:
Wenn ich X anklicke, dann ...

## Aktivierte Module:
- y
- x

## Mögliche Lösung / Verbesserungsvorschlag:
...

---
#### Beta Version: ...

Optional zu den Browser-Angaben könnt ihr auch euren Ingame Nutzernamen nennen.

**Comment by Edelweisser** [comment]
Einsatz beim Starten gekommen 
Notebook aus Schule entwendet
Einsatz eingegangen: 24. Mai, 13:06 Uhr Weiskirchener Straße, 66679 Losheim am See

Start der Leitstelle um 14:45 Uhr

Browser: CHrome
Version aktuell
Beta; 3

betrifft sowohl NP wie auch KTP

Gruss
de Edel

**Comment by eaglefsd** [comment]
Testkommentar
