### ISSUE TITLE
Rote Kästen im VB Forum

### ISSUE THREAD

**Issue by JonasKilian** [LSS-Manager/lss-manager-v3#10]
## Fehlermeldung:
IM VB Forum werden hinter den Seitenzahlen Rote Kästen angezeigt
![2017-05-23 at 07-37-26](https://cloud.githubusercontent.com/assets/28886468/26340164/24ac2978-3f8d-11e7-8d7e-1ff565936ce3.png)
 

## Aktivierte Module:
Keine

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
fixed
