### ISSUE TITLE
Grüne Hinterlegung geht nicht

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#100]
Die grüne Hinterlegung der einzelnen Menüpunkte oben in der Leiste gehen nicht. Weder der News, Verband oder die Zahl bei den Nachrichten werden grün hinterlegt.

Aktivierte Module:
DASHBOARD
EINSATZHELFER
EINSÄTZE SUCHEN
EINSÄTZE FREIGEBEN
FAHRZEUGE UMBENNENEN
MISSIONOUT
SHOW BACK ALARM ABOVE
REDESIGN
WACHENSTATUS

**Comment by lostdesign** [comment]
Liegt am Redesign - danke.

**Comment by lostdesign** [comment]
Behoben im nächsten Update.
