### ISSUE TITLE
FMS5 Statusposition

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#101]
Der FMS5 Status kann nicht weiter nach rechts verschoben werden, wie im Screenshot ersichtlich. Egal wo sich die Uhr befindet.

Betrifft: Beta 3.2.2

![Screenshot](https://cdn.discordapp.com/attachments/315848362953932801/322483952524984330/image.png)

**Comment by lostdesign** [comment]
![](https://i.imgur.com/Bl1Njdp.png)

Nicht wirklich ein Bug - der Container der FMS ist einfach so groß. Ich teste mal ob man den verkleinern kann ohne das die FMS dann bei langen Namen gleich wieder bescheiden ausschauen.

**Comment by MrWeezle** [comment]
kann man die Breite nicht dynamisch an das längste Element anpassen?

**Comment by OiledAmoeba** [comment]
Jetzt hängt's links oben über der Kartensteuerung...
![grafik](https://user-images.githubusercontent.com/14559685/26967893-4761eeb4-4d00-11e7-976e-ac39c4709d7a.png)

**Comment by lostdesign** [comment]
@OiledAmoeba einfach verschieben. Ich werde es noch an den richten 'initial Platz' hauen.

**Comment by OiledAmoeba** [comment]
My Fault. Hatte nicht mitbekommen, dass der Kasten verschiebbar ist....

**Comment by lostdesign** [comment]
Das wissen die wenigsten ^^ wir müssen die Descriptions ein/ausschaltbar machen per Button & aktualisieren 👍

**Comment by MrWeezle** [comment]
Oder beim Aktivieren die Description mit ausklappen :+1:

**Comment by lostdesign** [comment]
Der Container ist schon dynamisch. Leider können wir da nichts dran ändern.

**Comment by MrWeezle** [comment]
Position wird nun zwar gespeichert, wird aber die Fenstergröße geändert, bleibt die Anzeige trotzdem noch an der Position
https://drive.google.com/file/d/0B9oDPjS3kltlMC1RMDY3QXlsdk0/view

**Comment by lostdesign** [comment]
Neues Issue bitte.
