### ISSUE TITLE
Vorschlag: Doppelbesetzung für Fahrzeuge

### ISSUE THREAD

**Issue by Moratorion** [LSS-Manager/lss-manager-v3#1043]
Mir fehlt im Leitstellenspiel die Möglichkeit eine Doppelbesetzung für Fahrzeuge herstellen zu können. Meine Idee wäre, per Dropdown-Menü ein "Partnerfahrzeug" aus der eigenen Wache auszuwählen. Wenn dann eins der beiden Fahrzeuge in den FMS 3 geht, würde das 2. Fahrzeug (oder mehr wenn möglich) in den FMS 6 gehen.
Weiterführend könnte man auch eine gemeinsame Fahrzeugzuordnung des Personals machen, aber das ist nicht zwingend notwendig.

**Comment by jxn-30** [comment]
Das ganze lässt sich zwar Scriptseitig lösen (wurde auch im Forum schon gewünscht: https://forum.leitstellenspiel.de/index.php?thread/21018-script-wunsch-doppelbesetzung/), allerdings funktioniert das eben nur, wenn das entsprechende Script gerade aktiv ist. Das ist eher suboptimal und wäre eher ein Vorschlag fürs Spiel. => Bitte bei Interesse im Forum ein Vorschlag (gut ausgearbeitet) erstellen, vorher nochmals die Forensuche verwenden, vielleicht gibt es einen entsprechenden Thread bereits.

Der LSSM V.3 ist End of Life, deshalb schließe ich hier, ich hab mir das ganze aber mal auf die Lange Liste der V4 (https://github.com/LSS-Manager/LSSM-V.4) gesetzt, vielleicht kommt es ja irgendwann als Script ;)

**Comment by Moratorion** [comment]
Alles klar, danke für die schnelle Antwort. Ich würde mich sehr drüber freuen, aber bis dahin probiere ich mich mal selbst ein bisschen daran aus ;).
