### ISSUE TITLE
Dashboard - Wachenplanung

### ISSUE THREAD

**Issue by maxk1312** [LSS-Manager/lss-manager-v3#105]
Wie der Screenshot ( ![](https://i.imgur.com/8yoiXGO.jpg) )zeigt, werden die Ausbaustufen vom KH als Fahrzeuge gezählt und bei der SEG (ausgebaut mit ELW, GW-San, RTW und 3 KTW Typ B sind es 6/1 Fahrzeuge...

**Comment by Suchty112** [comment]
Sollte gefixxt sein für die BetaLeute. er zeigt beim THW und bei der SEG jetzt immer die höchste ausbaustufe an für die Autos. also SEG = 9 mit WR drin. Und bei THW 12 auch dort wg der Wasserrettung. Krankenhaus müssen wir im nächsten update mal schauen. Aber sollte ja erstmal net so schlimm sein oder? :D 
Bitte um rückmeldung @maxk1312 ob es funktioniert (vorrausgesetzt du bist betaspieler :P) dann schließen wir den hier sobald rückmeldung erfolgt :D
