### ISSUE TITLE
AAO SUCHE

### ISSUE THREAD

**Issue by lostdesign** [LSS-Manager/lss-manager-v3#106]
#### Fehler
Züge werden nicht in der AAO Suche angezeigt / sind nicht suchbar.
*BETA 3.2.2*

#### Forum Link
https://forum.leitstellenspiel.de/index.php/Thread/11166-LSS-MANAGER-V3/?postID=187671#post187671

**Comment by Mausmajor** [comment]
Sollte im nächsten Update behoben sein
