### ISSUE TITLE
Ausgewählte AAO/Züge umranden

### ISSUE THREAD

**Issue by stefschen** [LSS-Manager/lss-manager-v3#108]
Hallo, 
ich finde es toll wenn, wie in einem anderen Script, die ausgewählten AAO / Züge umrandet werden könnten. So sieht man bei der Alarmierung, wen man schon ausgewählt hat ;)

Danke

**Comment by Tsumiki-Chan** [comment]
Würde es nicht mehr sinn machen, wenn man anzeigt wie oft man das ganze alarmiert hat? Du kannst ein und die selbe AAO ja mehrmals anklicken und es werden auch immer mehr fahrzeuge alarmiert.

**Comment by stefschen** [comment]
Da ich kaum mit AAO sondern bis auf die Sonderfahrzeuge nur mit Zügen arbeite, ist es für mich wichtiger zu wissen, ob ich den Zug zum alarmieren bereits ausgewählt habe (auch abwähl-Funktion z.B. durch erneuten Button-Click wäre toll) .. bei der AAO habe ich mir mehrere Buttons angelegt (z.B. 1XRTW, 2XRTW, 4XRTW .. oder NAW.. auch bei POL funzt das ganz gut ;) ) .... ggf könnte man hinter die Buttons n label machen, in dem die Anzahl drin steht (klick auf das Label kann dann alles Löschen ;) )
so hätte man beides kombiniert... hiesse aber die Komplette Alarmierungs-Seite neu schreiben :(

Danke und Gruß

Stefschen

**Comment by Tsumiki-Chan** [comment]
Ich frage mich jetzt grad eher, wo ich das ganze umsetze. Als eignes Modul macht es kaum sinn. @lostdesign Was meinst du?

**Comment by lostdesign** [comment]
Das Umranden + Counter + Zurücksetzen Funktion » kann ein Plugin sein. Wieso nicht?

**Comment by Tsumiki-Chan** [comment]
Die "Zurücksetzen"-Funktion ist bereits Teil der AAO-Suche

**Comment by lostdesign** [comment]
#65

**Comment by KBOE2** [comment]
Implemented with #731
