### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by keksi27bln** [LSS-Manager/lss-manager-v3#1093]
Seid heute löst der LSS Manager V3 beim Laden des Spiels nach sehr kurzer Zeit einen Fehler aus : Out of Memory 
Diesen aber benötige ich weil mir einige Buttons fehlen den der LSS Manager V4 noch scheinbar nicht hat
Grüner Button zum Einklappen bzw Freigeben rechts neben den Einsatz

**Comment by jxn-30** [comment]
Beide Features sind bereits in der V4 integriert: https://proxy.lss-manager.de/v4/docs/de_DE/apps.html#lssm-v-3-vs-lssm-v-4

Die Out of Memory kannten wir bisher nur aus der V4, dort sind diese aber soweit behoben bis auf seltene Einzelfälle.
Welchen Browser nutzt du denn? Dann kann ich mir das gerne auch mal in der V3 anschauen.

**Comment by jxn-30** [comment]
Ok, das ist vollkommen in Ordnung. Die Module/Features existieren ja in der V3 weiterhin, weil uns bewusst ist, dass das "alte" Design manchen Spielern einfach besser gefällt.

Tatsächlich scheint da also Chrome derzeit Probleme zu machen. Die wenigen anderen Out of Memories kommen auch alle von Chrome.

Wir werden das weiter beobachten, aber ich schließe hier trotzdem mal, da ich befürchte, dass wir hier nicht allzu viel machen können.
