### ISSUE TITLE
LSS Manager Kompatibilität zu Sebastians Dunklem Layout

### ISSUE THREAD

**Issue by GregorPaul** [LSS-Manager/lss-manager-v3#11]
## Fehlermeldung:
Ich hab mit dem Dunklen Layout in den LSS Manager gestartet. Der kommt damit aber nicht richtig klar Siehe Bild.
![bildschirmfoto 2017-05-23 um 07 53 29](https://cloud.githubusercontent.com/assets/28886972/26340426/8bdcfe3c-3f8e-11e7-8fc5-46e9a7db8090.png)

## Aktivierte Module:
-keine Module. (war noch grad am Anfang)

## Mögliche Lösung / Verbesserungsvorschlag:
...

**Comment by lostdesign** [comment]
Hi, wir werden wieder unseren eignen Darkmode einführen. Das LSS Manager Design wird noch in Redesign-01 ausgelagert - dann gehts wieder 👍

**Comment by GregorPaul** [comment]
wäre echt cool wenn beides Funktionieren würde. Um den Wechsel zwischen Handy, anderen PCs und LSS Manager nicht so krass zu machen. der Dark Modus von Sebastian ist ja so gesehen Global.

**Comment by lostdesign** [comment]
Wir hängen uns nur ein & machen nicht viel anders. Man kann aber wie immer alles optional nutzen.
