### ISSUE TITLE
Beim Einsatz werden falsche Voraussetzungen eingesetzt (Einsatzhelfer)

### ISSUE THREAD

**Issue by Stinkerwue** [LSS-Manager/lss-manager-v3#110]
![image](https://user-images.githubusercontent.com/11669885/26981377-33740574-4d35-11e7-83df-bffc47d2c09c.png)

Die Voraussetzungen lt. IG-Hilfe sind:

Beschreibung	Wert
Benötigte ELW 1	1
Benötigte Streifenwagen	1
Benötigte Löschfahrzeuge	3
Benötigte Dekon-P	1
Dekon P Anforderungswahrscheinlichkeit	30
Benötigte GW-Mess	1
GW-Mess Anforderungswahrscheinlichkeit	30
Benötigte GW-Gefahrgut	1
GW-Gefahrgut Anforderungswahrscheinlichkeit	30

Version: 3.2.2

aktive Module: DASHBOARD
EINSATZHELFER
LS-HEATMAP
MISSIONOUT
NOTIFICATION ALERT
REDESIGN 01
SHOW BACK ALARM ABOVE
WACHEN STATUS

**Comment by Suchty112** [comment]
Ja in meiner Version ist das gefixxt, ich werde nachher mit Lost und Co. darüber reden, dann kommt sie rein, und dann sollten soweit alle Fehler beseitigt sein. Daher bitte abwarten :) . Schönes Wochenende

**Comment by Stinkerwue** [comment]
noch einen Einsatz gefunden:
![image](https://user-images.githubusercontent.com/11669885/27005112-e55210be-4e17-11e7-833d-07dbda2e1185.png)


Beschreibung	Wert
Benötigte Löschfahrzeuge	2

**Comment by Suchty112** [comment]
Das wiederum liegt daran, das es davon ja mehrere Gibt, und DrFussel dort einfach den größten genommen hat, inwiefern man später evtl das ändern kann, kann ich nicht sagen. 
#91

**Comment by Suchty112** [comment]
Ist in #130 gefixxt, der teil ist soweit auch schon in der entwicklungsversion drin. Auffälligkeiten gab es soweit keine. Sollte wahrscheinlich in den nächsten Tagen für die Beta-Leute bzw für alle raus kommen.

Schönes Wochenende

**Comment by Suchty112** [comment]
noch ein update für dich @Stinkerwue . Im Dev branch ist es soweit drin und sollte in den nächsten Tagen bei euch ankommen, da wird dann auch bei den Flächenbränden unterschieden
