### ISSUE TITLE
Vorschlag  Wachenplanung auf Karte

### ISSUE THREAD

**Issue by Thomas21030** [LSS-Manager/lss-manager-v3#112]
Ist es mögl bei der Wachenplanung auf der Karte  

1.) Anstelle des KM-Reglers die Angabe freiwählbar  mit so ein Up/Down Schaltfläche wie bei der AAO oder ein Eingabefeld 

2.) Fahrzeugaufgebot ausblenden

Auf der Karte das Fahrzeugaufgebot alternativ mit ein/aus Button ausblenden, da oft ein Teil der Karte durch die Anzeige von 10 und mehr Fahrzeuge sehr weit verdeckt wird.
![wachenplanung](https://user-images.githubusercontent.com/28989752/26996617-b29fa25c-4d73-11e7-9ed2-044d70d75320.JPG)

**Comment by Mausmajor** [comment]
Punkt zwei werd ich mich jetzt ran setzten.
Was ist mit Punkt 1? reichen 400 km nicht aus?

**Comment by Thomas21030** [comment]
Der Regeler ist recht ungenau finde ich,
1 Millimetern zuweit nach links oder rechts und schon sind 25 Kilometer weiter ;-)

**Comment by Mausmajor** [comment]
Sollte im nächsten Update gehen.
Wechsel zwischen Slider und Inputbox geht per doppelklick

**Comment by lostdesign** [comment]
Ich würde nur einen Input mit + - Buttons machen, dann brauchen wir Jquery UI nicht.

Den Hover können wir entfernen - gibt ja das Modul Wachenstatus.
