### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JonasFeuerwehr** [LSS-Manager/lss-manager-v3#1124]
It doesn't work anymore. I used it long but now it won't even show the green button. And yes, it is turned on.

**Comment by JonasFeuerwehr** [comment]
Please help... I need it back...

**Comment by jxn-30** [comment]
With this very detailed error report it is very easy to help 👍

Please try reinstalling the script. Does that help?
If no, are there any red errors in console (F12->Console)?

**Comment by JonasFeuerwehr** [comment]
yeah... soooo

![2023-04-29 (1)](https://user-images.githubusercontent.com/75850739/235300643-0a1d57f5-6ab6-4fee-84b9-ba0f29bcc3b0.png)
![2023-04-29 (2)](https://user-images.githubusercontent.com/75850739/235300644-9987e2b5-c26f-44e3-a0c5-1d4ba8fa9fb4.png)
![2023-04-29](https://user-images.githubusercontent.com/75850739/235300646-86b0739f-de73-4e8f-94d4-bbe84ed62daf.png)

**Comment by JonasFeuerwehr** [comment]
The bottom one in consol reads:
Failed loading for the <script> witht he source "..."

**Comment by JonasFeuerwehr** [comment]
And now this error in console too:
![2023-04-29 (3)](https://user-images.githubusercontent.com/75850739/235300712-e91e1283-a47a-4882-bdd7-454afe142ca2.png)

**Comment by jxn-30** [comment]
You're using an outdated version of the script, so you have to reinstall it!
You can do so by navigating to "Installierte Userscripte" and press the Mülleimer button in the line of the script.
Then you can reinstall by using the official installation link: https://github.com/LSS-Manager/lss-manager-v3/raw/master/lssm-v3.user.js

**Comment by JonasFeuerwehr** [comment]
Aaaah! Thanks. Also do you speak german?

**Comment by JonasFeuerwehr** [comment]
Yes! It works! And all my activated apps are still on! YES! Thanks for help! I'll give you a 5 out of 5 stars rating!

**Comment by jxn-30** [comment]
Gut, dann schließe ich hier, da Problem behoben!
