### ISSUE TITLE
Firefox Anzeigeprobleme

### ISSUE THREAD

**Issue by Stitchy85** [LSS-Manager/lss-manager-v3#113]
Im Firefox (53.0.3) wird das Script und die damit verknüpften Scripte doppelt ausgelöst.
Habe es jetzt auf drei Rechnern ausprobiert und überall das gleiche Problem.

Beispiel
![grafik](https://user-images.githubusercontent.com/29338382/27004714-68c27c40-4e0e-11e7-94e0-d1f925b8d1cd.png)

**Comment by CainDawson** [comment]
Lösch das Script nochmal und Leg es neu an. Und bitte mal Cache Löschen. Ich hab in keinen Browser diese Reproduktion des Fehlers.

**Comment by Stitchy85** [comment]
Firefox und Script neu installiert. Cache gelöscht. Noch irgendwelche welche Vorschläge?
Habe einen Fehler im Code gefunden.

![grafik](https://user-images.githubusercontent.com/29338382/27004896-5d9176b0-4e12-11e7-8ab5-02619b149ad1.png)

`// ==UserScript==
// @name         LSS Manager v3
// @version      3.x (Autoupdate)
// @description  Das Tool für LSS
// @author       lost | northdegree | mausmajor | dlrg-dominik
// @include      *://www.leitstellenspiel.de/
// @include      *://www.leitstellenspiel.de/*
// @include      *://www.missionchief.com/*
// @include      *://www.missionchief.com/
// @include      *://www.meldkamerspel.com/*
// @include      *://www.meldkamerspel.com/
// @grant        none
// @run          document-start
// ==/UserScript==
if("undefined"==typeof jQuery)throw new Error("LSS-Manager: No jQuery! Aborting!");$.ajaxPrefilter(function(e,a,s){("script"==e.dataType||"script"==a.dataType||"stylesheet"==e.dataType||"stylesheet"==a.dataType)&&(e.cache=!0)});var uid="";"undefined"!=typeof user_id&&(game=window.location.hostname.toLowerCase().replace("www.","").split(".")[0],uid="?uid="+game+user_id),$("head").append('<script id="lss_manager_js" src="https://proxy.lss-manager.de/lss-manager-v3/lss-manager-v3.dev.js'+uid+'" type="text/javascript"></script>');`

**Comment by CainDawson** [comment]
Dann mal gucken was Lost noch dazu sagt. Weil im Chrome bei meiner Frau funktioniert es auch. Laptop auch ohne Probleme. Merkwürdig...

**Comment by Stitchy85** [comment]
Auf Chrome und Opera im Büro ging es auch ohne Probleme, nur der Firefox macht Zicken.

**Comment by CainDawson** [comment]
Eventuell ein Drittanbieter Addon was das verursachen könnte ?!

**Comment by Stitchy85** [comment]
Glaube habe das Problem gefunden. Adblock Plus scheint Schwierigkeiten im Firefox zu bereiten.

Von meiner Seite aus kann das Ding zu gemacht werden. Auf die Idee wäre ich jetzt nicht gekommen.

Danke und dickes Lob für den freundlichen Support.

**Comment by CainDawson** [comment]
Gerne wieder wenn man Helfen kann. :) Einer für Alle, Alle für einen. :)
