### ISSUE TITLE
Einsatzhelfer nicht am funktionieren

### ISSUE THREAD

**Issue by JonasFeuerwehr** [LSS-Manager/lss-manager-v3#1140]
Hallo! Ich habe den Einsatzhelfer aktiviert und schon ein paar Monate benutzt. Auf einmal ist er nicht mehr da. Kann mir da jemand helfen?

~Grüße

**Comment by jxn-30** [comment]
Leere bitte einmal deinen Cache, dann sollte es wieder tun:
1. im Spiel Strg+Umschalt+Entf drücken
2. Im Auswahlfenster darauf achten, dass **nur** der Cache ausgewählt ist, ansonsten drohst du Einstellungen zu verlieren
3. Das Spiel mit Strg+F5 neu laden.

Der Einsatzhelfer sollte dann wieder problemlos laden.

**Comment by JonasFeuerwehr** [comment]
Also da steht dann noch "[Die letzte Stunde] Löschen"
Was soll ich da machen?

Die [ ] sollen eine Box darstellen.

**Comment by jxn-30** [comment]
Dort sollte es egal sein, was du auswählst, da die Option nicht beachtet werden sollte.

**Comment by JonasFeuerwehr** [comment]
Achso okay.

**Comment by JonasFeuerwehr** [comment]
Perfekt! Funktioniert wieder.

Außerdem, was ist die aktuelle Version?

**Comment by jxn-30** [comment]
Freut mich, dass es wieder tut.

Die aktuellste Version ist 3.3.11

**Comment by JonasFeuerwehr** [comment]
Sehe ich die Verion, wenn ich auf den grünen button drückte?
