### ISSUE TITLE
Frage: Wie sehe ich, welche Version ich habe?

### ISSUE THREAD

**Issue by JonasFeuerwehr** [LSS-Manager/lss-manager-v3#1141]
Hallo!
Wenn ich auf den grünen Button oben rechts drückte, sehe ich "Stable: 3.3.11". Ist das die Version?

**Comment by jxn-30** [comment]
Ja, genau das ist die Version.

**Comment by JonasFeuerwehr** [comment]
Wenn ich aber weiter unten auf "Einstellungen" gehe, steht oben rechts "Version 1.2"
Was ist das?

**Comment by jxn-30** [comment]
Das ist die Versionsnummer der Einstellungs-Verwaltung.

**Comment by jxn-30** [comment]
Ja. Es ist nahezu unmöglich, eine veraltete Version zu haben, wenn du den Original-LSSM nutzt (und das tust du, wie die meisten). Manchmal kommt es zu Problemen mit dem Cache, aber die lassen sich wie in #1140 beschrieben einfach beheben.

Da der LSSM V.3 aber nur noch sehr selten Updates bekommt, musst du dir da auch keine Sorgen machen, da etwas zu verpassen.

**Comment by JonasFeuerwehr** [comment]
Ach gut. Danke dann!
