### ISSUE TITLE
Vorschlag: Fahrzeugsuchleiste im Einsatzmenü

### ISSUE THREAD

**Issue by JonasFeuerwehr** [LSS-Manager/lss-manager-v3#1142]
Hallo! Ich suche andauernd meine Fahrzeuge im EInsatzmenü. Ich schlage hier mit vor, eine Suchleiste als Finktion anzubieten, die dann bei allen 3 Kategorien (Fahrzeuge auf Anfahrt, Fahrzeuge an der Einsatzstelle, Freie Fahrzeuge) nach dem eingegebenen FUnkrufnamen sucht und alle, die nicht passen auszublenden. Man kann in den Einstellungen einstellen, eine Checkbox anzuzeigen, mit die nur genaue Treffer der Suche anzeigt.

Die Suchleiste ist für Leute, die Alarm und Ausrückeordnungen kaum/gar nicht benutzen.
Die Checkbox ist dafür da, wenn man nur ein bestimmtes Fahrzeug schicken möchte.

~Grüße

PS: Könnte schwierig werden, dass zu programmieren. Aber ihr schaftt das schon!

**Comment by jxn-30** [comment]
Für die Tabelle(n) der freien Fahrzeuge gibt es bereits spielseitig eine Suchleiste (das kleine Lupen-Icon im Tabellen-Kopf).

Suchleisten für die anderen Tabellen kann man sich überlegen.

Da die Version 3 des LSS-Manager allerdings nicht mehr weiterentwickelt wird, schließe ich hier!
Wenn dann wäre das was für die V.4
