### ISSUE TITLE
VORSCHLAG: Markierungen setzen auf der Karte

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#116]
Hey,

mir ging grade folgendes durch den Kopf. Kann man eine Art Markierungen setzen, möglichst viele müssten das dann sein. Da ich zum Beispiel die Wachen nach realer Standorte baue, würde ich da durch gerne gleich direkt Markierungen setzen, bevor ich bauen kann. Damit man am ende nicht ewig suchen muss.

Würde so was gehen?
Würden die Markierungen auch dauerhaft gespeichert bleiben?

Liebe Grüße,
Cain

**Comment by Mausmajor** [comment]
Ich denke da ist was möglich.

Was sollte bei so einer Markierung alles gespeichert werden? Bzw. was möchtest du alles eingeben können?

**Comment by Tsumiki-Chan** [comment]
Ich denke mal du spielt hier auf eine Art Wachenplanung an.

Siehe Mausmajor, was soll, bis auf die Position, gespeichert werden? Die umsetzung an sich ist relativ easy.
