### ISSUE TITLE
Bug im Alarmfenster

### ISSUE THREAD

**Issue by Merlingilb** [LSS-Manager/lss-manager-v3#117]
Wenn im Alarmfenster, die linke Seite länger ist als die rechte wird unten etwas abgeschnitten.
![](http://i.imgur.com/SLfVXsL.png)
Ich benutzte Edge.

edit by lost:
### Module
-Layout04
-MissionOut
-Clock
-allianceMissionlistShare
-dashboard
-WachenHoverStati
-RenameFZ
-telemetry
-mapreload
-showBackAlarmAbove
-missionHelper

**Comment by lostdesign** [comment]
Aktivierten Module?

**Comment by Merlingilb** [comment]
Einsätze freigeben
Fahrzeuge umbenennen
Layout 04
Missionout
Show back alarm above
Clock
Wachen Status
Dashboard
Einsatzhelfer

**Comment by Merlingilb** [comment]
ok ohne lss das gleiche problem
aber viellericht könnt ihr ja was ändern

**Comment by lostdesign** [comment]
Schon besser. Wir schauen es uns an :D
