### ISSUE TITLE
RenameFZ

### ISSUE THREAD

**Issue by Baumi4480** [LSS-Manager/lss-manager-v3#1170]
Moin, 

beim THW wird das Zugfahrzeug des Anh Hund als MTW- OV ausgeführt. Nach einer Änderung des Spiels heißt der aber nun MTW-O.
Das OV müsste dann zum MTW Ortsverband gehören.

**Comment by Suchty112** [comment]
https://github.com/LSS-Manager/lss-manager-v3/blob/master/lss-manager-v3/helperfunctions.js#L1002
https://github.com/LSS-Manager/lss-manager-v3/blob/master/lss-manager-v3/helperfunctions.js#L1033 
die ID's und Namen bei uns stimmen mit denen Ingame überein. Daher seh ich hier kein Fehler
