### ISSUE TITLE
VORSCHLAG: Wachen Umbenennen über Leitstelle

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#118]
Hey,

mir ist gerade was eingefallen. Und zwar:
Wäre es Super wenn man Wachen Umbenennen könnte über die Leitstelle. So wie es mit den Fahrzeugen bereits in der Leitstellenansicht unter Fahrzeuge ist.

**Comment by Mausmajor** [comment]
Solange vom  Spiel aus die Möglichkeit nicht besteht sehe ich das als nicht erwünschte Funktion vom Spielbetreiber.

@lostdesign  du könntest das mal bei Sebastian erfragen wie er das sieht.

**Comment by Mausmajor** [comment]
Nach Rücksprache:
Solange vom Spiel  keine Möglichkeit geboten wird wie bei den FZ ohne Script, wird es von uns keine Möglichkeit zu geben.

**Comment by lostdesign** [comment]
Hab Sebastian mal gefragt.
