### ISSUE TITLE
BUG -- News-Feed von LSS wird nicht angezeigt

### ISSUE THREAD

**Issue by stefschen** [LSS-Manager/lss-manager-v3#119]
Hallo, 
mir ist aufgefallen, dass der News-feed (also die Benachrichtigung über neue Facebook einträge) von Sebastian bei aktiviertem Manager nicht tut

**Comment by lostdesign** [comment]
Liegt am `redesign01`. Bitte immer dazuschreiben welches Plugin aktiviert worden ist. Wird behoben.

**Comment by lostdesign** [comment]
Duplikat #100
