### ISSUE TITLE
Absenden Button im Alarmfenster zu Hell

### ISSUE THREAD

**Issue by GregorPaul** [LSS-Manager/lss-manager-v3#12]
## Fehlermeldung:
Der Rückmeldung Absenden Button ist kaum lesbar. Wäre gut wenn der weiterhin grün unterlegt wäre. Zumindest nach dem man was eingetippt hat

![bildschirmfoto 2017-05-23 um 08 24 58](https://cloud.githubusercontent.com/assets/28886972/26341041/f271b43c-3f91-11e7-860c-0863fdd0ecb6.png)

## Aktivierte Module:
- Uhr
- FMS 5 auf Karte

## Mögliche Lösung / Verbesserungsvorschlag:
...

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Erstmal close da redesign neu geschrieben wird. Später wird es dann nicht mehr auftreten.
