### ISSUE TITLE
Vorschlag Einsatzhelper ein/aus schalten

### ISSUE THREAD

**Issue by stefschen** [LSS-Manager/lss-manager-v3#120]
Wäre es möglich, den Einsatzhelfer so zu schreiben, dass man ihn, nur wenn benötigt einschalten kann ( Die Übersicht ist eindeutig besser als die im original ;) ) ... oder meinetwegen bei nicht-Bedarf ausblenden :)

Ich finde er nimmt sehr viel Platz weg, und die Fahrzeugliste verrutsch zum Teil nicht lesbar nach unten

gruß
Stefschen

**Comment by lostdesign** [comment]
Sehr gute Idee, wir wollten es noch viel kompakter machen. Wird dann so aussehen wie in der Wachenplanung.

**Comment by Suchty112** [comment]
Hätte jetzt hier ein vorschlag zu mindest erstmal mit nem button. das nimmt dann schonmal ein wenig platz weg @stefschen 
![grafik](https://user-images.githubusercontent.com/1109899/29387816-2ddae0e6-82e2-11e7-81c0-c325b3bf8abd.png)

**Comment by lostdesign** [comment]
Mhh der Button nimmt wieder eine komplette Zeile weg. Bitte kleiner & eventuell sollten wir den innerhalb des Einsatzhelfers packen @Suchty112

**Comment by KBOE2** [comment]
Wäre mit 94a12f9 eingebaut :)
