### ISSUE TITLE
Vehicle names in dashboard in Dutch Version (Meldkamerspel.nl)

### ISSUE THREAD

**Issue by DMCEM4** [LSS-Manager/lss-manager-v3#124]
In the dutch version of the game the Vehicles have different names. This is not dispayed accordingly in the Dashboard function. The same goes for the English version Missionchief.com

![bug-id](https://user-images.githubusercontent.com/29376272/27042132-61d4ce86-4f96-11e7-909d-e0a5dd4c6b8b.png)
_All german names instead of dutch counterparts._

**Complete list of all Vehicle ID's ingame so far.**
_Edited 13 from Suchty112's list and removed the ALL CAPS from number 22.
Thanks to Suchty112 for starting the list!_

0 SIV | Snel Interventie Voertuig
1 TS 8/9 | Tankautospuit (8/9 personen)
2 AL | Autoladder
3 DA-OVD-B | Officier van Dienst Brandweer
4 HV-G | Hulpverleningsvoertuig Groot
5 AB | Adembeschermingsvoertuig
6 TST 8/9 | Tankautospuit Terreinvaardig (8/9 personen)
7 TST 6/7 | Tankautospuit Terreinvaardig (6/7 personen)
8 TST 4 | Tankautospuit Terreinvaardig (4 personen)
9 TS 4 | Tankautospuit (4 personen)
10 SL | Slangenwagen
11 WvD | Waarschuwings- en Verkenningsdienst
12 TST-NBB 8/9 | Tankautospuit Natuurbrandbestrijding (8/9 personen)
13 TS8 | Tankautospuit Terreinvaardig (8 personen)
14 TST-NBB 6/7 | Tankautospuit Natuurbrandbestrijding (6/7 personen)
15 TST-NBB 4 | Tankautospuit Natuurbrandbestrijding (4 personen)
16 Ambulance
17 TS 6/7 | Tankautospuit (6/7 personen)
18 HW | Hoogwerker
19 DA-HOvD-B | Hoofd Officier van Dienst
20 DA | Dienstauto (4 personen)
21 DB | Dienstbus (9 personen)
22 DA Noodhulp | Dienstauto Noodhulp
23 Lifeliner
24 AGS | Adviseur Gevaarlijke Stoffen
25 DB Noodhulp | Dienstbus Noodhulp
26 HA | Haakarmvoertuig
27 ABH | Adembeschermingshaakarmbak
28 Politiehelikopter
29 WTH | Watertransporthaakarmbak
30 Zorgambulance | B-ambulance
31 CO | Commandovoertuig
32 COH | Commandohaakarmbak
33 WO | Waterongevallenvoertuig
34 TW | Tankwagen
35 OVD-P | Officier van Dienst - Politie
36 WOA | Waterongevallenaanhanger
37 MMT-Auto

**Comment by Suchty112** [comment]
Here the ID's for the Brandweer. @lostdesign 

0 SIV | Snel Interventie Voertuig
1 TS 8/9 | Tankautospuit (8/9 personen)
2 AL | Autoladder
3 DA-OVD-B | Officier van Dienst Brandweer
4 HV-G | Hulpverleningsvoertuig Groot
5 AB | Adembeschermingsvoertuig
6 TST 8/9 | Tankautospuit Terreinvaardig (8/9 personen)
7 TST 6/7 | Tankautospuit Terreinvaardig (6/7 personen)
8 TST 4 | Tankautospuit Terreinvaardig (4 personen)
9 TS 4 | Tankautospuit (4 personen)
10 SL | Slangenwagen
11 WvD | Waarschuwings- en Verkenningsdienst
12  TST-NBB 8/9 | Tankautospuit Natuurbrandbestrijding (8/9 personen)
13
14 TST-NBB 6/7 | Tankautospuit Natuurbrandbestrijding (6/7 personen)
15 TST-NBB 4 | Tankautospuit Natuurbrandbestrijding (4 personen)
16
17 TS 6/7 | Tankautospuit (6/7 personen)
18 HW | Hoogwerker
19 DA-HOvD-B | Hoofd Officier van Dienst
20 DA | Dienstauto (4 personen)
21 DB | Dienstbus (9 personen)
22
23
24 AGS | Adviseur Gevaarlijke Stoffen
25
26 HA | Haakarmvoertuig
27
28
29
30
31 CO | Commandovoertuig
32
34 TW | Tankwagen
35



The other ID's would have to be ambulances / rescue service and police. As well as the water guard.

**Comment by DMCEM4** [comment]
**FIRE:**
27 ABH  | Adembeschermingshaakarmbak
29 WTH | Watertransporthaakarmbak
32 COH | Commandohaakarmbak

Water Rescue
33 WO | Waterongevallenvoertuig
36 WOA | Waterongevallenaanhanger

**POLICE:**
22 DA NOODHULP | Dienstauto Noodhulp
25 DB Noodhulp | Dienstbus Noodhulp
28 Politiehelikopter
35 OVD-P | Officier van Dienst - Politie


**AMBULANCE**
23 Lifeliner
30 Zorgambulance | B-ambulance
37 MMT-Auto

**Comment by DMCEM4** [comment]
**Fire**
13 TS8 | Tankautospuit Terreinvaardig (8 personen)

**Ambulance**
16 Ambulance

**Comment by DMCEM4** [comment]
**Complete list of all ID's so far.**
_Edited 13 from Suchty112's list and removed the ALL CAPS from number 22._
Thanks to Suchty112 for starting the list!

0 SIV | Snel Interventie Voertuig
1 TS 8/9 | Tankautospuit (8/9 personen)
2 AL | Autoladder
3 DA-OVD-B | Officier van Dienst Brandweer
4 HV-G | Hulpverleningsvoertuig Groot
5 AB | Adembeschermingsvoertuig
6 TST 8/9 | Tankautospuit Terreinvaardig (8/9 personen)
7 TST 6/7 | Tankautospuit Terreinvaardig (6/7 personen)
8 TST 4 | Tankautospuit Terreinvaardig (4 personen)
9 TS 4 | Tankautospuit (4 personen)
10 SL | Slangenwagen
11 WvD | Waarschuwings- en Verkenningsdienst
12 TST-NBB 8/9 | Tankautospuit Natuurbrandbestrijding (8/9 personen)
13 TS8 | Tankautospuit Terreinvaardig (8 personen)
14 TST-NBB 6/7 | Tankautospuit Natuurbrandbestrijding (6/7 personen)
15 TST-NBB 4 | Tankautospuit Natuurbrandbestrijding (4 personen)
16 Ambulance
17 TS 6/7 | Tankautospuit (6/7 personen)
18 HW | Hoogwerker
19 DA-HOvD-B | Hoofd Officier van Dienst
20 DA | Dienstauto (4 personen)
21 DB | Dienstbus (9 personen)
22 DA Noodhulp | Dienstauto Noodhulp
23 Lifeliner
24 AGS | Adviseur Gevaarlijke Stoffen
25 DB Noodhulp | Dienstbus Noodhulp
26 HA | Haakarmvoertuig
27 ABH | Adembeschermingshaakarmbak
28 Politiehelikopter
29 WTH | Watertransporthaakarmbak
30 Zorgambulance | B-ambulance
31 CO | Commandovoertuig
32 COH | Commandohaakarmbak
33 WO | Waterongevallenvoertuig
34 TW | Tankwagen
35 OVD-P | Officier van Dienst - Politie
36 WOA | Waterongevallenaanhanger
37 MMT-Auto

**Comment by Tsumiki-Chan** [comment]
Could you open your web browser console (Ctrl+Shift+I or F12) and type this:
`console.log(I18n.locale)`

I need the output :3

**Comment by DMCEM4** [comment]
console.log(I18n.locale)
nl       VM255:1
undefined

**Comment by Tsumiki-Chan** [comment]
Whyever you have undefined there. But thanks, that's what I needed

**Comment by DMCEM4** [comment]
![console](https://user-images.githubusercontent.com/29376272/27241216-29f932aa-52d8-11e7-950f-1002e4251b80.png)

**Comment by Tsumiki-Chan** [comment]
Here's something else I need:

```
lssm.carsById = {
  "0": ["SIV | Snel Interventie Voertuig", 0],
  "1": ["TS 8/9 | Tankautospuit (8/9 personen)", 0],
  "2": ["AL | Autoladder", 0],
  "3": ["DA-OVD-B | Officier van Dienst Brandweer", 0],
  "4": ["HV-G | Hulpverleningsvoertuig Groot", 0],
  "5": ["AB | Adembeschermingsvoertuig", 0],
  "6": ["TST 8/9 | Tankautospuit Terreinvaardig (8/9 personen)", 0],
  "7": ["TST 6/7 | Tankautospuit Terreinvaardig (6/7 personen)", 0],
  "8": ["TST 4 | Tankautospuit Terreinvaardig (4 personen)", 0],
  "9": ["TS 4 | Tankautospuit (4 personen)", 0],
  "10": ["SL | Slangenwagen", 0],
  "11": ["WvD | Waarschuwings- en Verkenningsdienst", 0],
  "12": ["TST-NBB 8/9 | Tankautospuit Natuurbrandbestrijding (8/9 personen)", 0],
  "13": ["TS8 (4x4)", 0],
  "14": ["TST-NBB 6/7 | Tankautospuit Natuurbrandbestrijding (6/7 personen)", 0],
  "15": ["TST-NBB 4 | Tankautospuit Natuurbrandbestrijding (4 personen)", 0],
  "16": ["Ambulance", 0],
  "17": ["TS 6/7 | Tankautospuit (6/7 personen)", 0],
  "18": ["HW | Hoogwerker", 0],
  "19": ["DA-HOvD-B | Hoofd Officier van Dienst", 0],
  "20": ["DA | Dienstauto (4 personen)", 0],
  "21": ["DB | Dienstbus (9 personen)", 0],
  "22": ["DA NOODHULP | Dienstauto Noodhulp", 0],
  "23": ["Lifeliner", 0],
  "24": ["AGS | Adviseur Gevaarlijke Stoffen", 0],
  "25": ["DB Noodhulp | Dienstbus Noodhulp", 0],
  "26": ["HA | Haakarmvoertuig", 0],
  "27": ["ABH | Adembeschermingshaakarmbak", 0],
  "28": ["Politiehelikopter", 0],
  "29": ["WTH | Watertransporthaakarmbak", 0],
  "30": ["Zorgambulance | B-ambulance", 0],
  "31": ["CO | Commandovoertuig", 0],
  "32": ["COH | Commandohaakarmbak", 0],
  "33": ["WO | Waterongevallenvoertuig", 0],
  "34": ["TW | Tankwagen", 0],
  "35": ["OVD-P | Officier van Dienst - Politie", 0],
  "36": ["WOA | Waterongevallenaanhanger", 0],
  "37": ["MMT-Auto", 0]
}
```

Could you please change the last number (, 0]) according to the correct group?

0 = Firefighter
1 = Rescue
2 = Police

(You shouldn't have any other groups)

**Comment by DMCEM4** [comment]
`lssm.carsById = {
  "0": ["SIV | Snel Interventie Voertuig", 0],
  "1": ["TS 8/9 | Tankautospuit (8/9 personen)", 0],
  "2": ["AL | Autoladder", 0],
  "3": ["DA-OVD-B | Officier van Dienst Brandweer", 0],
  "4": ["HV-G | Hulpverleningsvoertuig Groot", 0],
  "5": ["AB | Adembeschermingsvoertuig", 0],
  "6": ["TST 8/9 | Tankautospuit Terreinvaardig (8/9 personen)", 0],
  "7": ["TST 6/7 | Tankautospuit Terreinvaardig (6/7 personen)", 0],
  "8": ["TST 4 | Tankautospuit Terreinvaardig (4 personen)", 0],
  "9": ["TS 4 | Tankautospuit (4 personen)", 0],
  "10": ["SL | Slangenwagen", 0],
  "11": ["WvD | Waarschuwings- en Verkenningsdienst", 0],
  "12": ["TST-NBB 8/9 | Tankautospuit Natuurbrandbestrijding (8/9 personen)", 0],
  "13": ["TS8 (4x4)", 0],
  "14": ["TST-NBB 6/7 | Tankautospuit Natuurbrandbestrijding (6/7 personen)", 0],
  "15": ["TST-NBB 4 | Tankautospuit Natuurbrandbestrijding (4 personen)", 0],
  "16": ["Ambulance", 1],
  "17": ["TS 6/7 | Tankautospuit (6/7 personen)", 0],
  "18": ["HW | Hoogwerker", 0],
  "19": ["DA-HOvD-B | Hoofd Officier van Dienst", 0],
  "20": ["DA | Dienstauto (4 personen)", 0],
  "21": ["DB | Dienstbus (9 personen)", 0],
  "22": ["DA NOODHULP | Dienstauto Noodhulp", 2],
  "23": ["Lifeliner", 1],
  "24": ["AGS | Adviseur Gevaarlijke Stoffen", 0],
  "25": ["DB Noodhulp | Dienstbus Noodhulp", 2],
  "26": ["HA | Haakarmvoertuig", 0],
  "27": ["ABH | Adembeschermingshaakarmbak", 0],
  "28": ["Politiehelikopter", 2],
  "29": ["WTH | Watertransporthaakarmbak", 0],
  "30": ["Zorgambulance | B-ambulance", 1],
  "31": ["CO | Commandovoertuig", 0],
  "32": ["COH | Commandohaakarmbak", 0],
  "33": ["WO | Waterongevallenvoertuig", 0],
  "34": ["TW | Tankwagen", 0],
  "35": ["OVD-P | Officier van Dienst - Politie", 2],
  "36": ["WOA | Waterongevallenaanhanger", 0],
  "37": ["MMT-Auto", 1]
}`

In Dutch:
0 = Brandweer
1 = Ambulance
2 = Politie


Would you also need the names of all the buildings?

**Comment by DMCEM4** [comment]
Oh, By the way. The status of the vehicle also isn't shown correctly in the dashboard because the numbers aren't the same, as stated in my other issue.
