### ISSUE TITLE
Mouseover Status numbers do not match.

### ISSUE THREAD

**Issue by DMCEM4** [LSS-Manager/lss-manager-v3#125]
In the Dutch version the Funkmelde status are different than in the German and English versions of the game. Therefore the beautifull mouse-over buildings to show vehicle status - Plugin does not work properly! The wrong colors are shown within the little screens.

Some images for examples:
![status2](https://user-images.githubusercontent.com/29376272/27042645-eb1300a4-4f97-11e7-9359-8dcf88adee21.png)
_All the vehicles are at the base, dutch status 5 and green color_
![status1](https://user-images.githubusercontent.com/29376272/27042684-0617b886-4f98-11e7-8f39-caac2ed95af4.png)
_mouse-over shows red/black blinking status 5_

The Dutch statusses are as follows:

**Status#  : Dutch    ////////   German** 
1: Uitgerukt                                   //////      Einsatz übernommen
2: Ter plaatse                                //////      Ankunft am Einsatzort
3: Vertrokken met patiënt            //////      Patient aufgenommen
4: Beschikbaar                             //////      einsatzbereit über Funk 
5: Op post                                   //////      einsatzbereit auf Wache
6: Buiten dienst                          //////       nicht einsatzbereit
7: Aanvraag spraak                    //////       Sprechwunsch

**Comment by Tsumiki-Chan** [comment]
Does the same problem occur when lss manager is disabled?

**Comment by DMCEM4** [comment]
How do you mean? Mouseover does not exist without LSS-Manager so ther can be no difference?

**Comment by Tsumiki-Chan** [comment]
Ohhh... now I get what you mean... I'll look into it.

**Comment by DMCEM4** [comment]
Haha, allright!  Let me know, if anything is unclear or if you need anything translated!

**Comment by Tsumiki-Chan** [comment]
Actually, cloud you right-click the correct status and do "inspect element"? I need the classes for them.

**Comment by DMCEM4** [comment]
Do you mean these?

<span class="building_list_fms building_list_fms_1">4</span>
<span class="building_list_fms building_list_fms_2">5</span>
<span class="building_list_fms building_list_fms_3">1</span>
<span class="building_list_fms building_list_fms_4">2</span>
<span class="building_list_fms building_list_fms_5">7</span>
<span class="building_list_fms building_list_fms_6">6</span>
<span class="building_list_fms building_list_fms_7">3</span>

**Comment by Tsumiki-Chan** [comment]
Okay... if you would excuse me... I need to kms...
