### ISSUE TITLE
Vorschlag: Einsätze einfärben

### ISSUE THREAD

**Issue by Thomas21030** [LSS-Manager/lss-manager-v3#128]
Ist es möglich die Einsätze ein zufärben in Form von  ?

Hintergrundfarbe wie bei Rauchentwicklung
Umrandung wie beim Traktor oder
Unterstrich wie bei  Linienbus einzuführen

Und das selbe dann auch in die EinsatzListe ?

Warum, dann kann mann sich jeden Einsätze individuell einfärben, und je nach Farbe entscheiden,

Beispiele:
Grün = immer freigeben z.B > Gasex oder Bauernhof gr. 
Gelb = freigeben, kann Groß werden > GG-LKW verungl. oder Hauswand
Orange = nur im Haupteinsatzgebiet freigeben > Sporthalle oder Reetdachhaus
Rot = Kleinkram nicht freigeben > Mülleimer oder Container

![11111farbe](https://user-images.githubusercontent.com/28989752/27100988-53a75c58-5080-11e7-9f06-d61603c0048b.JPG)

**Comment by lostdesign** [comment]
Es ist nur möglich die Farbe von dem linken Balken zu übertragen. Für individuelle Einsätze gelten auch individuelle Einschätzungen. Deshalb erstmal nicht möglich.

Jedoch ist es möglich so ein Plugin zu schreiben - allerdings würde das sehr viele Ressourcen brauchen. Ich bin mir nicht sicher wie das dann bei mehreren hundert Einsätzen laufen wird.
