### ISSUE TITLE
Anzeigefehler Wachen Layout 01

### ISSUE THREAD

**Issue by JanH8** [LSS-Manager/lss-manager-v3#13]
## Fehlermeldung:
Habe den Namen einer Wache geändert (tritt auch bei Fahrzeugumbenennungen auf), bin zurück zu Leitstellenspiel, und dann kam es zu dem Fehler (Siehe Bild)
![image](https://cloud.githubusercontent.com/assets/16578440/26346700/5bc10aa4-3fa7-11e7-8ea2-e56d92ba63c6.png)
## Aktivierte Module:
- LAYOUT 01
- EINSATZLISTE KOMPRIMIEREN
- CHAT POPUP
- FAHRZEUG TABLEAU
- FMS 5 IN DER KARTE
-RENAMEFZ

## Mögliche Lösung / Verbesserungsvorschlag:
- keine -

**Comment by lostdesign** [comment]
Fixed.
