### ISSUE TITLE
Nach Update auf Beta 3.2.3, REDESIGN 01 funktioniert nicht

### ISSUE THREAD

**Issue by BjoernEnd** [LSS-Manager/lss-manager-v3#132]
Hallo,

habe eben festgestellt, dass es ein Update gab. Seit diesem ist das REDESIGN 01 ohne Funktion.

Habe dieses auch OHNE alle anderen Module ausprobiert, selbes Ergebnis.

Hat noch jemand Probleme damit?

Gruß
Björn

**Comment by lostdesign** [comment]
Fixed im nächsten Update
