### ISSUE TITLE
Vehicle status and names in Dashboard-module in any verison

### ISSUE THREAD

**Issue by DMCEM4** [LSS-Manager/lss-manager-v3#133]
After a first round of fixes for the Dutch version of the Dashboard-module some errors unfortunately still remain:
![dash1](https://user-images.githubusercontent.com/29376272/27259947-54328542-541f-11e7-99da-8d3886c90272.png)
Translations added in red and 'slice' shown instead of actual type-name

![dash2](https://user-images.githubusercontent.com/29376272/27259962-aafd721a-541f-11e7-8abe-ecb2a60f9e8b.png)
Translations added in Red and Status not shown correct since the Status numbers of The Dutch Versions do not match the German version

If you need more info or translations I am more than willing to help!

@lostdesign edit:
- title changed since all versions are affected since update

**Comment by Thomas21030** [comment]
Das Slice stehe auch im Leitstellespiel drin bei Version 3.2.3

**Comment by lostdesign** [comment]
fixed im nächsten update
