### ISSUE TITLE
Vorschlag: Verbandseinsätze auf Karte aus/einblenden

### ISSUE THREAD

**Issue by BjoernEnd** [LSS-Manager/lss-manager-v3#134]
Hallo,

ich Nutze aktuell das Modul "CENTER MAP". Ich finde die Idee sehr gut. Aber gibt es evtl. noch die Möglichkeit als Modul die Verbandseinsätze ein und auszuschalten? Bei meinem Verband sind wir zwar eigentlich auf NRW Konzentriert, aber es gibt auch welche die in München oder Berlin agieren.

Somit ist der Zoom auf ganz Europa gerichtet *lach

Würde mich freuen, wenn das umsetzbar ist.

Viele Grüße
Björn

**Comment by jalibu** [comment]
Wäre technisch relativ simpel umzusetzen. Vielleicht sollte man sich dann aber doch überlegen, ob man nicht ein allgemeines Map-Plugin entwickelt, in dem man 3-4 Funktionalitäten zusammenfasst (Reload, Zoom-Level, etc...)

**Comment by jalibu** [comment]
@lostdesign, wenn ich es recht verstehe, dann ist das Reload-Plugin immer aktiviert, weil es aufgrund irgendwelcher Anpassungen ab und an nötig werden könnte?

Es knüpft sich da nun eben die Frage an, ob man den Reload-Button ebenfalls in ein allgemeineres Map-Plugin packt und das dann eben auch immer aktiviert lässt. Mit individuell ein- und ausschaltbaren Optionen versteht sich.

Die Side-by-side und integrierte Alternative hätten beide ihre Vor- und Nachteile über die man durchaus diskutieren kann.

**Comment by jalibu** [comment]
Stelle mir das so vor...
Buttons auf der Karte:
1. Reload / Neuausrichtung (Refresh Logo wie bisher)
2. Einstellungen (Zahnrad Logo oder ähnliches)

Einstellungen / Optionen
1. Standard (Center und Default-Zoom auf Leitstelle)
2. Alle Einsätze auf einen Blick
    -- Mit Option "Verbandeinsätze berücksichtigen"
3. "Aktuellen Kartenausschnitt als Standard setzen". Speichert die aktuellen Koordinaten und das Zoom Level.

Beim Page-Load und beim Klick auf den Refresh Button wird die Karte entsprechend ausgerichtet.

**Comment by lostdesign** [comment]
**Map-Reload muss immer ein standalone Plugin bleiben, bis LSS auf Vector-Maps setzt**

Ein Map Plugin wäre sinnvoll, mit Settings wie:
» Centermap (wie aktuell) / Fokus eigene oder alle Einsätze
» Zoom Stufe speichern
» & deine 3. Funktion

Das Einstellungsfenster soll aber im Dropdown landen, da dort alle Plugins mit Einstellungen aufgelistet werden. 

Siehe Notification Plugin:
```js
...,
    settings: {
        has: false,
        function_code: "NotificationAlarm_show_settings"
    },
...
```

**Comment by jalibu** [comment]
Umgesetzt mit https://github.com/LSS-Manager/lss-manager-v3/commit/53de78fb864d71618888ce59ea9675be8add32a3
