### ISSUE TITLE
FMS5 Statusposition

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#135]
Position wird nun zwar gespeichert, wird aber die Fenstergröße geändert, bleibt die Anzeige trotzdem noch an der Position
https://drive.google.com/file/d/0B9oDPjS3kltlMC1RMDY3QXlsdk0/view

**Comment by Mausmajor** [comment]
sollte im nächsten update halbwegs gefixt sein.
zumindest kann man dann nun nicht mehr aus dem sichtbaren Bereich raus.
Es könnte aber sein das man den cache leeren muss
