### ISSUE TITLE
Einsatzhelfer aktiv bei EVENTS

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#139]
Eventuell sollte man prüfen, ob man die Anzeige für den Einsatzhelfer nur auf reguläre Einsätze ausweitet.
Bei Events ist das eher überflüssig, nebenbei noch ein Anzeige fehler zusätzliche ;-) 

![grafik](https://user-images.githubusercontent.com/28895574/27381521-6f13aaec-5683-11e7-8456-e3c849bf929c.png)

**Comment by Suchty112** [comment]
Sollte gefixxt sein hier: https://github.com/LSS-Manager/lss-manager-v3/commit/122ecd27c7a3b7dae774ad9fbccecafdc9b5937e . :)
