### ISSUE TITLE
Anzeigefehler bei Layout 4

### ISSUE THREAD

**Issue by MaxiFF** [LSS-Manager/lss-manager-v3#14]
## Fehlermeldung:
Bei dem Layout 4 ist das Problem, das es nur komischerweißer sehr Selten Auftritt.
Wenn man Einsätze, Krankentransporte und Verbandseinsätze auf hat, schließt sich nicht die Fortschrittbalken bei den Verbandeinsätzen.

## Aktivierte Module:
- Layout04

## Mögliche Lösung / Verbesserungsvorschlag:
-

**Comment by lostdesign** [comment]
Sehr komisches verhalten - werden das genauer beobachten.

**Comment by lostdesign** [comment]
Schließe ich erstmal - scheint eher ein Bug von LSS gewesen zu sein.
