### ISSUE TITLE
Bug: Plugin: Redesign

### ISSUE THREAD

**Issue by ifconfig** [LSS-Manager/lss-manager-v3#141]
Hi,

wenn das Plugin Redesign eingeschaltet ist, funktioniert der Gebäudefilter nicht mehr. Es werden immer alle Gebäude in der Liste angezeigt.
<img width="538" alt="bildschirmfoto 2017-06-22 um 12 32 38" src="https://user-images.githubusercontent.com/998362/27429861-ed89ca6e-5746-11e7-8dc9-0305d8947b93.png">

System: MacBook Pro - MacOS Sierra 10.12.5
Browser: Chrome - alle Scripte außer LSS Manager V3 abgeschaltet

**Comment by lostdesign** [comment]
Wurde bereits in der nächsten Version gefixt.
