### ISSUE TITLE
CenterMap funktioniert nicht ganz

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#142]
Button zentriert die Karte nicht mehr komplett. Teile der Einsätze und Wachen sind abgeschnitten. Zoomstufe wird anscheinend nicht richtig eingestellt.

https://drive.google.com/file/d/0B9oDPjS3kltla1RsclNUajR0dUk/view

**Comment by jalibu** [comment]
Center Map zentriert bislang nur innerhalb der laufenden Einsätze.
Es macht jedoch aus meiner Sicht durchaus Sinn auch die Wachen mit in das Zoom-Gebiet mit aufzunehmen.

Ist nicht viel Arbeit. Mache ich bei Gelegenheit.

**Comment by jalibu** [comment]
Gefixt
