### ISSUE TITLE
Vorschlag: Einsatzliste sortieren

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#147]
Einfacher Vorschlag, die Einsatzliste nach bestimmten Werten sortieren lassen (wenn möglich), zum Beispiel Patientenanzahl, Dauer oder nach Ort und/oder Einsatzart gruppieren.

**Comment by KBOE2** [comment]
Referencing diesen Vorschlag im Forum: 
https://forum.leitstellenspiel.de/index.php?thread/11166-lss-manager-v3/&postID=295111#post295111

Setting Priority a bissl höher, da nicht geringe Nachfrage.

**Comment by KBOE2** [comment]
Ist mal zu #537 zusammengefasst
