### ISSUE TITLE
Vorschlag: Plugin Einsatzhelfer

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#148]
Den Einsatzhelfer um die Angabe der mögl. Credits erweitern.

**Comment by Suchty112** [comment]
Können wir gerne machen. :) Ist ja nur ne zeile mehr :)

**Comment by Suchty112** [comment]
https://github.com/LSS-Manager/lss-manager-v3/commit/4ec7a1057ee0b66fc7a585471346b4478982e54d ist umgesetzt. Auch für Missionchief.
