### ISSUE TITLE
Vorschlag: Filter für Krankenhäuser

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#149]
Basierend auf den alten Scripten im LSS-Forum:

Einen Filter einrichten, der Krankenhäuser ausblendet die 0 Betten frei haben und/oder FH-Abteilungen fehlen und/oder Abgabe (opt. einstellbar oder als fixwert über settings)

**Comment by jalibu** [comment]
Toll wäre auch, wenn man die maximale Entfernung einstellen könnte.

**Comment by jalibu** [comment]
Eine initiale Version wurde implementiert (nur KH). Sie muss noch etwas aufgehübscht werden und wird dann an die Beta-Tester verteilt.

**Comment by jalibu** [comment]
Nicht schließen, bis die UI von jemandem aufgehübscht wurde.
Funktional ist es fertig.

**Comment by FlorianRhausen** [comment]
Scheint noch nicht zu funktionieren:

![grafik](https://user-images.githubusercontent.com/28895574/28356293-d3c18dac-6c67-11e7-9240-94fa1a82c76c.png)

**Comment by Suchty112** [comment]
Es gibt 2 Einstellunge. Einmal dort beim RTW, und einmal unter Einstellungen. da auch schonmal geschaut In Sachen einstellungen? Weiß grad net was man da einstellen kann. Zumindest bei mir hat es gefunzt

**Comment by FlorianRhausen** [comment]
![grafik](https://user-images.githubusercontent.com/28895574/28358228-663bfca2-6c6e-11e7-987a-56ac8a04f8d6.png)

**Comment by Suchty112** [comment]
@jalibu das ist dein Part :)

**Comment by jalibu** [comment]
Fehler war reproduzierbar und wird mit folgendem Pull Request gefixt:
https://github.com/LSS-Manager/lss-manager-v3/pull/221

**Comment by KBOE2** [comment]
Ist funktionsfähig bereits umgesetzt.
