### ISSUE TITLE
FehlerHafte Einsatzbezeichnung

### ISSUE THREAD

**Issue by SCplayerHD** [LSS-Manager/lss-manager-v3#151]
Bei der Hilfolosen person ist auch RD einsatz

**Comment by lostdesign** [comment]
Kannst du das bitte ausführlicher machen?

**Comment by Suchty112** [comment]
Er meint wahrscheinlich die [LSS einsatzID 154](https://www.leitstellenspiel.de/einsaetze/154) , dort gibt es auch ein Pat. . Aber in den Missionkeywords gibt's beide HiloPe's nur mit POL 1 https://github.com/LSS-Manager/lss-manager-v3/blob/dev/modules/lss-missionKeyword/missionKeyword.user.js#L169

**Comment by MrWeezle** [comment]
wird im nächsten Update gefixed
