### ISSUE TITLE
Bug im plugin "Verbesserter Status 5"

### ISSUE THREAD

**Issue by Kuschi** [LSS-Manager/lss-manager-v3#154]
Wenn ich meine Status 5 abarbeite und der letzte Einsatz bereits einen transportfähigen Patienten sowie noch weitere NICHT transportfähige Patienten hat, wird der Einsatz geöffnet.

Ich vermute mal das es daran liegt das an selber Stelle wo sonst der "Zum nächsten Fahrzeug mit FMS 5" Button ist, in dem Fall der "Einsatz öffnen" button kommt.

Ist nichts gravierendes, aber ich denke doch das es nicht gewollt ist.

**Comment by MrWeezle** [comment]
doch ist genauso gewollt --> Kein Bug
