### ISSUE TITLE
Noise Complaint Required Vehicle Issue

### ISSUE THREAD

**Issue by Kpudlo** [LSS-Manager/lss-manager-v3#158]
Hello,

Just a small typo I found on the English version of LSS. For the Noise complaint mission, LSS is saying 1 ambulance is required, the mission actually calls for a Police Car. 

Thanks for such a great script!
![image](https://user-images.githubusercontent.com/4432822/27685353-ce2b6fba-5c9b-11e7-9cde-fc2f6c3bab69.png)
![image](https://user-images.githubusercontent.com/4432822/27685361-d8c7f1d2-5c9b-11e7-9571-852d3daf8eb2.png)

**Comment by Suchty112** [comment]
Oh sry. This fixed in the new version:
https://github.com/LSS-Manager/lss-manager-v3/commit/6b20a61cc371756f3f08723e903caee547986969

**Comment by Kpudlo** [comment]
Thanks! Awesome response time BTW!!!
