### ISSUE TITLE
Button zurückalarmieren nach oben

### ISSUE THREAD

**Issue by robs92** [LSS-Manager/lss-manager-v3#16]
Habe Layout 1 aktiviert.
Kann man die Buttons wieder nach oben holen, so wie in V2?
![2017-05-23 13_39_17-leitstellenspiel de - baue deine eigene leitstelle in deiner stadt](https://cloud.githubusercontent.com/assets/28887439/26352706/26bd7a16-3fbd-11e7-9e86-8dcedce4f987.png)

**Comment by Mausmajor** [comment]
sollte im nächsten Update kommen
