### ISSUE TITLE
Vorschlag: LSS-Einstellungen pro Account synchronisieren

### ISSUE THREAD

**Issue by CSA-Verweigerer** [LSS-Manager/lss-manager-v3#163]
Die Einstellungen (z.B. aktive Module/Layouts, Radiuseinstellungen, eigene VGE's) 
könnten anhand des Accountnamens synchronsiert werden, d.h. wenn ich mich auf einem anderen PC mit installiertem LSS-Manager einlogge, kann ich mich wie Zuhause fühlen :-)

**Comment by jalibu** [comment]
Das wird relativ schwer umsetzbar sein. Wir werden allerdings die Möglichkeit schaffen die Einstellungen in eine Datei zu exportieren, damit man sie an anderer Stelle wieder importieren kann.

Das ist nicht ganz das selbe, aber vielleicht als erster Schritt trotzdem nützlich für euren Bedarf.

**Comment by lostdesign** [comment]
Ist noch nicht so schwer - kann nur zu diesem Zeitpunkt nicht umgesetzt werden. Zukünftig werden die Einstellungen online in einem Keystore gespeichert. 

Die manuelle Verison Import / Export wird es bald geben, wurde von @jalibu umgesetzt.
