### ISSUE TITLE
Vorschlag: Bereits laufende Einsätze ausblenden

### ISSUE THREAD

**Issue by CSA-Verweigerer** [LSS-Manager/lss-manager-v3#164]
Einsätze, die in der Einsatzliste auf grün (wird abgearbeitet) stehen könnten auch ausgeblendet werden. Ich möchte mich nur um die Einsätze kümmern, die entweder Rot (oder wenigstens Gelb) sind

**Comment by Kuschi** [comment]
So etwas suche ich ebenfalls.
Kann ich mir prima als Option im plugin "missionout" vorstellen, bzw würde es mir dort am besten gefallen.

**Comment by KBOE2** [comment]
Ist mal zu #537 zusammengefasst
