### ISSUE TITLE
Vorschlag: AAO-Button je Einsatz einfärben

### ISSUE THREAD

**Issue by CSA-Verweigerer** [LSS-Manager/lss-manager-v3#165]
Ich habe (wie viele Spieler) AAO-Knöpfe, die ganze Einsätze Abbilden. Je mehr Knöpfe, desto schwieriger  wird es, den richtigen zu finden. 

Kann man den richtigen Button denn Entsprechend farblich hervorheben? (Siehe Screenshot)

![farbiger knopf kopie](https://user-images.githubusercontent.com/29802197/27747630-41ffc8a6-5dcc-11e7-8866-d44b56b005f3.jpg)

**Comment by lostdesign** [comment]
Da gibt es das AAO-Dropdown Modul, dort kannst du nach buttons suchen - ist das nichts?

**Comment by CSA-Verweigerer** [comment]
Doch, funktioniert auch, aber eine automatische Einfärbung finde ich intuitiver als im Dropdown zu suchen.

**Comment by CainDawson** [comment]
Das hat was, finde ich! Wenn man einen Einsatz hat und die AAO entsprechend schon eingefärbt zusätzlich ist damit man weiß was man anklicken muss. :) Erleichtert wirklich das Suchen.
Ja ich weiß, es gibt eine AAO-Suche App. Ich hab aber das Problem, das es immer Sekunden dauert bist jedes Modul geladen ist. Somit verzögert sich das ganz wieder und wenn ich wo klicken will, erscheint was und ich verklicker mich. Daher nutze ich die AAO-Suche nicht, auch nicht als Drop-Down. :)

**Comment by KBOE2** [comment]
Stellt einen zu großen Vorteil gegenüber anderen Nutzern dar.
Ausführliche Diskussionen und Meinungen dazu schwirren irgendwo im Spiel-Forum rum.
