### ISSUE TITLE
Dashboard mit Taste schließen

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#169]
> just a quick question, is there a quick way of closing the dashboard? (instead of clicking LSS Manager button and Dashboard button?)

Aufgrund MPR's Frage ob es sowas gibt, es aber leider nicht tut, dachte ich, das wäre doch ne nette idee eine Taste zu nehmen zum schließen. Wie ESC oder so

**Comment by lostdesign** [comment]
Esc jetzt nicht gerade aber eine Taste wäre super. ESC macht halt fürs öffnen keinen sinn & beendet den Fullscreen mode. Könnte zu Probleme führen.

**Comment by myselfolli** [comment]
Ich habe ein pull request zu diesem Thema erstellt. Bis dahin könnt ihr euch ein eigenes TamperMonkey Script mit folgendem Code anlegen:
`// ==UserScript==
// @name         LSS-Manager Dashboard Extention
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Open dashboard on keypress (d)
// @author       myselfolli
// @match        https://www.leitstellenspiel.de/
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    $(function(){
        $(document).keypress(function(e){
            console.log("Key pressed: " + e.keyCode);
            if (e.keyCode == 100){
                e.preventDefault();
                $("#lssm_db_activate").click();
            }
        });
    });
})();`

**Comment by KBOE2** [comment]
Mal so ne Frage, hätte sich das nicht eigentlich erledigt, nachdem das Dashboard jetzt in unsrer Lightbox ist?
Alternativ könnte man einbauen, dass sich unsere Lightboxen, genauso wie die im Spiel, auf `ESC` schliessen lassen.
