### ISSUE TITLE
Statistik/Dashboard im LSS Manager

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#17]
Fehlermeldung:
In den Einstellungen des LSS Manager ist über dem gesamten Teil der Einstellungen und dem Text die Statistik/das Dashboard, leer, drübergeschoben

 Aktivierte Module:
- Layout 04
- EINSATZLISTE KOMPRIMIEREN
- Dashboard
- Statistik
- Einsätze suchen

 Browser: Chrome
#### Beta Version: 0.1

**Comment by OiledAmoeba** [comment]
Duplicate #5
