### ISSUE TITLE
Gebäudefilter inkompatibel mit Wachenplanung

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#170]
Sobald die Wachenplanung aktiv ist funktioniert der Gebäudefilter nicht mehr. 
Es werden lediglich die Wachen angezeigt die vor der Aktivierung von der Wachenplanung da waren. Ich kann so oft wie ich will auf FW oder sonstiges klicken aber er ändert nichts.

Aktivierte Module:
DAshboard
Einsätze suchen
Einsätze freigeben
Meldedatum für Einsätze
MissionOut
Show back alarm above
Wachenstatus
Verbesserter FMS5
und natürlich Wachplanung auf der Karte

Mögliche Lösung:
Muss denke mal nur definiert werden Welche wachen im Gebäudefilter angezeigt werden sollen. Also nur gebaut und keine geplanten Wachen.

**Comment by lostdesign** [comment]
Dieser Bug kann nicht rekonstruiert werden.
