### ISSUE TITLE
Vorschlag: ManagedSettings soll Möglichkeit bieten Settings in Tabs darzustellen/ein- ausklappbar zu machen

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#172]
In den ManagedSettings sollte jedes Modul einzeln sichtbar sein. Entweder über Toggles oder pro Modul einen Tab, wo die jeweiligen Settings hinterlegt sind.

**Comment by Suchty112** [comment]
Wäre mit 3.3.4 drin . Hype
