### ISSUE TITLE
Vorschlag: ManagedSettings soll Möglichkeit "Reset Standardwerte" anbieten

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#176]
Als Nutzer möchte ich, dass ich die vom Plugin vorgegebenen Default Werte in den ManagedSettings zurücksetzen möchte.
Diese Option soll pro Modul angeboten werden und darf sich nicht auf andere auswirken.

**Comment by Tsumiki-Chan** [comment]
Wurde schon längst hinzugefügt
