### ISSUE TITLE
Vorschlag: ManagedSettings soll Datenvalidierung unterstützen

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#177]
Als Entwickler von Modulen möchte ich, dass ich den einzelnen Settings Validierungsoptionen/Gültigkeitsbereiche mitgeben kann, um Falscheingaben zu verhindern.

Etwa so:
`'validation: {
  'min-value:' 1,
  'max-value': 10,
  'regex' : 'blabla',
  'allow-empty': false
}'

Weitere Vorschläge und Ideen können hier im Ticket ergänzt werden.

**Comment by Mausmajor** [comment]
Idee: wir machen ein Bereich Option: und dem können wir alle Attribute die das HTML Element hat zuweisen mit dein einzelnen Werten und beim erstellen werden die Option durchgelaufen und die Attribute einfach gesetzt.
Für die validation könnte man sich noch überlegen ob man da was dazu schreibt das der User eine Info box oder so bekommt.
