### ISSUE TITLE
Bug: Die Darstellung der ManagedSettings erfüllt nicht die Ansprüche attraktiver Web-Anwendungen

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#178]
Die Darstellung der ManagedSettings ist noch rudimentär umgesetzt. Ein Polishing ist hier dringend nötig, um eine zufriedenstellende User-Experience zu gewährleisten.

**Comment by lostdesign** [comment]
Ich hab heute schonmal reingeschaut. Werde das ganze natürlich optisch anpassen.

**Comment by MrWeezle** [comment]
Floating für toggles ist nicht optimal:
https://images.discordapp.net/attachments/330032719021211648/332117313522237442/image.png?width=400&height=173

**Comment by MrWeezle** [comment]
Labels zu Input-Fields Layout ebenfalls nicht ideal
![image](https://user-images.githubusercontent.com/6639017/27862251-9d3d6bc2-6184-11e7-9213-e03071c99edd.png)

**Comment by KBOE2** [comment]
Settings sind mittlerweile aufgehübscht. Jedes Modul hat seinen eigenen Tab.
