### ISSUE TITLE
Einsätze Suchen bei Layout 3

### ISSUE THREAD

**Issue by IngoL91** [LSS-Manager/lss-manager-v3#18]
## Fehlermeldung:
Wenn du nach z.b Gas die Einsätze sucht taucht leider keine Liste auf wo die ID Nummer der Einsätze stehen.

## Aktivierte Module:
- 

## Mögliche Lösung / Verbesserungsvorschlag:
-

**Comment by lostdesign** [comment]
![bildschirmfoto 2017-05-23 um 14 22 06](https://cloud.githubusercontent.com/assets/5164617/26354041/3dbd4218-3fc3-11e7-87e9-81331dfd450e.png)

Bei mir ist die sichtbar - welchen Browser hast du?

**Comment by IngoL91** [comment]
sorry meine den layout 3

**Comment by lostdesign** [comment]
fixed
