### ISSUE TITLE
Vorschlag: ManagedSettings alphabetisch nach Modul ordnen

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#185]
Die Reihenfolge der einzelnen Module in den Settings ändert sich jedesmal, wenn die Seite neu geladen wird. Hier wäre es besser, wenn der LSSM die Settings alphabetisch nach Modul sortieren würde.
![image](https://user-images.githubusercontent.com/6639017/27862449-7d46ac56-6185-11e7-9f02-c540c8f37cfc.png)

![image](https://user-images.githubusercontent.com/6639017/27862466-8aced7fe-6185-11e7-8204-516e87ffbe22.png)

**Comment by jalibu** [comment]
Die Ursache ist eine ganz einfache Race-Condition.
Der LSSM Core lädt die einzelnen Plugins und in der Reihenfolge der HTTP-Responses, bzw. dem jeweiligen JS Parsing registrieren die einzelnen Module dann ihre Settings.

Diese Reihenfolge ist nicht deterministisch.

Da dies kein Bug (und schon gar kein critical Bug) ist, wandle ich das mal in einen Vorschlag um.

**Comment by jalibu** [comment]
Fix in Pull Request: https://github.com/LSS-Manager/lss-manager-v3/pull/187

**Comment by lostdesign** [comment]
Offtopic, aber warum sieht die Einstellung pro Plugin anders aus? Das macht keinen Sinn.

**Comment by MrWeezle** [comment]
Die sehen deshalb anders aus, da ja unterschiedliche Funktionen benötigt werden. Oder was meinst du?
Für verbesserte S5 nen Switch zum aktiveren der Option, für die Stichworte gibt es Textfelder zum eingeben und für CenterMap radio buttons zum auswählen

**Comment by lostdesign** [comment]
Ist ja eigentlich egal, ich sorg schon für ein einheitliches Design ^^
