### ISSUE TITLE
Reloadbutton der Map funktioniert nicht

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#19]
Fehlermeldung:
 Der Reloadbutton für die Map will nicht.

Aktivierte Module:
- Layout 04
- Einsätze einklappen
- Dashboard
- Einsätze suchen
- RenameFz

Browser: Chrome
Version:Version 58.0.3029.96 (64-bit)
Beta Version: 0,1

**Comment by Tsumiki-Chan** [comment]
Ich sehe aktuell keinen Grund warum es nicht funktionieren sollte.

Benötigt die Map überhaupt einen Reload? Also hat die Map irgendwelche Bugs?
Der Reload hat keinen sichtbaren effekt, wenn die karte keinen reload braucht.

**Comment by brennerr** [comment]
Soweit ich das weiß braucht man den beim Layout01 da dort die Map "farbloser" ist als normal.

**Comment by Tsumiki-Chan** [comment]
Also wie gesagt, der map "reload" richtet die map nur neu aus, weil die sonst bugs hat, wenn man die Größe verändert

**Comment by brennerr** [comment]
Achso okay, dann hat sich das ja erledigt

**Comment by DLRG-Dominik** [comment]
closed da erledigt
