### ISSUE TITLE
Vorschlag: Funkspruch bei NEF Nachforderung

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#192]
Aus dem Forum: https://forum.leitstellenspiel.de/index.php/Thread/11792-Benachrichtigung-wenn-NEF-ben%C3%B6tigt-wird/

> Hallo Kameraden,
> 
> ich wollte mal fragen ob es möglich wäre, dass man wenn ein NEF benötigt wird automatisch einen Funkspruch oder eine Benachrichtigung erhält,
> sodass man nicht immer durch die ganzen Einsätze scrollen muss um zu schauen, ob ein NEF benötigt wird.

Das sollte von uns umsetzbar sein, wenn man sich in die patientMarkerAdd() von LSSM einklinkt, t.missing_text ablauscht und bei "Wir benötigen ein NEF." einen Funkspruch generiert.

**Comment by lostdesign** [comment]
test kommentar - lösch ich gleich wieder

**Comment by Suchty112** [comment]
Umgesetzt in #196 Damit Close
