### ISSUE TITLE
Vorschlag: Link "Fehler melden" in LSSM Dropdown einbauen

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#194]
Als Nutzer von LSSM möchte ich die Möglichkeit haben Fehler an die Entwickler zu melden. Im Dropdown zum LSSM soll daher ein Link zum Issue Tracker der Github Seite eingebaut werden.

**Comment by lostdesign** [comment]
Meh. Vll. im Appstore, ansonsten wurde es oft genug erwähnt.

**Comment by jalibu** [comment]
Alternativ wäre ein "About" Eintrag sinnvoll, hinter dem wir alle sonstigen Infos und Link-Outs bündeln können (Link zur Webseite, Link zu Github, Credits, etc).

Nur weil es oft genug erwähnt wurde, ist es aus meiner Sicht nicht unnötig.

**Comment by lostdesign** [comment]
--> Website.
