### ISSUE TITLE
Rückbau Coin Confirm

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#197]
Da diese Funktionalität mittlerweile weitestgehend nativ im Spiel integriert ist, brauchen wir sie nicht länger unterstützen.

**Comment by lostdesign** [comment]
Würde es ne zeitlang als 'develop' drinnen lassen, mit der Beschreibung, dass das Plugin ins Game übernommen worden ist.

**Comment by jalibu** [comment]
Wenn sie als 'develop' drin ist, lässt sie sich allerdings nicht mehr deaktivieren.
