### ISSUE TITLE
Neue Designauswahl deaktiviert altes Design nicht

### ISSUE THREAD

**Issue by OiledAmoeba** [LSS-Manager/lss-manager-v3#2]
## Fehlermeldung:
Wenn ich das Design ändere, dann bleibt ein voriges Design aktiviert. Die Aktivierung eines anderen Design sollte das davor aktive Design deaktivieren.

## Aktivierte Module:
- 

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Hi, wir waren uns dessen bewusst - eigentlich sollte jeder soweit denken können das man Layouts vermischt. Wir werden eine Schutzfunktion einbauen aber auch als *Komfort* Funktion - dann muss man nicht dran denken.

**Comment by Tsumiki-Chan** [comment]
Wurde zusammen mit https://github.com/LSS-Manager/lss-manager-v3/issues/24 gefixed.
