### ISSUE TITLE
Scrollreiter der Wachen- und Funkspruchfenster 

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#20]
## Fehlermeldung:
Im Wachenkasten gibt es zwei Reiter zum Scrollen. Der innere bewegt die vers. Auswahlmöglichkeiten ( Feuerwehr,RD, etc.) und die dazugehörigen Ergebnisse. Bei diesem kann man dann die Auswahl, also alle FW Wachen oder sonstiges bis unter den Kasten von Wachen scrollen.

![bildschirmfoto 2017-05-23 um 14 45 36](https://cloud.githubusercontent.com/assets/28895958/26354832/a77ffae4-3fc6-11e7-9f1f-8cbd0f927a41.png)

## Aktivierte Module:
- Layout04
- Einsätze einklappen
- Einsätze freigeben
-Einsätze suchen
- RenameFz

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
fixed.
