### ISSUE TITLE
[Einsatzhelfer] STROHBALLEN QUALMEN IN SCHEUNE

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#200]
Folgende Fahrzeuge werden hierzu benötigt:

5 Löschfahrzeuge (LF), 1 GW-A oder AB-Atemschutz, 1 ELW 1

Folgender Fehler wird mir angezeigt:

Benötigte Fahrzeuge
[missing "de.lssm.missionHelper.299" translation]

**Comment by Suchty112** [comment]
Es ist im DevBranch schon drinne. Ich weiß, das es leider blöd ist mit den Eonsätzen Freitags und unserem Updateprozess. Aber in den nächsten Tagen kommt die neue Version und da wird es drin sein

**Comment by CainDawson** [comment]
Och macht euch kein Stress, mir viel es nur auf. :)
