### ISSUE TITLE
Vorschlag: Definitionen für Einsatzhelfer vom LSSM Release entkoppeln

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#201]
Als Nutzer des LSSM Plugins "Einsatzhelfer" möchte ich immer möglichst zeitnah alle Einsatzdefinitionen haben.
Diese sind momentan noch an die Release-zyklen von LSSM gekoppelt. Man könnte diese trennen, indem man die Einsatzdefinitionen losgelöst in einer JSON Datei oder einem REST Service zur Verfügung stellt, die das Plugin anschließend konsumiert.

**Comment by MrWeezle** [comment]
im gleichenZug auch für Einsatzstichworte umsetzen

**Comment by jalibu** [comment]
Architekturvorschlag

![image](https://user-images.githubusercontent.com/25933231/28303915-b6155d10-6b95-11e7-9739-012f152f3a96.png)

**Comment by jalibu** [comment]
Die lokalisierte Mission Service Response für DE könnte zum Beispiel so aussehen:
```
{
  "0": {
    "name": "Mülleimerbrand",
    "avgCredits": "110",
    "vehicles": {
      "0": {
        "quantitiy": 1,
        "probability": 100
      }
    },
    "expansionOptions": [],
    "defaultAao": "B 1"
  },
  "2": {
    "name": "Irgendwas",
    "avgCredits": "110",
    "vehicles": {
      "0": {
        "quantitiy": 3,
        "probability": 100
      },
      "3": {
        "quantitiy": 1,
        "probability": 100
      },
      "5": {
        "quantitiy": 1,
        "probability": 70
      },
    },
    "expansionOptions": [],
    "defaultAao": "B 2"
  }
}
```

**Comment by jalibu** [comment]
Im Branch 201-NodeMissionCrawler habe ich einen prototypischen Entwurf umgesetzt.
Ein Crawler/Indexer in NodeJS sammelt automatisch alle Einsatzdefinitionen und schreibt sie in eine json Datei (bisher nur in DE, siehe Anhang).
Das Modul habe ich so umgebaut, dass es diese JSON Datei konsumieren kann.

[missions_DE.json.txt](https://github.com/LSS-Manager/lss-manager-v3/files/1161549/missions_DE.json.txt)

**Comment by Mausmajor** [comment]
Überlegung welche gegebenenfalls Ladezeiten sparen könnte, nicht alle Definitionen laden, sondern speziell die benötigte vom Server abfragen, natürlich mit Caching arbeiten. Hier kann man ja sogar einen Cachetime von mehreren Tagen wählen.

**Comment by Suchty112** [comment]
Sollte mit #519 mit unserem neuen Einsatzhelfer erledigt sein :) Viel Spaß und Have fun
