### ISSUE TITLE
[Vorschlag] Einsatzhelfer Position ändern

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#203]
Hallo,

wäre es möglich das man den Einsatzhelfer die Position ändern könnte. Ich muss immer ziemlich weit Scrollen wenn ich mit meinen Laptop/Netbook Spiele, was ja fast 90 % der fall ist.

Schön wäre es, wenn man die App Einsatzhelfer über die AAO setzen könnte. So muss ich nicht erst immer weit runter scrollen und sehe den Einsatzhelfer zuerst und dann kann ich eher meine AAO verwenden weil das dann als nächste erscheinen würde.

**Comment by Suchty112** [comment]
![grafik](https://user-images.githubusercontent.com/1109899/28081938-442bb3ee-6671-11e7-8148-9711079b0a1c.png)
Meinst du hier so? :D

**Comment by CainDawson** [comment]
Korrekt... Man kann ja sicherlich eine Funktion machen, das man sich das dann selbst definieren kann. Also so wie es zur Zeit ist und so wie ich es hätte. Weil das Netbook ist ja nicht groß und somit ist alles was rechts ist, ziemlich weit unten bei mir. :)

**Comment by Suchty112** [comment]
ich überleg mir da was. Soll das dann wenn es da oben ist auch so tief sein?(also alles autos unter einander wie es bis dato ist?), sonst muss ich da was umkrempeln im Script.....

**Comment by CainDawson** [comment]
Die Auflistung was im Einsatzhelfer steht ist egal, das kann so bleiben. Es reicht, wenn nur der Einsatzhelfer über der AAO ist. :)

**Comment by Suchty112** [comment]
Alles klar. Ich setz mich da mal ran. Kann dir aber nicht versprechen, das es im nächsten LSSM Update mit drin ist. Je nachdem wie weit ich komme xD

**Comment by CainDawson** [comment]
ok, besser als nichts. :) danke dir :)

**Comment by Suchty112** [comment]
Huhu Cain, ich hab ne Position gefunden wo es hinkommen könnte :D 
Sehe dann so aus:

![grafik](https://user-images.githubusercontent.com/1109899/28240445-2f918ec2-6982-11e7-8850-6b0621a6a3e1.png)

Wäre die Stelle ok? :)

**Comment by Suchty112** [comment]
Sollte mit #519 mit unserem neuen Einsatzhelfer erledigt sein :) Viel Spaß und Have fun
