### ISSUE TITLE
Sprechwünsche Layout 3

### ISSUE THREAD

**Issue by IngoL91** [LSS-Manager/lss-manager-v3#21]
Mir ist aufgefallen das die Sprechwünsche und die Funkrufe sich überscheiden.
![grafik](https://cloud.githubusercontent.com/assets/28859147/26356119/512a5644-3fcb-11e7-90f6-85cbffad1f4a.png)

Browser Googel Chrome
Version : 58.0.3029.110 ( 64bit)

**Comment by lostdesign** [comment]
Fixed.
