### ISSUE TITLE
[Einsatzhelfer] Einsatz: Abgestürzter Kletterer

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#212]
Folgende Fahrzeuge werden benötigt:
1 FuStW, 2 Löschfahrzeuge (LF), 1 Drehleiter (DLK 23), 1 ELW 1, 1 GW-Höhenrettung

Bekomme hier diesen Fehler:
[missing "de.lssm.missionHelper.300" translation]

**Comment by Suchty112** [comment]
Eigentlich sollte der schon online sein, da wir den EH ab jetzt immer in unseren Masterbranch machen, aber leider funktioniert der Proxy von North glaub ich net so richtig. Ich habs mir schon denken können, das jetzt einer hier nen Issue aufmacht :D . Aber trz danke. Wir haben das auf der Liste... bzw wäre es eigentlich schon seit gestern online für euch... Wir schauen da mal rüber...

**Comment by CainDawson** [comment]
Nur kein Stress. Was ich sehe. melde ich auch. :+1:

**Comment by Suchty112** [comment]
Alles klar, dann schließe ich den Issue wieder :) . Ich habs aber auf dem Schirm, weils mich selbst grad nervt das ihr sie nicht kriegt :D
