### ISSUE TITLE
Dashboard funktioniert nicht mehr richtig

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#213]
In unserer aktuellen Dev-Version funktioniert das Dashboard nicht mehr richtig
![2017-07-15 1](https://user-images.githubusercontent.com/1109899/28238911-c8b5ce0c-695e-11e7-8a54-a4ea12edac77.png)
![2017-07-15](https://user-images.githubusercontent.com/1109899/28238914-c8b819fa-695e-11e7-8ac9-a572492d09e6.png)
![2017-07-14 2](https://user-images.githubusercontent.com/1109899/28238913-c8b76a8c-695e-11e7-844f-b10a7dd8355f.png)

Inwiefern das mit der Fehlerbehebung der Sonarbugs ( https://github.com/LSS-Manager/lss-manager-v3/commit/ddd442acf0fd304aab0ef629f18e0a40d5f71619#diff-2f0d1ef4181a195878039df3c3f0c7a7 ) zu tun hat, müsste man mal überblicken, da dort die datei zumindest zuletzt bearbeitet wurde

**Comment by jalibu** [comment]
Das Problem lässt sich nach kurzer Analyse zumindest so eingrenzen, dass highcharts das series.data (cars[i].data) nicht schmeckt.

![image](https://user-images.githubusercontent.com/25933231/28247796-20931376-6a38-11e7-8609-d459206b492e.png)

**Comment by Suchty112** [comment]
fixxed in https://github.com/LSS-Manager/lss-manager-v3/commit/2e4afbbb48fc068aa3f57139c48027cc022b9ae9 . Thx sonar for this fucking bug :D
