### ISSUE TITLE
Vorschlag: AppStore in Modul auslagern

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#215]
Als Entwickler möchte ich eine möglichst funktionale Kapselung des Codes. Momentan ist der AppStore Teil des LSSM Cores.
Es wäre zu prüfen, ob die View des AppStores in ein eigenes, standardmäßig aktiviertes Modul ausgelagert werden kann, um den Code schlanker und übersichtlicher zu machen.

**Comment by Tsumiki-Chan** [comment]
Können wir im Zusammenhang mit der Webpack-Umstellung machen
