### ISSUE TITLE
Bug: LSSM v3 funktioniert nicht mehr!

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#217]
Hey,

mir fällt gerade auf, das ging mir heute schon auf dem Laptop so, das LSSMv3 nicht mehr läuft. Es wird mir zwar oben rechts angezeigt aber darunter verbirgt sich nur der Link "Beta 3.2.4" aber der rest wie Dashboard & Co. steht nicht mehr da. Auch meine Vergrößerte Karte ist nicht mehr da. Sprich die Apps werden derzeit nicht ausgeliefert.

Ist das ein Bug oder woran liegt es?

Genutzt wird die aktuelle Version von Opera.

**Comment by Suchty112** [comment]
Ja ist ein Bug, aber nicht von deiner Seite aus sondern von unserer Seite. Ihr also die Betatester kriegt leider durch einen kleinen Fehler aktuell unsere DevVersion wo leider der localhost (also dein PC) als "Server" eingetragen ist. daher funktioniert nicht alles wie es soll.

**Comment by CainDawson** [comment]
Ok, warten oder muss ich im Discord irgendwas beachten, zwecks neuen Code oder sowas ?

**Comment by Suchty112** [comment]
Erstmal leider warten, soleid es mir tut. Wir müssen erst mal Aisaka an Land kriegen, damit er an seinem Server das wieder ändert.

**Comment by CainDawson** [comment]
Jut geht klar... :) Weiß ich Bescheid. :)

**Comment by Tsumiki-Chan** [comment]
Weird, ich dachte, das hätte ich gestern geändert.

Naja, fehler behoben, server-cache geleert. Sorry für die Downtime

**Comment by CainDawson** [comment]
Bestätige, Problem ist behoben :)
