### ISSUE TITLE
RTW fordert NEF per FMS5 obwohl NEF auf Anfahrt

### ISSUE THREAD

**Issue by MrNobody92** [LSS-Manager/lss-manager-v3#220]
Version: Beta 3.2.4
Browser: Google Chrome Version 59.0.3071.115 (Offizieller Build) (64-Bit)
Aktive Module: Clock, Dashboard, VGE Speichern, Keyboard A., Summe f. d. t. ZF., Verbesserte S5, Zielort Filter, NEF Nachforderung

Fehlerbeschreibung: Ich habe zu meinen RD-Einsätzen per AAO RTW und NEF alarmiert. Der RTW war vor dem NEF an der EST und ist in den Status 5 gewechselt und hat ein NEF angefordert, obwohl dieses bereits auf Anfahrt war. Der Fehler ist mir bis jetzt bei 3 Einsätzen aufgefallen.

**Comment by FlorianRhausen** [comment]
hab da noch eine Verbesserung. RTW und NEF sind beide vor Ort und es wird der NEF weiterhin zur Alarmierung angezeigt: 

![grafik](https://user-images.githubusercontent.com/28895574/28353022-fe606e7e-6c59-11e7-9393-e580ad550204.png)

**Comment by jalibu** [comment]
@FlorianRhausen das zweite wäre dann aber ein Bug im Basisspiel. Mit dieser Anzeige hab ich nichts am Hut :-)

**Comment by FlorianRhausen** [comment]
Soll ich es mal im Hauptforum vom LSS einmelden?

**Comment by jalibu** [comment]
@MrNobody92 und @AlleDieEsInteressiert:
Ich habe ein bisschen nachgeforscht und musste leider feststellen, dass sich die Nachforderung des NEFs (auch wenn es bereits auf Anfahrt ist) nicht so ohne weiteres verhindern lässt.

Hintergrund:
Die komplette "Magie" dieses Plugins ist es, auf ein vom Basis-Spiel gesendetes Event "MissingVehicles" zu lauschen und für den Fall, dass es sich um ein NEF handelt, einen entsprechenden Sprechwunsch zu generieren.
Dieses Event kommt vom Basis-Spiel jedoch immer. Ganz unabhängig davon, ob ein entsprechendes Fahrzeug bereits auf der Anfahrt ist oder nicht. Es reicht der Umstand, dass es noch nicht an der E-Stelle ist.
Um dies zu prüfen müsste die Logik im Hintergrund einmal in alle NEFs im Status 3 rein gucken und prüfen ob es der jeweiligen Mission zugeordnet ist. Das würde gehen - wäre aber ein Verstoß gegen eine Auflage, die uns nicht gestattet zusätzliche Requests an das Spiel zu senden.

Wir könnten uns diese Sache ja auch schön reden: Behaupten wir jetzt einfach mal die Besatzung vom RTW weiß nicht, dass die Leitstelle vorausschauend gedacht und ein NEF mit alarmiert hat. Dann wäre der Sprechwunsch ja legitim. Ich könnte einen Button "Quittieren"/"Verstanden"/"NEF ist auf Anfahrt. Ende" oder sowas einbauen, der den Sprechwunsch dann auch aus den Funksprüchen beseitigt.

Was anderes fällt mir momentan leider nicht ein.

**Comment by FlorianRhausen** [comment]
eventuell mit Sebastian besprechen, das er hier nochmal nachfasst und eine Lösung schafft, auf die Ihr dann wieder reagieren könnt?
