### ISSUE TITLE
Vorschlag: AAO über Einsatzliste

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#222]
Wäre es möglich, das man bestimmte AAO's definieren kann (begrenzt auf max. 3 Stück oder) die in der Einsatzliste zur direkten Alarmierung genutzt werden können?

![grafik](https://user-images.githubusercontent.com/28895574/28359979-4e5b204e-6c74-11e7-8457-3deaf2746ba7.png)
 Mal als Beispiel

**Comment by CainDawson** [comment]
Dann sollte das aber soweit funktionieren das er die Möglichkeit vielleicht gleich so ist, das er den Titel des Einsatzes ab gleichen tut und als AAO hinterlegt. ;) das wäre natürlich wirklich mega praktisch. :)

Aber sollte auch angezeigt werden ob die AAO auch verfügbar ist mit Rot und Grün haken. :)

**Comment by KBOE2** [comment]
1. Man müsste die Fahrzeuge auslesen, was wie nah dran ist.
2. Zu großer Vortiel gegenüber Usern ohne diesem Script/Modul.
