### ISSUE TITLE
[Einsatzhelfer] Tiere auf der Fahrbahn

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#226]
Guck Guck,
ich böser junge hab mal wieder was für euch :+1: 

Tiere auf der Fahrbahn
Fehler: [missing "de.lssm.missionHelper.missions.301" translation]
Benötigte Fahrzeuge sind: 2 FuStW

Lg. Cain

**Comment by Suchty112** [comment]
Wir können auch nicht immer sofort alles drin haben :P . @Tsumiki-Chan muss heute oder morgen den master auf den proxy wieder machen. Es ist aber schon drin. Keine Sorge. :D Ich schließe es mal bei gelegenheit :P

**Comment by CainDawson** [comment]
Tscha, bin halt einer von der schnellen truppe. :)
Ich sags mal so, lieber melden als wenns vielleicht doch mal unter gehen sollte und manche sich im Forum dann wieder auslassen und so weiter. :)
Lg. Cain :P
