### ISSUE TITLE
[AAO Klick-Zähler kombiniert mit AAO-Suche] Klickzähler geht nicht

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#227]
Hey Ho,

Nutz ich den AAO Klick-Zähler mit der AAO-Suche zusammen ist das Problem wie folgt.

Angenommen "LKW Auffahrunfall" Ich gebe in der AAO-Suche "LKW" ein. Dann sehe ich die AAO als 0x LKW Auffahrunfall. Alles soweit korrekt. Klicke ich es aber an, bleibt der AAO Klick-Zähler bei 0x statt auf 1x zu springen.

Liebe Grüße
Cain

**Comment by Suchty112** [comment]
Da die AAO Suche von Sebastian übernommen worden ist, könnnen wir das denke ich heir schließen
