### ISSUE TITLE
Fehler des Einsatzhelfer beim Lagerhallenbrand

### ISSUE THREAD

**Issue by BobMeierLSS** [LSS-Manager/lss-manager-v3#229]
Ich habe den Einsatzhelfer aktiviert. Beim Lagerhallenbrand wird angezeigt, dass eine DLK benötigt wird. Allerdings werden 2 benötigt.

**Comment by Suchty112** [comment]
Ups da ist mir wirklich ein Fehler unterlaufen :/ upsala. Sollte nächste Woche gefixxt sein. oder vlt auch schon zwischenzeitlich :)  Dank dir
