### ISSUE TITLE
Color Picker für Fahrzeugfarben und AAO/Züge

### ISSUE THREAD

**Issue by JanH8** [LSS-Manager/lss-manager-v3#23]
## Fehlermeldung:
Color Picker für Fahrzeugfarben und AAO/Züge funktioniert nicht.
![image](https://cloud.githubusercontent.com/assets/16578440/26358847/23ad346c-3fd4-11e7-906c-251ee639259b.png)

## Aktivierte Module:
-LAYOUT 01
-EINSATZLISTE KOMPRIMIEREN
-CHAT POPUP
-FAHRZEUG TABLEAU
-FMS 5 IN DER KARTE
-RENAMEFZ
## Mögliche Lösung / Verbesserungsvorschlag:

- keine -

**Comment by lostdesign** [comment]
Nice :D Geht doch super, musst nur raten. (*wird natürlich gefixt*)

**Comment by Tsumiki-Chan** [comment]
Fehler liegt in der main.css. Ich schau mal.
