### ISSUE TITLE
Verbandskasse auf Hauptseite anzeigen lassen.

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#231]
>  Ich habe eine frage in der zeile wo man die einsätze ein/ausblenden kann kann man da ein script schreiben der die verbandskasse anzeigt ?

![verbandskasse](https://user-images.githubusercontent.com/1109899/28499079-ba2b3642-6fad-11e7-9bd4-77d880dda78d.png)

https://forum.leitstellenspiel.de/index.php/Thread/11880-Verbandskasse/?postID=191555#post191555

Inwiefern da man was machen könnte, müsste man schauen. Hab den vorschlag halt erstmal übernommen aus dem Forum

**Comment by jalibu** [comment]
Ohne Deep-Request ist das nicht umsetzbar.
