### ISSUE TITLE
VORSCHLAG: Chat Erweiterungen BBCodes, Links, Smilies

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#237]
Hey Ho,
gibt es eine Möglichkeit das mann den Verbandschat mit BBCodes, Links und Smilies füllen kann.

Das Wichtige wäre ja:
[B][/B] - Dick
[I][/I] - Kursiv
[U][/U] - Unterstrichen

Smilie :) :( ;) :D und sowas

Links sollten nicht als Text da stehen sondern als Link und aber mit target"_blank" So das diese immer im neuen Fenster sich öffnen. :)

Wäre so was möglich? Ich habe schon gelesen das im Forum solch ein wunsch schon mal geäußert wurde. :)

**Comment by jalibu** [comment]
@CainDawson: Klar geht das. Das Problem wäre dann eben nur, dass alle Nutzer ohne LSSM unformatierten Text sehen würden.
