### ISSUE TITLE
Fehler beim Einsatzhelfer

### ISSUE THREAD

**Issue by BobMeierLSS** [LSS-Manager/lss-manager-v3#245]
Ich hab gerade wieder beim Einsatzhelfer einen Fehler gefunden: Beim "Baum auf Gleisen" werden 2 FuStW angezeigt, es wird aber nur einer gebraucht...

**Comment by Suchty112** [comment]
https://github.com/LSS-Manager/lss-manager-v3/commit/8ea1eeef21154da6f5211696c0b25061f9569979
fixxed und online für die beta user
