### ISSUE TITLE
Dashboard klemmt bei User mit vielen Fahrzeugen

### ISSUE THREAD

**Issue by Zp9Zp9** [LSS-Manager/lss-manager-v3#246]
Dashboard hat seit neuestem scheinbar ein Problem mit vielen Fahrzeugen. Bei mir (2500 Fzg) und weiteren Spielern im VB (der kleinste davon rund 1300 Fzg) ist die Dashboard Anzeige unvollständig - und die Heatmap tut es auch nicht mehr. Die Screens dazu stehen im LSM-Thread im LSS-Forum.

**Comment by Suchty112** [comment]
Wir arbeiten aktuell dran und scheinen dem fix nah zu sein :)

**Comment by Suchty112** [comment]
So. Laut Rückmeldungen im ForumThread, scheint das Problem mit #247 behoben worden zu sein :) daher schließe ich den Issue mal :)
