### ISSUE TITLE
Fehler beim Bau / Setzen

### ISSUE THREAD

**Issue by VelonoX** [LSS-Manager/lss-manager-v3#25]
## Fehlermeldung:
Wenn ich neues Gebäude / neuen POI setzen / Event starten / Verbandsgroßeinsatz / etc. anklicke, dann erscheint links neben den Einsätzen das Interface für den jeweilig ausgewählten Button. Also zum Bestätigen des Bauens oder Erstellens.

## Aktivierte Module:
- Layout 1
- Einsatzliste komprimieren
- Clock
- FMS 5 in der Karte
- Einsätze freigeben
- Einsätze suchen
- Dashboard

## Mögliche Lösung / Verbesserungsvorschlag:
Menü im Feld bei dem Gebäude / Einsätzen etc. anzeigen

#### Beta Version: beta0.1

**Comment by lostdesign** [comment]
Fixed.
