### ISSUE TITLE
Anzeige der Abfahrtzeit im Einsatz

### ISSUE THREAD

**Issue by StefanPI314** [LSS-Manager/lss-manager-v3#259]
Hallo, zuerst einmal vielen Dank für das tolle Script.

Gab es den Vorschlag schon, die Anfahrtzeit in die Einsatzkachel zu übernehmen? Ich empfinde es als etwas nervig immer in den Einsatz zu gehen um einen Überblick über die Rest-AnrückZeit zu gewinnen.

Gruß
StefanPI314

**Comment by jalibu** [comment]
Das ist technisch mit unseren Mitteln leider nicht machbar.
