### ISSUE TITLE
Position der Einsatz"spalten"

### ISSUE THREAD

**Issue by maxk1312** [LSS-Manager/lss-manager-v3#26]
## Fehlermeldung:
Die Reihenfolge der Spalten für eigene Einsätze, KTP, VE, Eventeinsätze und Sicherheitswachen stimmt, wenn alle 5 ausgeklappt sind, nicht mit der Reihenfolge in der grünen Leiste darüber ein.
Hoffe mit dem Screenshot wird das deutlicher.
http://www.bilder-upload.eu/show.php?file=977521-1495553819.jpg

## Aktivierte Module:
- Layout 04
- Clock
- Einsatzliste komprimieren
- Einsätze freigeben

## Mögliche Lösung / Verbesserungsvorschlag:
Reihenfolge anpassen, d.h. 1. Spalte eigene Einsätze, 2. KTP, 3. VEs, 4. Event, 5. Sicherheitswachen, falls das möglich ist.

Wäre es ebenfalls möglich, dass wenn nur 1 Kategorie ausgeklappt ist, dass dann die ganze Breite ausgenutzt wird?

**Comment by lostdesign** [comment]
fixed
