### ISSUE TITLE
Meldedatum falsch

### ISSUE THREAD

**Issue by jplight** [LSS-Manager/lss-manager-v3#260]
Die "Meldedatum für Einsätze" kann nicht rechnen ^^

folgende Aneige:
08. Oktober, 18:01 Uhr - Vor **1d** 23h 22 min
Angezeigt am 09. Okt. um 17:23

Sind ja nur 23 Stunden und nicht fast zwei Tage

**Comment by Suchty112** [comment]
In der Beta/Dev version sind sie aktuell zumindest bei Missionchief auch falsch, da wird einfach eine stunde drauf gerechnet :/
![2017-11-10 3](https://user-images.githubusercontent.com/1109899/32658135-ec0be60e-c618-11e7-8b0c-c7e6f688924a.png)
![2017-11-10 2](https://user-images.githubusercontent.com/1109899/32658136-ec352ae6-c618-11e7-9439-716f6be18db0.png)

**Comment by Suchty112** [comment]
Sollte mit einen der letzten Updates gefixxt worden sein. Zumindest bis zur Zeitumstellung wieder 😂
