### ISSUE TITLE
Vorschlag: Anfahrtszeit in AAO (mouseover)

### ISSUE THREAD

**Issue by Roadblox** [LSS-Manager/lss-manager-v3#262]
Servus,
Ich wurde gebeten, meinen Vorschlag nochmal hier zu posten.

Die Idee:
Wenn man mit der Maus über eine AAO geht, wird die Zeit angezeigt, bis alle Fahrzeuge eingetroffen sein werden. Also quasi die Zeit des zuletzt eintreffenden Fahrzeugs.
Da einige Einsätze von mehreren verschiedenen Fahrzeugen abgearbeitet werden können, kann man sofort sehen, welches am schnellsten vor Ort ist.
Hier ein paar Beispiele: Alarmiere ich für eine kleine Ölspur ein Löschfahrzeug oder lieber einen GW-Öl? Ich habe einen weit entfernten ELW 1 zur Verfügung, jedoch ist ein ELW 2 direkt um die Ecke. 
Ist der GRTW schneller da, als 10 RTW?
Diese Fahrzeuge jedes mal über die Suche zu filtern und zu vergleichen würde 1. Zeit kosten und 2. könnte ich mir so die AAO auch gleich sparen.
Wenn man den Fahrzeug Radius hoch eingestellt hat, könnte man sehen, dass ein Fahrzeug z.B. 45min zum Anfahren bräuchte und man deshalb lieber wartet, bis ein naher Einsatz fertig ist und ein entsprechendes Fahrzeug frei wird.

Seit ich diese Idee habe, merke ich immer öfter, wie nützlich ein solches Feature wäre. Je mehr Fahrzeuge man besitzt, desto unübersichtlicher wird das Management und der Versuch, immer die schnellsten und nützlichsten Fahrzeuge zu einem Einsatz zu schicken. 

Freue mich auf eure Reaktionen :)

**Comment by jalibu** [comment]
Ich habe das bereits prototypisch umgesetzt. Da ich selbst keine AAOs nutze, müsste das aber intensiv getestet werden.

Ich hab es erst mal als reines Greasemonkey Skript.
Wer will?

**Comment by Roadblox** [comment]
Perfekt, immer her damit 👍

**Comment by jalibu** [comment]
Funktioniert bisher nur, wenn die Anfahrtszeit unter 1h ist UND alle erforderlichen Fahrzeuge in S1 oder S2 innerhalb der in Zeit angezeigten Reichweite sind.

Bitte mal testen und Feedback geben.

`// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.leitstellenspiel.de/missions/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    const LOGLEVEL = 1;
    var timeRegex = /([0-9]{2}) Min. ([0-9]{2}) Sek./i;

    $('.aao').on('mouseover', function(){
        const aaoObject = this;
        var maximumSeconds = '';
        var aaoVehicles = getAaoVehicles(aaoObject);

        if(LOGLEVEL > 0){
            console.log('AAO contains the following vehicles:');
            console.log(aaoVehicles);
        }

        $('.vehicle_checkbox').each(function(){
            if(LOGLEVEL > 2){
                console.log('Next vehicle..');
            }
            var vehicle = this;
            for(var key in aaoVehicles) {
                if(LOGLEVEL > 2){
                    console.log('Is this a ' + key + '?');
                }
                if(vehicle.attributes[key].value > 0){
                    aaoVehicles[key]--;
                    if(LOGLEVEL > 1){
                        console.log('Found one! Remaining vehicles of ' + key + ': ' + aaoVehicles[key]);
                    }

                    var totalSeconds = getDurationInSeconds(vehicle);
                    if(totalSeconds > maximumSeconds){
                        if(LOGLEVEL > 0){
                            console.log('The current vehicle takes ' + totalSeconds + '. This is a new maximum');
                        }
                        maximumSeconds = totalSeconds;
                    } else {
                        if(LOGLEVEL > 1){
                            console.log('The current vehicle takes ' + totalSeconds + '. This is fewer than the current maximum of ' + maximumSeconds);
                        }
                    }
                    if(aaoVehicles[key] === 0) {
                        if(LOGLEVEL > 1){
                            console.log('Found all ' + vehicle.attributes[key].name);
                        }
                        delete aaoVehicles[key];
                        break;
                    }
                }
            }
            if(Object.keys(aaoVehicles).length === 0){
                if(LOGLEVEL > 0){
                    console.log('Found all required vehicles. Good thing :-)');
                }
                return false;
            }
        });
        if(Object.keys(aaoVehicles).length === 0){
            if(LOGLEVEL > 0){
                prettyPrintResult(aaoObject, maximumSeconds);
            }
        } else {
            if(LOGLEVEL > 0){
                const error = 'Could not find all vehicles! The following are missing: ' + aaoVehicles;
                prettyPrintResult(aaoObject, maximumSeconds, error);
            }
        }

    });

    const prettyPrintResult = (aaoObject, secondsString, error) =>{
        if(error){
            $(aaoObject).attr('title', error + ' The maximum was ' + secondsString + ' sec.');
        } else {
            $(aaoObject).attr('title', 'Takes ' + formatSeconds(secondsString));
        }
    };

    const formatSeconds = (totalSeconds) => {
        var days = Math.floor(totalSeconds / 86400);
        totalSeconds -= days * 86400;

        var hours = Math.floor(totalSeconds / 3600) % 24;
        totalSeconds -= hours * 3600;

        var minutes = Math.floor(totalSeconds / 60) % 60;
        totalSeconds -= minutes * 60;

        var seconds = totalSeconds % 60;  // in theory the modulus is not required

        return minutes + ' min. ' + seconds + ' sec.';
    };

    const getDurationInSeconds = (vehicleObject) =>{
        var durationString = $(vehicleObject).parent().parent().find('td[class*="alarm_distance_"]').text().trim();
        var matches = durationString.match(timeRegex);
        var minutes = matches[1] * 60;
        var seconds = matches[2];
        var total = parseInt(minutes) + parseInt(seconds);
        return total;
    };

    const getAaoVehicles = (aaoObject) => {
        var vehicles = {};
        $.each(aaoObject.attributes, function (index, attribute) {
            if(!isNaN(attribute.value) && attribute.value >0){
                vehicles[attribute.name] = parseInt(attribute.value);
            }
        } );

        return vehicles;
    };
})();`

**Comment by Roadblox** [comment]
Kurz getestet, Prima!

Genau das, was ich mir vorgestellt hatte. Da meine Anfahrtszeit, bzw. mein Radius nie über eine Stunde hinaus geht, beeinträchtigt mich das nicht.

Ich werde LSS Forum am besten auf diesen Beitrag verweisen.

**Comment by lostdesign** [comment]
@Roadblox lass uns das ganze erst testen, dann würde ich es in den LSSM aufnehmen, so haben alle etwas davon. :)

**Comment by jalibu** [comment]
Hab nochmal ein kleines Update gemacht.
Bitte hiermit testen und Feedback geben.
[AAODuration.user.txt](https://github.com/LSS-Manager/lss-manager-v3/files/1374513/AAODuration.user.txt)

Die Rückmeldungen können wir dann bei der Integration in LSSM berücksichtigen.

**Comment by Roadblox** [comment]
Alles klar, ich werde es dann heute Abend ausgiebiger testen. Schon mal vielen Dank :)

**Comment by jplight** [comment]
Erster Test lief bei mir erfolgreich. Update folgt, bei Gelegenheit.
Einziges Manko: Die Ladezeit scheint doch länger zu dauern.

**Comment by Roadblox** [comment]
Bei mir bisher auch erfolgreich. Das mit der Ladezeit merkt man schon ein wenig, aber bis das Script bei jedem mouseover durchgelaufen ist, ist das verständlich.

Ich habe die Fehlermeldung rausgenommen, falls eine AAO überhaupt nicht verfügbar ist. Diese war mir zu lang und ich sehe ja direkt, das sie nicht verfügbar ist. Falls nur teilweise Fahrzeuge fehlen, kann es vielleicht noch angepasst werden, dass die Fahrzeugbezeichnungen richtig angezeigt werden.

**Comment by jalibu** [comment]
@Roadblox @jplight ,
danke für das Feedback. Die lange "Ladezeit" kommt übrigens nicht durch langes Laden oder Berechnen zustande, sondern "title"-Tooltips werden vom Browser bewusst verzögert dargestellt.

Ich werde stattdessen einfach ein eigenen Tooltip verwenden. Dann sollte die Darstellung stets in <1s erscheinen.

Im Laufe des Tages werde ich nochmal ein Update bereitstellen.

**Comment by jalibu** [comment]
Bitte nochmal hiermit testen:
[AAODuration2.user.txt](https://github.com/LSS-Manager/lss-manager-v3/files/1378683/AAODuration2.user.txt)

**Comment by Roadblox** [comment]
Ein Traum, jetzt erscheint es sofort :) Einzige Verbesserung, die mir jetzt noch auffällt: Der neue Tooltip erscheint direkt bündig unter der Box der AAO, dadurch ist der Cursor fast immer drüber und verhindert die Sicht auf die Zeit. Kannst du diesen beispielsweise eine Cursorbreite weiter nach unten setzen?

**Comment by jalibu** [comment]
Die Umsetzung für LSSM wurde abgeschlossen. Der Code ist im aktuellen DEV Branch und wird mit der nächsten Version ausgeliefert.
Die Position des Hinweis Felds wurde dabei nochmals optimiert.
