### ISSUE TITLE
[Bug?] Plugins nach Browser Restart erneut auswählen

### ISSUE THREAD

**Issue by simsus** [LSS-Manager/lss-manager-v3#265]
Moin

Ist die Speicherung der aktivierten Plugins abhängig von irgendwelchen Browser Einstellungen?
Sobald ich FF 56.0 schliesse und erneut starte, muss ich im LSSMv3 die benötigten Plugins erneut aktivieren.

LG

simsus

**Comment by Tsumiki-Chan** [comment]
Die Speicherung der aktivierten Plugins erfolgt im LocalStorage deines Browsers. Wenn dieser deaktiviert wurde bzw. auf Temporär geschaltet wurde, kann es zu diesem verhalten kommen

**Comment by simsus** [comment]
Danke für die Rückmeldung. Hab es im Debugger gesehen :-D
Könnte man hier sonst eine Export- / Import-Funktion irgendwann implementieren?
#199 #216

**Comment by Suchty112** [comment]
ja ist ja geplant und zumindest seit längerer Zeit für die BetaSpieler verfügbar wie du ja an #216 siehst :) Es fehlen allgemein noch ein paar kosmetische änderungen am script. Aber aktuell sind sogut wie alle ein wenig überall eingespannt, sodass sich das noch ein wenig nach hinten verschieben kann :)
