### ISSUE TITLE
Vorschlag: allianceMissionlistShare-Plugin um Meldungstext ergänzen

### ISSUE THREAD

**Issue by CSA-Verweigerer** [LSS-Manager/lss-manager-v3#274]
Bei mir ist es Standard, bei meinen Freigaben noch die Abarbeitungszeit der Einsätze mit Hilfe eines Standardisierten Texts mit anzugeben.

Hierbei habe ich vier verschiedene Texte:
Keine ELW2 senden, Abarbeitung ab 17:00 Uhr
Keine ELW2 senden, Abarbeitung ab 21:30 Uhr
Keine Fükw senden, Abarbeitung ab 17:00 Uhr
Keine Fükw senden, Abarbeitung ab 21:30 Uhr

Kann das Plugin so erweitert werden, dass ein vorab eingegebener Text in den Rückmeldungen gepostet wird?
Kür wäre, noch entscheiden zu können, ob das ganze noch in den Verbandschat soll oder nicht

**Comment by KBOE2** [comment]
Hab mal den Titel angepassst, da falsches Plugin angegeben ;)
Müsste man mit Seb abklären, wie weit erlaubt.

**Comment by KBOE2** [comment]
Ich verweise btw mal auf #70 und close hier 🙃
