### ISSUE TITLE
Maßgeschneiderte Tabs

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#277]
Sollte man mehr als 250 Autos haben und das Addon anhaben, werden nur die ersten 250 angezeigt. Sollte man diese nachladen, werden diese nicht mit in die maßgeschneiderten Tabs getan.

> Ich nutze die "MASSGESCHNEIDERTE TABS" Erweiterung. Gefällt mir so sehr gut!
Wenn ich jetzt Fahrzeuge Nachlade, werden die nicht in die neuen Tabs sortiert, sondern verbleiben in den alten Tabs.
Sprich bisher funktioniert das AddOn nur für die Fahrzeuge die angezeigt werden bevor ich die Fahrzeuge Nachlade.

**Comment by jalibu** [comment]
Eigentlich sollte das tun.
Wenn die zusätzlichen FZ nachgeladen sind, sollte der Mechanismus zum Einsortieren nochmal laufen. Ich hatte das mehrmals getestet.

Ich vermute hier, dass es zu einer Racing Condition kommt, weil ich das Ajax-Done Event nicht 100% perfekt abgefangen bekomme. Dazu musste ich relativ unsaubere Workarounds nutzen, die aber in meinen Tests immer funktionierten.

Vielleicht hat ja jemand ne bessere Idee und kann das dann fixen.

**Comment by Suchty112** [comment]
ich kann nur das weitergeben was im forum steht ^^ Werde aber hierrauf mal verlinken

**Comment by Suchty112** [comment]
Klappt eigentlich wieder. zumindest bei mir, daher close
