### ISSUE TITLE
Button "absenden" hat unleserliche Farbe

### ISSUE THREAD

**Issue by maxk1312** [LSS-Manager/lss-manager-v3#28]
## Fehlermeldung:
Der Button "Absenden" bei den Rückmeldungen wird im normales Design hellgrau über"malt".

## Aktivierte Module:
- Version 04
- Clock
- Einsatzliste komprimieren
- Einsätze freigeben

## Mögliche Lösung / Verbesserungsvorschlag:
Farbe ändern?

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Duplikat #12
