### ISSUE TITLE
Fehler von AAO Anfahrtzeit

### ISSUE THREAD

**Issue by FendoRichter** [LSS-Manager/lss-manager-v3#280]
Windows 10 - Chrome

Uncaught TypeError: Cannot read property 'value' of undefined
    at HTMLInputElement.<anonymous> (lss-aao-time.user.js?uid=leitstellenspiel404358:4)
    at Function.each (application-1d3ddb9c129239d3bbfae7b22626e003.js:16)
    at init.each (application-1d3ddb9c129239d3bbfae7b22626e003.js:16)
    at handleMouseOver (lss-aao-time.user.js?uid=leitstellenspiel404358:4)
    at HTMLAnchorElement.<anonymous> (lss-aao-time.user.js?uid=leitstellenspiel404358:6)
    at HTMLAnchorElement.dispatch (application-1d3ddb9c129239d3bbfae7b22626e003.js:27)
    at HTMLAnchorElement._.handle (application-1d3ddb9c129239d3bbfae7b22626e003.js:27)

Bei manchen AAOs wird die Zeit angezeigt. Bei manchen leider nicht und dieser Fehler tritt auf.

**Comment by Suchty112** [comment]
Ok danke. Bei denen wo es nicht angezeigt wird, wird nicht zufällig die Kilometer anzeige angezeigt oder?

**Comment by FendoRichter** [comment]
Nein. Es wird absolut gar nichts angezeigt.

**Comment by Suchty112** [comment]
ich meine nicht im tooltip dann sondern bei dem jeweiligen auto unten in der fahrzeugliste, ob da nicht die km anzeige steht wenn du das auto per aao alamieren willst und so der fehler kommt

**Comment by FendoRichter** [comment]
Ach so. Gerade nochmal nachgeschaut. Alle Fahrzeuge sind mit Zeitangabe in der Liste.

**Comment by Suchty112** [comment]
Ok danke, wir werden da mal nach schauen.

**Comment by jalibu** [comment]
Der Fehler tritt auf, wenn NAW oder RTW+NEF/RTH Optionen in der AAO hinterlegt sind.

Mit Einführung der NAWs wurden hier neue spezielle Attribute eingefügt (z.B. das Attribut naw_or_rtw_and_nef).

Die Verarbeitung dieser speziellen Attribute müsste im Script entsprechend implementiert werden.

Kleiner Hinweis zum schnelleren Finden:
Der Fehler fliegt in der Zeile 130.
` for (let key in aaoVehicleSearchList) {
if (vehicle.attributes[key].value > 0) { 
`

Das vehicle.attributes Array sieht dann etwa so aus:
`{0: ab_atemschutz_only, 1: ab_oel_only, 2: ab_ruest, 3: ab_ruest_rw, 4: abl2wasser_only, 5: arff, 6: boot, 7: building_id, 8: class, 9: dekon_p, 10: dlk, 11: elw2, 12: elw3, 13: elw, 14: fire, 15: fly_car, 16: fms, 17: fukw, 18: fustw, 19: fwk, 20: gefkw, 21: gkw, 22: grtw0, 23: grtw1, 24: grtw, 25: grukw, 26: gw_atemschutz_only, 27: gw_oel_only, 28: gw_san, 29: gw_taucher, 30: gw_wasserrettung, 31: gwa, 32: gwgefahrgut, 33: gwhoehenrettung, 34: gwl2wasser, 35: gwl2wasser_only, 36: gwmesstechnik, 37: gwoel, 38: hlf_only, 39: id, 40: ignore_aao, 41: k9, 42: kdow_lna, 43: kdow_orgl, 44: ktw, 45: ktw_b, 46: lebefkw, 47: lf_only, 48: mtw, 49: mzb, 50: name, 51: naw, 52: nef, 53: nef_only, 54: only_ab_dekon_p, 55: only_dekon_p, 56: ovd_p, 57: polizeihubschrauber, 58: possible_tractive, 59: rth_only, 60: rtw, 61: rw, 62: rw_only, 63: seg_elw, 64: swat, 65: thw_anh_mzab, 66: thw_anh_mzb, 67: thw_anh_schlb, 68: thw_brmg_r, 69: thw_dle, 70: thw_lkw, 71: thw_lkw_7_lkr_19_tm, 72: thw_mlw5, 73: thw_mtw, 74: thw_mzkw, 75: thw_tauchkraftwagen, 76: tlf_only, 77: tractive_random, 78: tractive_vehicle_id, 79: trailer, 80: trailer_vehicle_id, 81: type, 82: value, 83: vehicle_type_id, 84: wasserwerfer, length: 85}`

Key wäre z.B.
`naw_or_rtw_and_nef`

Dies ist nicht im Array enthalten und es kommt zum Fehler.

**Comment by FendoRichter** [comment]
Kann man das temporär selbst beheben oder muss man auf ein Update warten?

**Comment by Suchty112** [comment]
ich schau da gleich mal nach :) Also heißt wir vom Team müssen das fixen.

**Comment by lostdesign** [comment]
@FendoRichter man soll und kann selbst nichts ändern.

**Comment by FendoRichter** [comment]
Kommt hier noch ein Fix?
Wäre echt schön wenn die tausenden Fehlermeldungen die dieser Fehler verursacht wegfallen würden. Ist ja auch für die Performance nicht unbedingt schön so viele Fehler zu produzieren.

**Comment by Suchty112** [comment]
Aktuell bin ich leider sogut wie der einzigste der etwas für den LSSM macht, die anderen sind durch Beruf und Schule sehr knapp angebunden. 
Da ich aber gesehen habe, das du ja auch schon ein paar Scripts schreibst, ob für dich selbst oder für andere, könntest du dich doch daran vlt. versuchen. 
Ist jetzt nur ein kleiner Vorschlag von meiner seite aus :) .

**Comment by jalibu** [comment]
Der Fehler kommt immer dann, wenn eine Entweder/Oder Option in der jeweiligen AAO enthalten ist (z.B. NAW oder NEF+RTW // HLF oder LF+RW).

Damit kommt das Script nicht klar und dafür gibt es auf die Schnelle auch keinen Quickfix.
Hier müsste sich jemand ran setzen und wohl etwas Logik implementieren (im besten Fall kann man sich die Logik vom Base Game kopieren, denn da muss der gleiche Input ja auch irgendwie verarbeitet werden).

**Comment by Suchty112** [comment]
Solllte sich hiermit erledigt haben. DAnke Sebastian :)
https://blog.leitstellenspiel.de/aao-maximale-fahrzeit/
