### ISSUE TITLE
AAO Anfahrtzeit nicht lesbar im dunklen Layout

### ISSUE THREAD

**Issue by FendoRichter** [LSS-Manager/lss-manager-v3#281]
Der Fehler wurde ja schon gemeldet dass die Spieler mit dunklen Layout es nicht lesen können.
Ich hätte dafür eine Simple Lösung die ich bei mir eingebaut habe.

Einfach den Hintergrund des Fensters von Weiß auf #5CB85C (Das Grün von Status 2) ändern.
Damit ist es für beide Layouts einwandfrei zu lesen und es sieht nicht deplatziert aus weil die Farbe
bereits im Spiel vorkommt.

**Comment by Suchty112** [comment]
ist online... daher close
