### ISSUE TITLE
AAO Anrückzeit auch für Züge?

### ISSUE THREAD

**Issue by FendoRichter** [LSS-Manager/lss-manager-v3#282]
Ich finde die Erweiterung echt Top.
Perfekt wäre es wenn die Zeit auch bei Zügen angezeigt wird.

Ist das möglich oder technisch leider nicht umsetzbar?

**Comment by KokosnussDEV** [comment]
Umsetzbar
Frage wie? Was ist denn gewollt? Mittelwert der Anfahrtszeit?

**Comment by Dexus** [comment]
Die Max Zeit wäre glaube ich das ideal.

**Comment by Suchty112** [comment]
Solllte sich hiermit erledigt haben. DAnke Sebastian :)
https://blog.leitstellenspiel.de/aao-maximale-fahrzeit/
