### ISSUE TITLE
Vorschlag: Alarmieren und Teilen Button

### ISSUE THREAD

**Issue by FendoRichter** [LSS-Manager/lss-manager-v3#284]
Hallo liebes LSSM Team.

wäre es möglich in die Alarmierungsmaske einen zusätzlichen Button einzubauen mit welchem man die markierten Fahrzeuge alarmieren, gleichzeitig den Einsatz im Verband freigeben kann und auf den nächsten Einsatz weitergeleitet wird?
Ich glaube das wäre durchaus ein sehr geiles Feature für Verbandsspieler.

**Comment by Suchty112** [comment]
ist glaub ich jetzt im basisspiel drin. Daher close
