### ISSUE TITLE
Fehlende Übersetzung

### ISSUE THREAD

**Issue by dhavenith** [LSS-Manager/lss-manager-v3#294]
Einsatz: Handverletzung durch Feuerwerkskörper 

Benötigte Fahrzeuge
[missing "de.lssm.missionHelper.missions.326" translation]

**Comment by Suchty112** [comment]
Ja wir haben aktuell 1-2 Probleme wieder, das es nicht an die Spieler ausgegeben werden kann. Ich habe grad nochmal Aisaka bescheid gegeben, da es sein Server ist

**Comment by Suchty112** [comment]
ist online :) have fun
