### ISSUE TITLE
Restzeit geplante Einsätze

### ISSUE THREAD

**Issue by MissTemple** [LSS-Manager/lss-manager-v3#297]
Ich fände es praktisch, wenn man bei den geplanten Einsätzen auf der Karte die Zeit bis zum Start sehen würde. Damit man möglichst zeitnah seine Einheiten schicken kann und diese nicht unnötig blockiert werden, weil mans nicht verpassen möchte.

Sorry, falls es den Vorschlag schon gibt/gab und ich ihn übersehen hab.

LG

**Comment by Tsumiki-Chan** [comment]
Bereits im Leitstellenspiel
