### ISSUE TITLE
Rücksetzung der Plugins 

### ISSUE THREAD

**Issue by post24** [LSS-Manager/lss-manager-v3#298]
Zu meinem Problem jedesmal wenn ich den Browser schließe (Chrome :Version 63.0.3239.108 (Offizieller Build) (64-Bit)) und wieder öffne bzw mich neu einloggen muss dann hab ich des Problem dass alle Plugins die ich aktiviert hatte weg sind und ich sie wieder neu aktiveren muss. Inzwischen auch bei Firefox (auch aktuell). Des nervt ziemlich weil ich auch alle Einstellungen etc. neu machen muss. Java ist auch aktuell. Auf dem Rechner läuft WIN10 auch im aktuellsten offiziellen Build.

**Comment by Suchty112** [comment]
Das liegt daran, das beim schließen der Browser bei dir der Local Storage geleert wird. Guck mal in die Einstellungen rein bei beiden Browsern. Wie du es deaktivierst, kannst du leicht googeln

**Comment by post24** [comment]
Hat funktioniert DANKE :D

**Comment by Suchty112** [comment]
Wunderbar. Dann schließ ich hier :)
