### ISSUE TITLE
Briefumschlag im Chat erscheint in RL-Größe

### ISSUE THREAD

**Issue by Topix1** [LSS-Manager/lss-manager-v3#299]
Heute habe ich festgestellt, dass an meinen beiden PC ( 1 x WIN 7 / 32 u. 1 x WIN 7 / 64 ) der Briefumschlag im Chatfenster vor jedem Text gigantisch groß ist. Beides unter Chrome. Am Lappi (WIN 10) läuft das Script auf Chrome ohne Probleme. Ich habe das Script schon deinstalliert und neu installiert, aber der Fehler bleibt. 

Ich versuche mal ein screenshot hochzuladen, hoffe, das klappt. 

![image](https://user-images.githubusercontent.com/19910622/34650680-4e8b7fc2-f3c5-11e7-8376-0e5a2777022e.png)

**Comment by Suchty112** [comment]
heißt du ingame nur Topix? Wenn ja, hab ich grad gesehen, das du das Redesign1 an hast, deaktiviere dies vor erst, dann ist der umschlag auch wieder normal. Es ist schon ein Pullrequest (#295 ) gemacht worden von mir, was von den anderen noch reviewed werden muss, dann sollte es auch wieder funzen

**Comment by Topix1** [comment]
Ja, ingame nur Topix ... hier konnte ich den Nick nicht auswählen, weil vergeben

**Comment by Topix1** [comment]
Redesign 1 deaktiviert - danke, läuft jetzt wieder normal

**Comment by Suchty112** [comment]
du solltest es jetzt wieder nutzen können @Topix1 :) wir haben heute das update auf unsere server eingespielt :)

**Comment by Topix1** [comment]
...super, danke!
