### ISSUE TITLE
Nicht alle Wachen/Einsätze sichtbar nach Reload/Start

### ISSUE THREAD

**Issue by OiledAmoeba** [LSS-Manager/lss-manager-v3#3]
## Fehlermeldung:
Wenn ich die Seite neu lade (F5, STRG+F5 oder neu aufrufen), dann ist die Karte auf die ursprünglich geladenen Einsätze beschränkt. Verschieben der Karte bringt auch nur die von LSS vorgesehen Daten.
Die Karte muss mit dem Reload-Button der Beta neu geladen werden.

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Ich denke du gehst von dem hier aus:
<img width="1241" alt="bildschirmfoto 2017-05-23 um 07 59 07" src="https://cloud.githubusercontent.com/assets/5164617/26340261/b72da416-3f8d-11e7-8cb3-966437625dce.png">

Das sollte eigentlich nur in der Layout-01 so sein, kann aber geändert werden. Könntest du das bestätigen?

**Comment by OiledAmoeba** [comment]
Mir kommt es so vor, als wäre das bei mir daheim anders, aber mit FF 52.0.2 (32-Bit) in der Firma ist es genau das, was Du schreibst.

Bin der festen Überzeugung, dass der Chrome zwar die Karte komplett zeichnet, dann aber ein "virtueller Rahmen" rechts und unten die dynamischen Inhalte der Karte (Fahrzeuge, Wachen, Wegstrecken) ausblendet.

## Aktivierte Module:
- Layout 01
- Einsatzliste komprimieren
- FMS 5 in der Karte
- Clock
- Einsätze freigeben
- Keyboard Alarmierung

**Comment by Tsumiki-Chan** [comment]
Versuche mal bitte oben links das "neu laden" icon in der Map an zu klicken.

Damit verschwindet der Bug auf jeden fall im FF. Im Chrome ist das noch nicht getestet.

In https://github.com/LSS-Manager/lss-manager-v3/issues/36#issuecomment-303640446 haben wir eingebunden, dass beim Laden von Layout01 dieser map refresh automatisch passiert.

**Comment by OiledAmoeba** [comment]
@Tsumiki-Chan Das habe ich schon probiert und auch in Chrome erfolgreich getestet, siehe Startposting. (Und nebenbei frage ich mich gerade, wie Issue **3** eine Dublette von einem späteren Issue sein kann...)

**Comment by Tsumiki-Chan** [comment]
Ich habe nicht auf die Issue ID geachtet. Hatte nur gesehen "einsätze nicht da".

Ich werde das aber schließen, da dies bald gefixed sein sollte.
