### ISSUE TITLE
Layout 1 - Elementen Menü links bei hover

### ISSUE THREAD

**Issue by VelonoX** [LSS-Manager/lss-manager-v3#30]
## Beschreibung:
Folgendes Szenario: Im Layout 1 kann man ja zwischen den Fenstern von Einsätze/Gebäude etc. wechseln.
Wenn man die dementsprechenden Flächen für die anderen Menüs hovert ist das icon in der mitte schwarz.
Hovert man nun auch auf das Icon in der Mitte wird dieses erst weiß angezeigt.

## Mögliche Lösung:
Icon in der Fläche auch weiß färben wenn man auch nur schon die Fläche drum herum hovert.

**Comment by MrWeezle** [comment]
kann ich bestätigen

**Comment by FlorianRhausen** [comment]
Bei mir sieht das im Layout 1 anders aus. Wenn ich auf die Auswahl gehe, wird der Hintergrund rot - das Symbol in der Mitte ist dann erstmal grau, erst wenn der Mauszeiger auf dem Symbol fährt, wechselt es die Farbe auf weiss.

Browser: Firefox 53.0.2.32 bit

**Comment by lostdesign** [comment]
fixed.
