### ISSUE TITLE
Vorschlag: Zielort Filter max. Abgabe

### ISSUE THREAD

**Issue by FendoRichter** [LSS-Manager/lss-manager-v3#300]
Es wäre super wenn man dem Zielortfilter noch sagen könnte wie viel Abgabe man maximal leisten möchte und alle KH mit höherer Abgabe ausblendet.
Dann wäre die Erweiterung perfekt.

**Comment by fidelcastro54** [comment]
Sehe ich genauso, dann wäre es perfekt

**Comment by KBOE2** [comment]
0a3f74f ist implementiert.
