### ISSUE TITLE
Dashboard defekt

### ISSUE THREAD

**Issue by miba112** [LSS-Manager/lss-manager-v3#303]
Seit paar Tagen geht bei mir das Dashboard nicht mehr richtig (Win10, FF 57.0.4). Wollte das jetzt heute mal genau wissen und habe den LSSM in zweitem Browser (Edge) installiert. Gleiches Ergebnis.
Es wird nur noch die Übersichtsgrafik angezeigt. Buttons für die Wachenplanung und Fahrzeuge fehlen.
Da ich das recht häufig nutze (knapp 200 Wachen) vermisse ich das sehr.
Könnt ihr bitte mal danach schauen ?
![dashboard-bug ff57 0 4](https://user-images.githubusercontent.com/31823245/34894065-34d25744-f7e0-11e7-8040-685773c3c767.JPG)

**Comment by Suchty112** [comment]
Du hast nicht schon zufällig Flugfeld löschfahrzeuge oder Rettungstreppen geholt? :) Dann weiß ich in etwa woran es liegen könnte, muss dazu aber unseren Servertechniker nochmals anhauen :P

**Comment by miba112** [comment]
Natürlich habe ich FLF und Rettungstreppen schon geholt. Die Coins vom Adventskalender wollten ja sinnvoll investiert werden :-)
OK - dann hast du jetzt 'nen Ansatz.

**Comment by Suchty112** [comment]
Wunderbar, den gleichen Fehler hatte ich auch gehabt lokal :D . Und sry für die PN ingame xD

**Comment by miba112** [comment]
Alles gut

**Comment by miba112** [comment]
Betroffen sehr wahrscheinlich auch LS-Heatmap. Die geht auch nicht.

**Comment by Suchty112** [comment]
ja die holt sich auch die daten aus der einen datei wo die autos drinnen stehen. 
Und wenn du diese aber schon hast (autos), aber die datei mit den neuen autos noch nicht für euch freigegeben ist, kommen ebend die fehler, das euch nix angezeigt wird. 

Aber leider machen uns auch manchmal unsere eigenen server ein strich durch die Rechnung, sodass wir es an euch aktuell leider nicht ausliefern können.

**Comment by miba112** [comment]
Fixed. Geht alles wieder.
