### ISSUE TITLE
Anzeigefehler beim erstellen einer GSL/Fehlleitung GSL Abbrechen Button

### ISSUE THREAD

**Issue by GregorPaul** [LSS-Manager/lss-manager-v3#31]
## Fehlermeldung:
Es gibt ein Anzeigefehler beim erstellen der GSL.
Fehlleitung des Abbrechen Buttons bei einer GSL Erstellung. Man landet bei www.leistellenspiel.de/buildings

![bildschirmfoto 2017-05-23 um 22 00 08](https://cloud.githubusercontent.com/assets/28886972/26374063/4802d1de-4004-11e7-91db-e37ed21c715d.png)
![bildschirmfoto 2017-05-23 um 22 00 46](https://cloud.githubusercontent.com/assets/28886972/26374064/48193618-4004-11e7-9a0b-876268e100d1.png)

## Aktivierte Module:
- FMS 5 in Karte
- Uhr in Karte

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: 0.1

**Comment by DLRG-Dominik** [comment]
Dieser Fehler ist uns bereits bekannt. Wird auch gefixt. Danke für die Meldung :)

**Comment by lostdesign** [comment]
Fixed.
