### ISSUE TITLE
rote Farbunterlegung im Chat erscheint nicht

### ISSUE THREAD

**Issue by Topix1** [LSS-Manager/lss-manager-v3#312]
Moin Moin,

mir ist gerade aufgefallen, dass persönliche Anschreiben im Chat (per @Nick > Text) nicht rot unterlegt werden. Nach einem neuen Laden der Seite erscheint besagter Text kurz in rot, jedoch verschwindet der rote Hintergrund nach dem Laden des Scriptes wieder.

Ingame-Nick >>  Topix (der war hier schon vergeben)

**Comment by Suchty112** [comment]
Welche Module hast du aktiviert? Das wäre auch immer gut zu wissen.
Dann könnten wir das evtl. eingrenzen

**Comment by Topix1** [comment]
![image](https://user-images.githubusercontent.com/19910622/35200217-58447abe-ff0a-11e7-9c2d-14d14aeaeba0.png)


Ich hoffe, das mit dem Screenshot klappt

**Comment by Suchty112** [comment]
Okay. Ich habe den Übeltäter erwischt... Es ist mal wieder das verflixte Redesign01 :D . Wenn man die Layouts alleine anhat, ist alles kein Problem. Aber sollte man das Redesign anhaben ob mit oder ohne Layouts, zeigt er es nicht mehr an

**Comment by Topix1** [comment]
Danke!

**Comment by Suchty112** [comment]
Sollte jetzt online sein. Have fun :)
