### ISSUE TITLE
Kopfleiste - Einsatzliste (Vorschlag)

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#32]
## Beschreibung:
Die Kopfleiste bei der Einsatzliste ist nicht fixiert, wenn man durch die Einsatzliste scrollt, wandert diese nach oben.
![grafik](https://cloud.githubusercontent.com/assets/28895574/26388648/e5134462-4055-11e7-89d4-c1f458777e80.png)
![grafik](https://cloud.githubusercontent.com/assets/28895574/26388656/f016f746-4055-11e7-9371-884ea18d03df.png)

## Mögliche Lösung:
Eventuell die Leiste fixieren, das die Einsatzliste nur darunter scrollt.

**Comment by Tsumiki-Chan** [comment]
War ein LSS-Problem. Mittlerweile fixed
