### ISSUE TITLE
"Wachenplanung auf der Karte" kann nicht aktiviert werden

### ISSUE THREAD

**Issue by OneOfTwelve** [LSS-Manager/lss-manager-v3#325]
Spielername: OoT
Browser: Google Chrome
Version: Version 65.0.3325.181 (Offizieller Build) (64-Bit)
Beta Version: Nein
LSS Manager v3

Aktivierte Module:
-AAO Anrückzeit
-Dashboard
-FMS 5 in der Karte
-NEF NAchforderung per FMS
-Meldedatum für Einsätze
(-LS-Heatmap)

Wenn ich versuche das Plugin "Wachenplanung auf der Karte" versuche zu aktivieren wirft dies die Fehlermeldung (Popup):

"Wachenplanung auf der Karte" kann nicht aktiviert werden, da es mit folgenden Modul(en) inkompatibel ist:

[missing "de.lssm.apps.1.name" translation]

Ist das Plugin "LS-Heatmap" noch aktiviert taucht zusätzlich folgende Zeile mit auf:

[missing "de.lssm.apps.2.name" translation]

**Comment by KBOE2** [comment]
Kann das ganze so bestätigen: FMS 5 in Karte + Wachenplanung wirft [missing "de.lssm.apps.1.name" translation] aus.
LS-Heatmap + Wachenplanung wirft [missing "de.lssm.apps.2.name" translation] aus.

**Comment by Suchty112** [comment]
Bitte einmal wie hier #1  den Issue ändern.

**Comment by Suchty112** [comment]
Ist schon längst gefixxt. Damit close
