### ISSUE TITLE
Zuweisung von KH per Hotkey 1 - 5

### ISSUE THREAD

**Issue by Schneesperling** [LSS-Manager/lss-manager-v3#327]
Hallo,

bei mir funktioniert weder mit Chrome noch mit Opera die Zuweisung eines RTWs in ein Krankenhaus per Hotkey. 

Vielen Dank.

**Comment by KBOE2** [comment]
Versuchst dus über den Ziffernblock oder die Zahlenleiste oben?
Zahlenleiste oben wäre hier die richtige Wahl. mit Hilfe von 1-5 auf dem Ziffernblock kannst du im Alamierungsfenster jeweils das erste bis fünfte Fahrzeug wählen/abwählen.

Dann kannst du evtl. mal über F12 bzw. Strg+Umschalt+I die Konsole öffnen und schauen, ob es einen Fehler beim drücken einer der Zahlen gibt.

Grüße und hoffe, ich kann helfen Jan

**Comment by Schneesperling** [comment]
Hallo Jan,

danke für die Rückmeldung. Ich habe die Zahlenreihe genutzt und nach meinem Verständnis sollte dann das entsprechende KH in der entsprechenden Alarmierungsmaske für RTW ausgewählt werden. 

Es gibt tatsächlich eine Fehlermeldung für die Zahlenreihe, hier als Beispiel für die 1.

Uncaught TypeError: Cannot read property 'click' of undefined
    at HTMLDocument.<anonymous> (lss-keyboardAlert.user.js?uid=leitstellenspiel534251:21)
    at HTMLDocument.dispatch (application-8f8a4a5e4169400bc4ff98c7597df405.js:27)
    at HTMLDocument._.handle (application-8f8a4a5e4169400bc4ff98c7597df405.js:27)
(anonymous) @ lss-keyboardAlert.user.js?uid=leitstellenspiel534251:21
dispatch @ application-8f8a4a5e4169400bc4ff98c7597df405.js:27
_.handle @ application-8f8a4a5e4169400bc4ff98c7597df405.js:27

Viele Grüße,
Felix

**Comment by Suchty112** [comment]
Hast du es schon in Firefox probiert. Nur kurz, brauchst da ja nicht dauerhaft mit spielen, aber zumindest ging es bei mir damit. Werde es aber gleich nochmal selbst bei Opera und Chrome probieren

**Comment by Suchty112** [comment]
Okay, konnte den Fehler evtl. ausmachen. 
Wieviele Krankenhäuser hast du selbst? 
Oder versuchst du evtl. an  ein Verbandskrankenhaus zu schicken. 
Weil dort kommt der Fehler bei mir nämlich auch, wenn ich eine Taste drücke die auf ein verbandskrankenhaus zeigen würde.
Das Problem ist, wir können das leider nicht anders machen. Das mit ins Krankenhaus schicken (1-5) ist leider nur für eigene Krankenhäuser nicht für VKH. 
Da diese kein 
`btn_approach_` 
haben.

**Comment by Schneesperling** [comment]
Ah, dann liegt es daran. Ich habe kein eigenes KH, sondern nutze nur VKHs.

Vielen Dank für die raschen Antworten. 

Man könnte ggf. in der Wiki auf diesen Umstand hinweisen.

@Suchty112: Ja, mein Ingame-Name ist LSME.

**Comment by Suchty112** [comment]
Ok fürs nächste mal wenn du was haben solltest weiß ich es :D abundzu brauchen wir auch Infos wg den Addons. 
Naja ich ändere das mal und schließe hier
