### ISSUE TITLE
Beschreibung bei Apps (Vorschlag)

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#33]
## Beschreibung:
Im App-Bereich werden Layouts angeboten, die Beschreibungen sind dabei sehr ähnlich (eigentlich identisch):
![grafik](https://cloud.githubusercontent.com/assets/28895574/26388727/584dc362-4056-11e7-91eb-dcdd973054d2.png)

Die Auswahl nach einem passenden Layout ist daher aktuell "probieren"

## Mögliche Lösung:
In der Beschreibung ein Mini-Bild einfügen, damit man grob die Unterschiede sieht.

**Comment by Tsumiki-Chan** [comment]
Die beschreibungen sollten in der nächsten Beta-Version angepasst sein. Wenn nicht einfach nochmal hierauf antworten.
