### ISSUE TITLE
Dashboard & Layouts laden nicht

### ISSUE THREAD

**Issue by LPNKevin** [LSS-Manager/lss-manager-v3#330]
Seit einigen Tagen lädt das Dashboard nicht mehr. 
Anzeige "Dasboard wird geladen" - keine weitere Reaktion.
Ich habe es auch mit mehreren Browsern versucht (Chrome, Opera & Firefox).
Beim Versuch das Layout zu wechseln um zu probieren, ob es daran liegt, ist mir aufgefallen, dass Layout 1 & 2 nicht laden. Bei mir funktioniert lediglich das Layout 4.

**Comment by Suchty112** [comment]
Seit einigen Tagen kann eigentlich nicht sein. Sondern erst seit gestern morgen. Aber wir arbeiten daran

**Comment by Suchty112** [comment]
#331
