### ISSUE TITLE
wird nicht angezeigt

### ISSUE THREAD

**Issue by RedCrafer** [LSS-Manager/lss-manager-v3#331]
Hi 

gestern ist mir aufgefallen, dass das script nicht mehr lädt... geht nicht nur mir so sondern auch einem kollegen von mir  [https://i.imgur.com/LIWrLTg.png](url)

[https://i.imgur.com/1PEYTpS.png](url)

kam ein update oder was läuft da falsch?

**Comment by Suchty112** [comment]
Uns ist leider unser wahrscheinlich wichtigster server ausgefallen. Es wird aber daran gearbeitet. Da es Wochenende ist, kann es sich leider noch weiter verzögern

**Comment by RedCrafer** [comment]
alles klar vielen dank für die schnelle rückinfo!

**Comment by Benjakos** [comment]
gibt es zu dem Thema eine neue Information? Bei mir wird das script leider auch nicht angezeigt.

**Comment by Suchty112** [comment]
Nein aktuell leider noch nicht. Wir würden uns dann melden wenn es wieder laufen sollte. ☺

**Comment by Benjakos** [comment]
Okay, danke für die schnelle Antwort!

**Comment by Suchty112** [comment]
Sollte wieder funktionieren. Damit schließe ich hier.
