### ISSUE TITLE
Einstellungen bei aktiviertem dunklem Design kaum lesbar

### ISSUE THREAD

**Issue by KBOE2** [LSS-Manager/lss-manager-v3#334]
Moinsen zusammen,
Mir ist aufgefallen, dass die Einstellungen bei dunklem Design kaum lesbar sind.
Hier ein Bild dazu: 
![image](https://user-images.githubusercontent.com/27238105/39007308-d81bd42c-4405-11e8-93fd-d1ff474d6752.png)

Grüße Jan

**Comment by Tsumiki-Chan** [comment]
Erstmal fixed (Jumbotron entfernt)
