### ISSUE TITLE
Dialog - etwas flackert

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#34]
## Fehlermeldung:
Wenn die Dialoge (Alarmierung/Sprechwunsch) geladen werden, flackern diese an einer bestimmten Stelle, siehe Screenshot gelb markierter Bereich:

![grafik](https://cloud.githubusercontent.com/assets/28895574/26389376/fdab1c94-4059-11e7-958b-7e1da7151746.png)

## Aktivierte Module:
- Layout01
- Einsatzliste komprimieren
- Chatpopup
- FMS5 in Karte
- Clock
(ist aber davon unabhängig, auch ohne Module)

#### Beta Version: beta 0.1

**Comment by Tsumiki-Chan** [comment]
Ist das Flackern permanent?

**Comment by FlorianRhausen** [comment]
Ja, eventuell ist flackern nicht der richtige Begriff, es sieht so aus, als wäre da kurz am Anfang noch ein Schatten an der gelb markierten Linie, dann wird der Schatten weggenommen und das Bild bleibt ruhig, bis man zum nächsten Einsatz springt.

**Comment by Tsumiki-Chan** [comment]
Das gleiche phänomen hatten wir schon im LSS-Manager V2 beobachtet. Es scheint dann auf zu tauchen, wenn der LSS-Manager sein Stylesheet einhängt. Somit kommt es zu einem kurzen "Flackern", was dann auch sofort verschwinden sollte.

**Comment by lostdesign** [comment]
Wurde behoben.
