### ISSUE TITLE
Zugriffszeiten hoch bzw Seite nicht erreichbar

### ISSUE THREAD

**Issue by keksi27bln** [LSS-Manager/lss-manager-v3#341]
HAbe seid einigen Tagen folgendes Problem

Sobald der LSS Manager aktiv ist, laufen Anfragen an die Webseite ins unermessliche an Zeit bzw wird angezeigt, das Seite nicht erreichbar...

Spielt man ohne dem Plugin, läuft das Spiel absolut sauber ohne irgendwelche Verzögerungen :(

**Comment by jplight** [comment]
Bei mir seit gestern auch das Problem.
Seite lädt Minutenlang, stürzt ab und wenn geladen, dann kann ich keinen SW bearbeiten
--> leeres Pop-Up

Ohne aktiviertes Plugin läuft alles flüssig. Auch getestet, wenn nur LSSM aktiv war.

Nutze Chrome (Version 66.0.3359.139 (Offizieller Build) (64-Bit))
Auf Win 10 Home (Version 1709)

**Comment by jplight** [comment]
https://1drv.ms/f/s!AqSowvJL1pzgsxYrrYeVURZwx-tK
Hier ein Screenshot.

Heute abend scheint es wieder besser zu sein. Mal beobachten.
