### ISSUE TITLE
Einsatzliste - Icons fehlen

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#35]
## Fehlermeldung:
Icons fehlen, siehe Screenshot:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26389667/5915b2fa-405b-11e7-93bc-25d998e50e89.png)

## Aktivierte Module:
- Layout01
- Einsatzliste komprimieren
- Chatpopup
- FMS5 in Karte
- Clock

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: 0.1

**Comment by FlorianRhausen** [comment]
##Nachtrag
Wenn ich auf die App-Seite wechsel und wieder zurück (schätzungsweise kompletter Refresh der Seite) kommen die Icons zurück.

**Comment by DLRG-Dominik** [comment]
Tritt das öfters auf? 
Wann tritt dies speziell auf, also was hast du davor gemacht.

**Comment by FlorianRhausen** [comment]
Es scheint am Layout 1 zu liegen - in den anderen Layouts noch nicht aufgefallen.
Jetzt habe ich sogar einen umgekehrten Fall, wo zuviele Icons da sind:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26408047/0e829a9a-409d-11e7-8c74-46c5c5a67e8a.png)

Ich hab eigentlich nur den Browser geöffnet, hab gesehen das eine Gasexplosion sich ausgebreitet hatte, gab die über den Button im Verband frei, bin in die Alarmierung gesprungen und hab die AAO Gasexplosion gestartet und aus dem Fenster wieder raus. 

Dann wollte ich noch schnell schauen, ob gute einsätze da sind und dabei fiel mir jetzt auf, das die Icons zuviel sind .... so war das auch heute morgen wo die Icons gefehlt haben.

Ich beobachte das aber nun speziell weiter und meld mich dann, wenn ich das nochmal sehe.

**Comment by lostdesign** [comment]
Scheint an *MissionOut* zu liegen. Dort wird zumindest mit dem Icon gearbeitet.

**Comment by Tsumiki-Chan** [comment]
Wenn das Problem auftritt bitte mal mit Strg+Shift+I (oder F12) das Entwicklermenü öffnen, in die Konsole gehen und uns die Fehler, die ausgegeben wurden, mitgeben.

**Comment by Tsumiki-Chan** [comment]
Im nächsten Update gefixed
