### ISSUE TITLE
Uhr klebt fest

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#352]
Mit der "neuen" [Karte](https://www.leitstellenspiel.de/?mapkit=1)  klebt die Uhr statisch fest und lässt sich auch nicht mehr verschieben. 

> TypeError: map.dragging is undefined[Weitere Informationen]
clock.user.js:56:21

kommt dann als Fehlermeldung.

Desweiteren rutscht dadurch die Map nach unten.
Dieses würde sich wahrscheinlich mit 
`position: absolute;` für die map fixxen lassen.

Vlt. mag sich daran ja jemand versuchen das zu fixxen :)

**Comment by KokosnussDEV** [comment]
Ich habe die Uhr garnicht in LSS obwohl im AppStore aktiviert

**Comment by Suchty112** [comment]
> Ich habe die Uhr garnicht in LSS obwohl im AppStore aktiviert

Hast du als KartenTyp Mapkit? Dann liegt es daran, weil sie da noch nciht geht.
Funzt aktuell nur mit Openstreetmaps

**Comment by KokosnussDEV** [comment]
Jo hab ich auch gesehen

**Comment by Suchty112** [comment]
Mapkit unterstützung schwierig daher close
