### ISSUE TITLE
Karte abgeschnitten

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#36]
## Fehlermeldung:
Die Karte wird im unteren Bereich öftersmal nicht nachgeladen:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26389777/e0ffe064-405b-11e7-9f95-3f74b7381a5a.png)

## Aktivierte Module:
- Layout01
- FMS5 in Karte
- Clock
- Chatpopup

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: 0.1

**Comment by FlorianRhausen** [comment]
Wenn in der Karte gescrollt wird, kann auch sowas passieren: 
![grafik](https://cloud.githubusercontent.com/assets/28895574/26389828/16a0051e-405c-11e7-81a9-4e23eb08959b.png)

**Comment by Tsumiki-Chan** [comment]
Klick mal, wenn der Bug auftritt, oben links auf das "neu laden" Icon. Damit sollte die Karte neu ausgerichtet werden.

**Comment by FlorianRhausen** [comment]
Okay, das funktioniert.

**Comment by Tsumiki-Chan** [comment]
https://github.com/lostdesign/lss-entwicklung/commit/c2bdc8c01e8fef9cff30f06c4bda9d3d886d4ef4

Im nächsten Update wird nach aktivierung von layout01 die map automatisch neu zentriert werden.
