### ISSUE TITLE
Gebäudeliste: Details zu Gebäuden minimieren (Vorschlag)

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#37]
## Beschreibung:
Bei der Gebäudeliste müssen Details zu den Gebäuden über das Icon direkt ein- und ausgeblendet werden, eine allgemeine Funktion um alle Gebäude zu minimieren oder aufzumachen gibt es nicht:

![grafik](https://cloud.githubusercontent.com/assets/28895574/26391420/fd6efb70-4062-11e7-9b0c-6e8bc981e12d.png)

## Mögliche Lösung:
Details zu den Gebäuden auf- und zuklappen, wie bei den Einsätzen über diesen Button auch: 

![grafik](https://cloud.githubusercontent.com/assets/28895574/26391439/1b6ffd36-4063-11e7-8d3c-88971c3dbc26.png)

**Comment by Tsumiki-Chan** [comment]
Nicht möglich, weil die Funktion zum Einklappen von Einsätzen von Sebastian einen Seitenaufruf auslöst.

(Sebastian würde uns erschlagen)
