### ISSUE TITLE
Pictogramm für Karte ausgliedern fehlt

### ISSUE THREAD

**Issue by OiledAmoeba** [LSS-Manager/lss-manager-v3#4]
## Fehlermeldung:
Design#1: Der Button für Karte in Popup ausgliedern ist da und hat die gewünschte Funktion, das Bildchen wird aber nicht angezeigt. Es ist einfach ein leeres Quadrat in der Größe des Reload-Buttons zwischen Zoom und Reload.

## Aktivierte Module:
- 

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Browser: 
Google Chrome
#### Version: 
58.0.3029.110 (64-bit)
#### Beta Version: 
0.1

**Comment by Tsumiki-Chan** [comment]
Fehler gefunden, ist in der nächsten Version gefixed
