### ISSUE TITLE
"Im Verband freigeben" Button

### ISSUE THREAD

**Issue by BSTim** [LSS-Manager/lss-manager-v3#40]
Fehlermeldung/Vorschlag:
Wenn ich den Button "Im Verband freigeben" anklicke, dann schiebt sich alles nach oben bzw. springt die Seite nach oben.

Aktivierte Module:
STATISTIK
DASHBOARD
EINSATZLISTE KOMPRIMIEREN
NOTIFICATION ALERT
EINSÄTZE FREIGEBEN

Mögliche Lösung / Verbesserungsvorschlag:
das die Seite auf der "Ebene" bleibt da wo sie ist.

Browser: Chrome
Version: neuste Version
Beta Version: 0.1

**Comment by DLRG-Dominik** [comment]
Kannst du davon mal ein Foto machen. Ich habe gerade mal das getestet, also habe deine Module aktiviert und dann den "Im Verband freigeben" Button gedrückt. Bei mir war alles normal. 

Also am besten ein Foto und eine Beschreibung was du halt genau gemacht hast.

**Comment by BSTim** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/24434140/26422659/fecac310-40ca-11e7-8419-0d4f456f16eb.PNG)
Ich habe den Button gedrückt und die ganze Seite hat sich nach oben "geschoben"

**Comment by DLRG-Dominik** [comment]
hm, ok jetzt wird mir einiges klar. Bitte auch bei aktivierte Module ALLE Module angeben die aktiviert sind. 

Weil du hast ja mehr als nur Statistik und Dashboard aktiviert. 

Bitte Korrigiere dies, danach können wir mit der Fehlersuche weiter machen.

**Comment by BSTim** [comment]
ahhh okay sry

**Comment by DLRG-Dominik** [comment]
keine Layouts aktiviert?

**Comment by DLRG-Dominik** [comment]
Habe das ganze gerade ausprobiert.  Dies ist aber so, das wir dies im HG neuladen und dadurch LSS nach oben geschoben wird. 

Ich nehme dies als Vorschlag mal auf und gebe es mal an Lost weiter, eventuell kann er ja was dran machen. Bin mir da aber gerade nicht sicher ob da eine Lösung gibt.

**Comment by BSTim** [comment]
ne Layouts habe ich keine.

**Comment by Mausmajor** [comment]
sollte im nächsten update gefixt sein
