### ISSUE TITLE
Vorschlag: Personenanforderung im Einsatzhelfer

### ISSUE THREAD

**Issue by RanjidTatu** [LSS-Manager/lss-manager-v3#404]
» Vorschlagbeschreibung
Anzeigen der Personenanforderung wie z.B. bei einem Supermarktbrand wo man mindestens 33 Personen braucht aber je nach Fahrzeug Auswahl was man hin schicken möchte/kann nicht auf die 33 Personen kommt.
» Name im Spiel
RanjidTatu
» Browser & Version
Chrome
» Version des Scripts
Beta 3.3.0
» Zeitpunkt des Auftretens:
Immer

**Comment by KBOE2** [comment]
Die Möglichkeit besteht nun, dies in den Einstellungen des Einsatzhelfers zu (de-)aktivieren.
