### ISSUE TITLE
APPSTORE Beschreibung

### ISSUE THREAD

**Issue by BSTim** [LSS-Manager/lss-manager-v3#41]
Fehlermeldung/Vorschlag:
Das Bild sagt es schon. Ich kann das "Hier" nicht anklicken bzw. ist das "Hier" nicht href mit dem Forum

Aktivierte Module:
...

Mögliche Lösung / Verbesserungsvorschlag:
![appstorebes](https://cloud.githubusercontent.com/assets/24434140/26423038/5e1dfa48-40cc-11e7-9977-7a80cae01ded.PNG)

Browser: Chrome
Version: neuste Version
Beta Version: 0.1

**Comment by Tsumiki-Chan** [comment]
Wird in der nächsten Beta-Version gefixed.
