### ISSUE TITLE
Verbandsforum Anzeigefehler

### ISSUE THREAD

**Issue by JanH8** [LSS-Manager/lss-manager-v3#42]
## Fehlermeldung:
Verbandsforum (siehe Screenshot)
![image](https://cloud.githubusercontent.com/assets/16578440/26423256/3c3ca3a6-40cd-11e7-893b-7716e9cbceae.png)

## Aktivierte Module:
-LAYOUT 01
-EINSATZLISTE KOMPRIMIEREN
-FAHRZEUG TABLEAU
-FMS 5 IN DER KARTE
-RENAMEFZ
## Mögliche Lösung / Verbesserungsvorschlag:

- keine -

**Comment by BSTim** [comment]
gibts schon :P

**Comment by JanH8** [comment]
Sorry :(

**Comment by DLRG-Dominik** [comment]
Closed da Duplikat.
