### ISSUE TITLE
Mouseover AAO - Anfahrtszeit / Problem

### ISSUE THREAD

**Issue by Topix1** [LSS-Manager/lss-manager-v3#428]
Seitdem Sebastian die Wartung vor wenigen Tagen durchgeführt hat, habe ich Probleme beim Anzeigen der Anfahrtszeit bei "Mouseover auf die AAO"
Bisher wurde immer alles korrekt angezeigt, außer, wenn die Fahrzeuge zu weit entfernt waren und man die Fahrzeugliste nachladen musste.
Seit kurzem klappt die Anzeige meistens nicht - selbst bei einer AAO "1 Fustw" zeigt er die Anfahrtszeit sehr oft nicht an, wenn der Fustw auf Platz 1 der Fahrzeugliste ist und nur wenige Sekunden bis zum Einsatzort braucht.  Da es ---sehr selten--- aber klappt, kann es m.E. nicht an meinen AAO liegen, sondern eigentlich eher am Plugin. Wäre klasse, wenn ihr das mal prüfen könntet. Ingame-Nick --> Topix

**Comment by Suchty112** [comment]
JA es liegt auch am Plugin. Wann wir es gefixxt kriegen, können wir artok so nicht sagen. Wir wissen darüber aber schon bescheid, da es im Forum direkt danach reportet worden ist.

**Comment by Topix1** [comment]
Alles klar, danke!

**Comment by Keppchen** [comment]
Gibts hier mittlerweile Neuigkeiten?

**Comment by KBOE2** [comment]
Ja: Wenn die Zeit vorhanden ist, wird dran gearbeitet. Wann das sein wird ist aber definitiv nicht vorhersehbar.(Auch kein grobes Datum)

**Comment by Suchty112** [comment]
Solllte sich hiermit erledigt haben. DAnke Sebastian :)
https://blog.leitstellenspiel.de/aao-maximale-fahrzeit/
