### ISSUE TITLE
POI Check

### ISSUE THREAD

**Issue by JanH8** [LSS-Manager/lss-manager-v3#43]
Ganz normal versucht POI zu Checken.
![image](https://cloud.githubusercontent.com/assets/16578440/26425295/96e816f8-40d4-11e7-8ba8-2231de8cbf95.png)

## Aktivierte Module:
-LAYOUT 01
-EINSATZLISTE KOMPRIMIEREN
-FAHRZEUG TABLEAU
-FMS 5 IN DER KARTE
-RENAMEFZ
## Mögliche Lösung / Verbesserungsvorschlag:

- keine -

**Comment by Tsumiki-Chan** [comment]
http://i.imgur.com/ySePvAY.png
Das ist ein bug von LSS und nicht durch den LSS-Manager verursacht.
