### ISSUE TITLE
renameFZ.user.js

### ISSUE THREAD

**Issue by Dexus** [LSS-Manager/lss-manager-v3#436]
Es wäre cool, wenn man dieses Script mal etwas umbauen würde, so das man es im Batch macht, und nicht alles auf einmal, glaube damit könnte man das Abstürzen verhindern.

Gruß

**Comment by Dexus** [comment]
Also ich habe mir das mal angesehen und muss sagen, das sollte man mal refactoren, völlig falsche was die Arrays angeht beim erstellen... und unnötige arrays mit IDs [i -1] .... also völlig Blödsinn.

wenn es gut geschrieben ist, wird auch nicht von chrome gefragt ob man warten will oder schließen.

Gruß

**Comment by KBOE2** [comment]
Du bist jederzeit herzlich eingeladen, das selbst zu verbessern und dann einen PullRequest zu eröffnen.

**Comment by Suchty112** [comment]
Da es seitens Dexus ja keine weitere Rückmeldung gab, schließen wa hier ;)
