### ISSUE TITLE
LSS  Feuer in Bank

### ISSUE THREAD

**Issue by Robitour** [LSS-Manager/lss-manager-v3#438]
[missing "de.lssm.missionHelper.missions.433" translation]  kommt als Fehlermeldung

**Comment by Suchty112** [comment]
Das wird Freitags bei den neuen Einsätzen immer so sein... Wir warten bis Sebastian alle Spiele geupdatet hat und das dauert halt mal ein paar Stunden und da haben wir auch nix dagegen :) . Es gibt ja immer noch die Hilfe zum Einsatz :)
