### ISSUE TITLE
Buttons Verbandfreigabe/Ausblenden liegen teilweise über Patientenanzahl

### ISSUE THREAD

**Issue by BjoernEnd** [LSS-Manager/lss-manager-v3#44]
## Fehlermeldung:
Bei meinem 15" MacBook überblenden die Buttons "Im Verband freigeben" und "Ein/Ausblenden" leicht die Anzahl der Patienten.

## Aktivierte Module:
- LAYOUT 01
- MISSIONOUT
- NOTIFICATION ALERT
- EINSÄTZE SUCHEN

<img width="1440" alt="bildschirmfoto 2017-05-25 um 11 56 22" src="https://cloud.githubusercontent.com/assets/28508122/26446104/09049090-4143-11e7-952b-be767163caa1.png">

## Mögliche Lösung / Verbesserungsvorschlag:
- Nach Möglichkeit im Panel Header der jeweiligen Einsätze mehrere Reihen nutzen
-> Beispiel:
--> Reihe 1: ** Buttons: Alarm, Verbandfreigabe, Ein/Ausblenden, Patientenanzahl **
--> Reihe 2: ** EINSATZ BESCHREIBUNG **
--> Reihe 3: ** Straße + Hausnummer **
--> Reihe 4: ** Ort **

#### Beta Version: 0.1

**Comment by FlorianRhausen** [comment]
Seit heute sind die Buttons auch nicht mehr nach oben hin bündig:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26481630/c7da0ff0-41e2-11e7-8dbc-2aa147fb0aea.png)

Browser: Firefox
Version: 53.0.2 32bit
Beta Version: 0.1

Zum Vorschlag von BjoernEnd - würde ich aber bei der Aufteilung der Reihen ein wenig anders vorgehen:
1. Reihe: Buttons und Einsatzbeschreibung (dafür den Alarm-Button als Piktogramm)
2. Reihe: Adresse

sonst könnte die Anzahl an Reihen schnell unübersichtlich werden

**Comment by lostdesign** [comment]
Cache geleert?

**Comment by Tsumiki-Chan** [comment]
Die sind nicht überdeckt. Das täuscht. Siehe lost's kommentar. Ich mach da mal was
