### ISSUE TITLE
Vorschlag: Einsätze (Verband, Eigene) in Tabs legen anstatt Ein/Ausblenden

### ISSUE THREAD

**Issue by BjoernEnd** [LSS-Manager/lss-manager-v3#45]
## Beschreibung:
Ich habe vor kurzen mal ein kleines Script getestet, welches die Einsätze statt mit Buttons ein/Ausblendet, Sie in einzelne Tabs zu setzen.

## Mögliche Lösung:
- In Bootstrap gibt es die Funktion "Tabs and Pills"
-> https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.ass

**Comment by lostdesign** [comment]
Wo ist dabei der unterschied? Im Hintergrund passiert doch genau dasselbe? Ich verstehe nicht ganz.

**Comment by BjoernEnd** [comment]
Okay, ich habe mich nicht richtig ausgedrückt. Ich habe immer gerne nur EINE Ansicht. Als Beispiel meine eigenen Einsätze. Nun wenn ich die Verbandseinsätze angezeigt bekommen möchte, muss ich erst meine Ausblenden und dann die Verbandseinsätze einblenden, wenn ich Sie vorher ausgeblendet habe. In Layout 1 werden Chat und Gebäude und Einsätze ja auch in Tabs gepackt. Genau so meinte ich das bei den Einsatzarten.

Ich weis nicht in wie weit das für andere Hilfreich ist. Wie gesagt, nur ein vorschlag :-)

**Comment by lostdesign** [comment]
Also man kann es so machen - nur als Tipp: Doppelklick auf den Einsatzfilter == nur diese Einsatzart anzeigen. Eventuell schreiben wir ja ein Modul das aus einem Doppelklick einen einzelnen macht?

**Comment by BjoernEnd** [comment]
Okay, diese Funktion kannte ich noch nicht. Gut warum nicht. So wie es für euch möglich ist :-) Wie gesagt, mir wäre ein Tab-System lieber. Aber bin ja nicht der einzigste Spieler :-D

**Comment by Thomas21030** [comment]
@lostdesign,  ich glaube der meint sowas wie 

![einsatzliste 1](https://cloud.githubusercontent.com/assets/28989752/26744989/d8fe5fdc-47e8-11e7-846f-11126288d386.JPG)

**Comment by BjoernEnd** [comment]
Ich glaube es gab mal eine Erweiterung die so ein Tab-System ermöglichte. Sieht auf jeden fall so aus, wie das was ich mal gesehen hatte. Danke Thomas!

**Comment by stefschen** [comment]
Das "allgemeine Leitstellenscript" hatte diese Funktion ;)

**Comment by lostdesign** [comment]
@stefschen kennen wir - werden wir auch umsetzen. Das 'ASL' macht es technisch auf eine nicht elegante Art & Weise.

**Comment by KBOE2** [comment]
Ist mal zu #537 zusammengefasst
