### ISSUE TITLE
WachenHover und Heatmap zeigen nix mehr an

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#454]
Damit wir es hier haben:
Sebastian hat auch im Zuge des einen Fehler im Forum, das Lehrgänge lange laden diese Funktion hinzugefügt:
https://github.com/Suchty112/LSSD/commit/d813762413d7d36ec7a815e77753cd173ddb08d3

Dadurch, das wir augenscheinlich einiges deswegen nicht mehr auslesen können:
https://github.com/LSS-Manager/lss-manager-v3/blob/dev/modules/lss-WachenHoverStati/WachenHoverStati.user.js#L27
https://github.com/LSS-Manager/lss-manager-v3/blob/dev/modules/lss-heatmap/LSHeatmap.user.js#L199
https://github.com/LSS-Manager/lss-manager-v3/blob/dev/lss-manager-v3/helperfunctions.js#L195
funktionieren die Heatmap nicht mehr sowie WachenHogerStati aka WachenStatus

**Comment by CSA-Verweigerer** [comment]
Trifft auch das Dashboard

**Comment by Tsumiki-Chan** [comment]
Ist mit 3.3.4 fixed.
