### ISSUE TITLE
Mapkit inkompatible Module

### ISSUE THREAD

**Issue by Tsumiki-Chan** [LSS-Manager/lss-manager-v3#459]
Mit Mapkit inkompatible Module ab sofort nicht mehr mit einem "alert" blockieren, sondern im Appstore nicht aktivierbar machen und automatisch deaktivieren, sollte MapKit aktiv sein.

**Comment by KBOE2** [comment]
Aber dann mit Hinweis im Appstore, dass nicht kompatibel mit Mapkit.

**Comment by Tsumiki-Chan** [comment]
done
