### ISSUE TITLE
Vorschlag: Gebäudefilter

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#46]
Moin, mal nebenbei ein kleiner Vorschlag, das man auf der Karte sich gezielt Gebäudetypen anzeigen lassen kann - ähnlich dem Wachen-Radius, das man dann nur noch die Gebäude sieht, die angehakt sind.

Wäre auch im Verband nicht schlecht.

**Comment by Ron31** [comment]
Vom Spiel hinzugefügt: 
[Forum](https://forum.leitstellenspiel.de/index.php?thread/18853-neuerungen-im-spiel-und-fehlerbehebungen/) 
[Blog](https://blog.leitstellenspiel.de/neuerungen-im-spiel-und-fehlerbehebungen/)
