### ISSUE TITLE
Dashboard funktioniert nicht 

### ISSUE THREAD

**Issue by OStAp141** [LSS-Manager/lss-manager-v3#461]
» aktuell wird im Dashboard bei mir nur die Anzahl der Gebäude angezeigt; Auswahl der Orga/Fahrzeuge/Wachenplanung nicht mehr möglich
- 
OStAp

Firefox Quantum 66.0.1, Win10, Stable 3.3.3
-

**Comment by Suchty112** [comment]
#454 Und man könnte bitte auch mal ins Forum gucken :) . Es ist bekannt, und wir arbeiten daran. Wir haben auch Freizeit :) Und damit Close
