### ISSUE TITLE
Beta 3.3.4: Ladezeit für Dashboard >50 Sekunden

### ISSUE THREAD

**Issue by CSA-Verweigerer** [LSS-Manager/lss-manager-v3#466]
Hallo, 

ich wollte das Dashboard in 3.3.4 öffnen (keine anderen Scripte außer dem LSS-Manager aktiv)
Die Ladezeit des Dashboard beträgt bei mir 40 Sekunden bis sich das weiße Fenster öffnet und knapp 60 Sekunden bis zur Anzeige der Grafiken.

Sonstige sachdienliche Hinweise: 
Browser Opera v 58.0
sonst keine weiteren Programme geöffnet

Bei weiteren Fragen einfach melden

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by KBOE2** [comment]
Das liegt sicher daran, dass du so viele Wachen hast. 3209 sind ja jetzt nicht gerade wenig :smile: 
Das ist aber gut, dass du das schreibst, dann wissen wir, dass da noch etwas an der Performance geschraubt werden muss, danke! :+1:

**Comment by Tsumiki-Chan** [comment]
> Die Ladezeit des Dashboard beträgt bei mir 40 Sekunden bis sich das weiße Fenster öffnet

Okay, das ist aber doch schon etwas sehr lange, wenn es nur um das öffnen des Fensters geht.

**Comment by Tsumiki-Chan** [comment]
Mal schauen, ob es mit b72ed63eafa856c275f18bb0d2ab29abccdcaee8 und 0202d42953dcc50fd36c086cca9f031f231cdb05 besser wird.

**Comment by CSA-Verweigerer** [comment]
Habs getestet, 

Ladezeit vom Dashboard im Bereich 2 Sekunden. 

Perfekt, Danke!!! 

Sent by MailWise – See your emails as clean, short chats.

-------- Originalnachricht --------
Betreff: Re: [LSS-Manager/lss-manager-v3] Beta 3.3.4: Ladezeit für Dashboard >50 Sekunden (#466)
Von: Tsumiki <notifications@github.com>
An: LSS-Manager/lss-manager-v3 <lss-manager-v3@noreply.github.com>
Cc: CSA-Verweigerer <Manuel@haischt.de>,Author <author@noreply.github.com>

**Comment by Tsumiki-Chan** [comment]
2 Sekunden schneller oder 2 sekunden bis geöffnet?
Und was ist wenn du die tabs durchwechselst?



Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: CSA-Verweigerer <notifications@github.com>
Datum: 30.03.19 08:08 (GMT+01:00)
An: LSS-Manager/lss-manager-v3 <lss-manager-v3@noreply.github.com>
Cc: Tsumiki <mirkoiz@hotmail.de>, Comment <comment@noreply.github.com>
Betreff: Re: [LSS-Manager/lss-manager-v3] Beta 3.3.4: Ladezeit für Dashboard >50 Sekunden (#466)

Habs getestet,

Ladezeit vom Dashboard im Bereich 2 Sekunden.

Perfekt, Danke!!!

Sent by MailWise – See your emails as clean, short chats.

-------- Originalnachricht --------
Betreff: Re: [LSS-Manager/lss-manager-v3] Beta 3.3.4: Ladezeit für Dashboard >50 Sekunden (#466)
Von: Tsumiki <notifications@github.com>
An: LSS-Manager/lss-manager-v3 <lss-manager-v3@noreply.github.com>
Cc: CSA-Verweigerer <Manuel@haischt.de>,Author <author@noreply.github.com>

**Comment by CSA-Verweigerer** [comment]
Sorry, wenn ich unklar in der Formulierung war. 
Das Dashboard ist in der Standardansicht jetzt nach ca. 2 Sekunden geöffnet, also quasi 30x schneller als Vorher. Gaaanz großen Dank dafür!!!

Wenn ich durch die Tabs springe, öffnet sich "Fahrzeuge" in ca. 2 Sekunden, Wachenplanung dauert ca. 50 Sekunden, unabhänig ob erster oder zweiter Aufruf. 

Filtern auf die einzelnen Bereiche innerhalb der Wachenplanung dauert zwischen  1 Sek (Sonstige) und 13 Sek. (Feuerwehr)

**Comment by Tsumiki-Chan** [comment]
Okay. Dann liegt es an der wachenplanung. Schsuen wir uns demnächst an :)


Von meinem Samsung Galaxy Smartphone gesendet.

**Comment by Tsumiki-Chan** [comment]
Geht weiter in #471
