### ISSUE TITLE
Sorting Missionlist after Priority

### ISSUE THREAD

**Issue by olekristian** [LSS-Manager/lss-manager-v3#469]
Not sure if this is the right place to post, but I'm looking for a plugin / feature that sorts the missions after priority.

**Comment by KBOE2** [comment]
What do you mean with "sort the missions after priority"?
We don't have a plugin that sorts the missions yet.

**Comment by olekristian** [comment]
I mean that the trash can fire gets placed on the bottom of the mission
list, while the building collapse gets placed on top of it.
Basically just sorting them after how urgent they are, placing non urgent
calls on the bottom.

**Comment by KBOE2** [comment]
Thats a good Idea for a plugin!
I think, we can add this.

**Comment by der-homer** [comment]
Also it could be sorted by color. Red on top green at the bottom.

**Comment by KBOE2** [comment]
referencingt to #147 
duplicated suggestion => Close
