### ISSUE TITLE
Wachen Status

### ISSUE THREAD

**Issue by FFW115** [LSS-Manager/lss-manager-v3#470]
Ich habe die Funktion "Wachen Status" aktiviert, doch wenn ich mit der Maus über eine Wache fahre, wird zwar der Wachenname angezeigt, die dort Stationierten Fahrzeuge samt Status jedoch nicht. Hier steht nur "undefined"
![Fehler Wachen Status](https://user-images.githubusercontent.com/45369769/55267647-be651600-5283-11e9-8ee3-6331d867af20.PNG)

 Erst wenn diese zu einem Einsatz alarmiert worden sind, werden sie angezeigt.

**Comment by KBOE2** [comment]
Immernoch bekannt, siehe andere Issues oder im Forum!
