### ISSUE TITLE
Heatmap noch auf alten Stand

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#474]
Heatmap ist noch nicht umgebaut auf API https://github.com/LSS-Manager/lss-manager-v3/blob/dev/modules/lss-heatmap/LSHeatmap.user.js#L199
Holt sich die Daten aktuell noch aus aus der Gebäudeliste.

Desweiteren ein kleiner Fehler:
Sollte man sie deaktvieren und wieder aktivieren sollen über das Häkchen kommt es zum Folgenden Error:
```
Uncaught TypeError: Cannot read property '_leaflet_id' of null
    at n (application-6c51a386dc5683afaadae97f3c080298.js:199)
    at i.removeLayer (application-6c51a386dc5683afaadae97f3c080298.js:201)
    at renderMap (LSHeatmap.user.js?uid=leitstellenspiel675:221)
    at HTMLInputElement.<anonymous> (LSHeatmap.user.js?uid=leitstellenspiel675:159)
    at HTMLInputElement.dispatch (application-6c51a386dc5683afaadae97f3c080298.js:27)
    at HTMLInputElement._.handle (application-6c51a386dc5683afaadae97f3c080298.js:27)
```
Zeilen sind folgende laut fehlermeldung oben:

```js
            map.removeLayer(heat);

renderMap();
```
Und dadurch wird augenscheinlich auch die map grau bzw lädt net

**Comment by miba112** [comment]
Ich wollte mal vorsichtig nachfragen, ob es hier weiter geht. Die Heatmap lädt bei mir gar nicht mehr seit der Umstellung von Sebastian. Habe deshalb die Ausbau Aktivitäten gestoppt. Nutze FF 66.0.3, habe über 600 Wachen und über 5000 Fzg.
Die meisten anderen Module habt ihr ja schon fleißig repariert oder seid dabei, großen Respekt vor eurer Arbeit. Umbenennen läuft z.B. sehr viel besser, als vorher. Wenn jetzt die Heatmap noch funktioniert, kann ich wieder loslegen. Hätte mittlerweile 160Mio Credits auf der Map zu verteilen, und das macht ohne Heatmap keinen Spaß.
Grüßle
miba112

**Comment by KBOE2** [comment]
Ja, es geht weiter. Aber wann wir soweit sind weiss keiner. Musst dich noch a weng gedulden.

**Comment by fidelcastro54** [comment]
> Ja, es geht weiter. Aber wann wir soweit sind weiss keiner. Musst dich noch a weng gedulden.

Gibts schon einen neuen Stand?

**Comment by Suchty112** [comment]
Siehe #511 . Sollte nächste Woche gefixxt sein, bzw. onlien sein :) Damit schließe ich hier shconmal
