### ISSUE TITLE
Menüpunkte nicht erreichbar (Scrollbars fehlen)

### ISSUE THREAD

**Issue by grokash** [LSS-Manager/lss-manager-v3#475]
Keine Ahnung ob das nur bei mir ist aber ich komme an dieunteren Menüpunkte  nicht mehr ran.
App-Store, Dashboard & Einstellungen. In allen dreien das selbe.

![lss_manager](https://user-images.githubusercontent.com/22556838/55404806-04a6c780-5559-11e9-9fde-40f1dc050397.JPG)

**Comment by Suchty112** [comment]
Alles klar, danke für die Rückmeldung. Auch wenns dir vorerst nicht gefallen sollte, such über die suche da im fenster nach redesign01 deaktiviere es und lade die seite neu. Da musst du dann halt erstmal mit dem normalen design spieln.
Wir werden mal schauen woran es liegt an dem Design.

**Comment by Suchty112** [comment]
Ist gefixxt :) kannst du gerne wieder einschalten.
