### ISSUE TITLE
KM Begrenzung u. Volle Krankenhäuser werden nicht ausgebledet

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#477]
https://forum.leitstellenspiel.de/index.php?thread/11166-lss-manager-v3/&postID=272738#post272738
> Bei MC funzten das Ausblenden der vollen Krankenhäuser und die KM Begrenzung nicht
> 
> https://screenshots.firefox.co…9cVs/www.missionchief.com
> 
> https://screenshots.firefox.co…lFeF/www.missionchief.com
> 
> https://screenshots.firefox.co…XONi/www.missionchief.com
> 
> Was mache ich verkehrt?:/

Desweiteren zeigt er die "Einstellungen" auch dort (MC) nicht im FEnster beim RTW an, was es bei mir in lss zumindest immer gemacht hat

Ich werde auch schauen obs in MEL genauso is
Mel zeigt er die Einstellungen im RTW Fenster an und der rest klappt auch. Liegt an Punkt und Komma

**Comment by KBOE2** [comment]
Ich weiss nicht, warum es nicht funktioniert. Ich hab aber leider au noch kein Krankenhaus zum Testen...

**Comment by KBOE2** [comment]
Müsste gefixed sein, siehe 3a5a803.
