### ISSUE TITLE
Gitternetz der Landkarte

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#48]
## Fehlermeldung:
In einem gewissen Zoombereich der Karte, sieht man hellgraue Gitternetze (scheinbar die Segmenttrennung der einzelnen Kartenbereiche. Zommt man weiter rein oder raus, sind die Weg
![grafik](https://cloud.githubusercontent.com/assets/28895574/26482863/f99cb18a-41e9-11e7-8394-df44cdb79763.png)

## Aktivierte Module:
- Layout 01
- Missionout
- FMS5 in Karte
- Clock
- Einsätze freigeben
- Fahrzeuge umbenennen

## Mögliche Lösung / Verbesserungsvorschlag:
Prinzipiell nicht schlecht, sollte aber entweder durchgängig drin oder draussen sein. Eventuell wenn man die generell reinmacht, in einer leicht kräftigeren Farbe - sieht eigentlich Schick aus ;-)

#### Beta Version: 0.1

**Comment by FlorianRhausen** [comment]
hm, ich kann das ohne Problem bei mir reproduzieren:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26486774/e195bc68-41fc-11e7-88eb-87784f90c9a0.png)

**Comment by Tsumiki-Chan** [comment]
Das kann nicht am LSS-Manager liegen, da wir im Prinzip die Karte (noch) nicht anfassen. Schaltet mal den LSS-Manager aus und schaut dann nochmal.

**Comment by Tsumiki-Chan** [comment]
(P.s: Auch nicht reproduzierbar bei mir, auch wenn ich nur die Module aktiv habe, die du auch aktiv hast)

**Comment by FlorianRhausen** [comment]
Okay, Du hast recht, hab Greasemonkey deaktiviert und auf dem Standard-LSS gespielt. Hier entstehen die selben Gitternetzlinien. Dann hab ich nichts gesagt ;-)

**Comment by Tsumiki-Chan** [comment]
Je nachdem ob gewünscht oder nicht einfach mal Sebastian bescheidgeben :)
