### ISSUE TITLE
Heatmap funktioniert nicht richtig

### ISSUE THREAD

**Issue by Bertyocx** [LSS-Manager/lss-manager-v3#481]
Die Heatmap zeigt bei mir nur Kreise um 2 oder weniger Wachen an. Troztdessen, dass bei anderen Wachen die gleiche Anzahl an den gesuchten Fahrzeugen stationiert ist.
Der dazugehörige Screenshot:
![Heatmap](https://user-images.githubusercontent.com/40274220/55641971-7d16be00-57cf-11e9-9470-cd84394a4a85.PNG)
Die 2 Sichtbaren Kreise sind die einzigen auf der Karte, obwohl meine anderen Wachen auch über HLFs verfügen.

Version: Beta 3.3.5
Name: Bertyocx
Chrome: Version 73.0.3683.103 (Offizieller Build) (64-Bit)
Aktive Plugins:
- Fahrzeuge umbenennen
- Wachenstatus
- Heatmap

**Comment by Suchty112** [comment]
#474 ;) ich schließe dann mal

**Comment by Suchty112** [comment]
Könntest du uns deine Wachenanzahl verraten? und vlt dein namen aktualisieren. Ich finde nix zu deinem namen in unseren Daten

**Comment by Bertyocx** [comment]
FW 27
RW 10
Wasserrettungen 3
Polizeiwachen 6
BePos 12
KHs 4
THWs 7
SEGs 19

(Zum Threaderstellungszeitpunkt hatte ich nur 3 SEGs, der Rest ist unverändert)

**Comment by Suchty112** [comment]
Ok, danke für die Infos. dann sind das wenn ich richtig zähle 88 Wachen.

**Comment by Bertyocx** [comment]
Korrekt

**Comment by Suchty112** [comment]
Siehe #511 . Sollte nächste Woche gefixxt sein, bzw. onlien sein :) Damit schließe ich hier shconmal
