### ISSUE TITLE
Erweiterte Gebäudeansicht erweitern

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#484]
> Bei dem einzelnen Script "Erweiterte Wachansicht" wurde bei dem Personal eine Liste angezeigt welche das Personal nach Ausbildungen aufgelistet hat. Kommt so etwas auch noch fürn LSS Manager? Wäre schön weil es die Personalverwaltung doch schön leichter macht.

https://forum.leitstellenspiel.de/index.php?thread/11166-lss-manager-v3/&postID=274707#post274707

**Comment by Suchty112** [comment]
> Das sich im Script von Allure nichts mehr getan hat, bin ich jetzt auch zur "erweiterten Gebäudeansicht" im LSSM gewechselt.
> Die einzige Funktion die mir bei Euch fehlt ist das Umschalten des FMS 2/6 Status mit einem Klick auf das FMS Icon hinter dem Fahrzeug.
> Darf ich mir wünschen das Ihr die Funktion noch mit einbaut?

**Comment by KBOE2** [comment]
Mit 692809b eingebaut :)
