### ISSUE TITLE
App: Missionout

### ISSUE THREAD

**Issue by bckaiser** [LSS-Manager/lss-manager-v3#487]
Wenn man bei den Einsätzen umschaltet zwischen Anzeigen und nicht Anzeigen werden die Fahrzeugnamen auf der Karte ausgeblendet.

**Comment by KBOE2** [comment]
Ich hab diesen Fehler nie gehabt.
Selbst wenn, ist das Problem mit dem heutigen Rewrite des Moduls bestimmt behoben.

Hier erstmal close, sollte das Problem nach dem Update noch auftreten, ein neues Issue eröffnen oder kurze Nachricht an einen Dev, dann wird das hier wieder geöffnet.
