### ISSUE TITLE
Artefakt auf Karte

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#49]
## Fehlermeldung:
Wenn man schnell die Karte mit der Maus verschiebt - dabei aber nicht dauerhaft im Drag&Drop-Modus bleibt, entsteht ein Artefakt auf der Karte:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26485909/25fc6158-41f9-11e7-841c-11d5b3c037dd.png)
Hab dies bisher nur auf Layout4 gehabt - auch die gleiche Vorgehensweise unter Layout1 getestet, hier passiert das nicht.

## Aktivierte Module:
- Layout4
- FMS5 in Karte
- Clock
- MissionOut
- Fahrzeuge umbenennen

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Kann nicht rekonstruiert werden. Wie oft tritt das auf?

**Comment by FlorianRhausen** [comment]
also zur Zeitpunkt der Meldung unter Layout4 konnte ich es mit der beschriebenen Vorgehensweise reproduzieren, wenn ich es aktuell nochmal Versuche macht er es aber bei mir auch nicht mehr.

**Comment by Tsumiki-Chan** [comment]
Wir haben seitdem kein Update rausgehauen. Wir schauen später mal.
