### ISSUE TITLE
Verbandseinsätze einzeln auflisten. SumDailyMissions

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#492]
> Ich möchte ja nicht unverschämt sein, aber ist es möglich die "Verbandseinsätze" jetzt in der Tagesansicht einzeln auszuwerten? Die sind doch jetzt extra markiert. 😇

https://forum.leitstellenspiel.de/index.php?thread/11166-lss-manager-v3/&postID=279119#post279119

**Comment by KokosnussDEV** [comment]
Versteh ich nicht, kann mir das mal wer erläutern?

**Comment by Suchty112** [comment]
Sollte mit dem morgigen Update für den Großteil der Länder umgesetzt sein

**Comment by Suchty112** [comment]
#657 damit nun online
