### ISSUE TITLE
Statistik leer und über der Karte

### ISSUE THREAD

**Issue by OiledAmoeba** [LSS-Manager/lss-manager-v3#5]
## Fehlermeldung:
Wenn ich die Statistik aktiviere, erhalte ich leere Container (Überschriften sind da). Diese werden zudem oberhalb des restlichen Content angezeigt. Aber: Die Navigationsbuttons des LSS-Managers bleiben oben!

## Aktivierte Module:
- 

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Browser: 
Google Chrome
#### Version: 
58.0.3029.110 (64-bit)
#### Beta Version: 
0.1

**Comment by lostdesign** [comment]
Die ist noch nicht fertig :D & eine der beiden hat einen Fehler. Wir sind dran - danke.

**Comment by lostdesign** [comment]
Fixed.
