### ISSUE TITLE
Dashboard überlappt ein wenig

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#50]
## Fehlermeldung:
beim aktivieren des Dashboards gibt es eine kleine Überschneidung mit Layout 1
![grafik](https://cloud.githubusercontent.com/assets/28895574/26486012/a27f38ea-41f9-11e7-9f96-5325df385b42.png)

## Aktivierte Module:
- Layout1
- Dashboard
- FMS5inKarte
- Clock
-Fahrzeugeumbenennen

## Mögliche Lösung / Verbesserungsvorschlag:
- Den Bereich "geplantes" ganz rausnehmen, Informationen diesbezüglich in den AppStore verlagern.

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Geplantes bleibt drinnen dort kommt nur ein anderer Inhalt rein. Die 5px werden gefixt.
