### ISSUE TITLE
3.3.5 Stable: Wachenstatus - keine alphabetische Sortierung mehr

### ISSUE THREAD

**Issue by dome9921** [LSS-Manager/lss-manager-v3#500]
Bis zur Version 3.3.3 wurden in der Karte im Wachenstatus die Fahrzeuge alphabetisch sortiert angezeigt. Dies ist nun nicht mehr möglich. Würde mich freuen wenn der Fehler behoben wird.
![grafik](https://user-images.githubusercontent.com/51700332/59260730-6c098380-8c3c-11e9-8c93-3960cf7c9665.png)

Meine Daten:
Version: Stable 3.3.5
Name: dome9921
Browser: Firefox 67.0.1 (64-Bit)

**Comment by KBOE2** [comment]
Mit 22b1b1f aufgenommen, wird dann beim nächsten Update dabei sein.
