### ISSUE TITLE
LS-HEATMAP Fehler 

### ISSUE THREAD

**Issue by simon12211** [LSS-Manager/lss-manager-v3#505]
Servus,
Hätte einen Fehler bei der LS-HEATMAP beim Layout 1 
Er zeigt einfach nichts an.
![Feher LSS](https://user-images.githubusercontent.com/51846882/59548051-674d1400-8f49-11e9-9c1c-b063a2afd445.PNG)
Browser ist Firefox 

Grüße Simon122

**Comment by KBOE2** [comment]
Leute, schaut doch bitte bitte bitte endlich mal in die anderen Issies oder im Forum, ob ein Fehler gemeldet wurde, was is daran so schwer???!!!
Siehe #481 🙄
