### ISSUE TITLE
Suchfunktion geht nicht mehr

### ISSUE THREAD

**Issue by fux714** [LSS-Manager/lss-manager-v3#507]
Leider geht seit dem vom Entwickler die Suchfunktion ins Spiel integriet, ist die Suchfunktion vom LSS-Manager nicht mehr Verfügbar.
Ich bitte um behebung

**Comment by KBOE2** [comment]
Welche Suchfunktion meinst du?
AAO-Suche?
Einsatzsuche?

**Comment by Suchty112** [comment]
Du meinst die AAO-Suche? Joa die haben wir vorerst ausgebaut, aber da sie sich viele zurückgewünscht haben, wird sie in den nächsten Wochen bei einen der Updates wieder hinzugefügt :)

**Comment by fux714** [comment]
Danke dafür


Tobias <notifications@github.com> schrieb am Mo., 17. Juni 2019, 15:34:

**Comment by KBOE2** [comment]
Dann close ich mal
