### ISSUE TITLE
Vorschlag: Dashboard Wachen

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#52]
## Vorschlag

Die Fenster pro Wache um Funktionen ergänzen:
Derzeitiger Stand:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26486197/5fafe900-41fa-11e7-8f14-91d75e63ce76.png)

Möglichkeiten zur Verbesserung:
![dashboardwache](https://cloud.githubusercontent.com/assets/28895574/26486307/ccbb13d0-41fa-11e7-95a1-78db824f528d.PNG)
 Minimieren/Ausklappen-Button, der Status aus dem Hauptfenster in die Kopfleite, damit er sichtbar bleibt.
Anordnung der Fahrzeuge im Hauptfenster 2-spaltig.

**Comment by lostdesign** [comment]
Minimieren ausklappen find ich super. Das Design in der Wachenübersicht ändert sich aber noch komplett. Wenns geht wirds 2 Spaltig.

**Comment by FlorianRhausen** [comment]
Da hätte ich noch eine kleine Verbesserung für ein Designvorschlag:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26538550/d4c1fa72-4447-11e7-888d-8820c754383d.png)

Wie bisher (wobei ich jetz die Buttons nicht reinhab) aber unten in der Leiste noch eine kurze Übersicht wieviele Ausbildungen vorliegen (sofern das Auslesen überhaupt möglich ist) 

Theoretisch könnte man auch im Fahrzeugmarkt so was einbauen, das zum jeweiligen Fahrzeug angezeigt wird, wieviele Ausgebildete Personen überhaupt vorhanden sind (ungebunden wäre noch schicker).

**Comment by lostdesign** [comment]
Glaub nicht, dass das möglich ist - mal schauen.

**Comment by FlorianRhausen** [comment]
ist ja auch nur ein Vorschlag - anbei jetzt das richtige Bild, hoff ich :D 
![wachen](https://cloud.githubusercontent.com/assets/28895574/26539153/38a826b2-444b-11e7-8196-6a6937b33adf.PNG)
