### ISSUE TITLE
Mission helper

### ISSUE THREAD

**Issue by ndmdesign** [LSS-Manager/lss-manager-v3#520]
the Mission help on the side is very intimitent. It wiill either show the actual thing or it will show your html/php coding 

![f1f4b4904b85f157b0c870e20192df35](https://user-images.githubusercontent.com/44583238/62776096-81b2f200-baa1-11e9-8c66-49f76a0906f0.png)

**Comment by KBOE2** [comment]
The first time, a mission of a specific type appears, it is registered and written in our file.
With the time all the mission types will be added and this view won't come up anymore.
