### ISSUE TITLE
Ambulance only jobs in mission helper

### ISSUE THREAD

**Issue by ndmdesign** [LSS-Manager/lss-manager-v3#521]
Sorry to be a pain, i just like to see a working system :)

The ambulance only jobs dont show up that they require an ambulance they only show the need for transport. 

Not sure if bug or not but thought i would post to make you aware.

**Comment by ndmdesign** [comment]
![b2150afa82ad62a86264a805aa071f5b](https://user-images.githubusercontent.com/44583238/62776536-bbd0c380-baa2-11e9-8c0d-5ffeda91605d.png)

**Comment by KBOE2** [comment]
Yeah. Why should we add that the need an ambulance?
In my eyes it is clear that a patient needs an Ambulance. ^^

**Comment by ndmdesign** [comment]
oh trust me i know but we have to think of the new players. I work for the ambulance service so i know when a PT would need a truck haha but others may not

**Comment by KBOE2** [comment]
Well we can think about adding a hint that an ambulance is needed.

**Comment by KBOE2** [comment]
Included with 1e1c5e8
