### ISSUE TITLE
unknown wording

### ISSUE THREAD

**Issue by ndmdesign** [LSS-Manager/lss-manager-v3#522]
Morning All. 

Can you help.

Not sure what the two requirements at the bottom of the list are.

![d30e0a46fc9971dc516d12df804dc542](https://user-images.githubusercontent.com/44583238/62932774-b8964a00-bdb8-11e9-97be-33b8ae1ca59a.png)

**Comment by KBOE2** [comment]
This is a german thing that sould not be shown in english Version. I will take that out asap.

**Comment by KBOE2** [comment]
Fixed with 6d5199b
should be public with next update.
