### ISSUE TITLE
Falsche Angaben bei einigen NL Missionen

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#529]
Bei einigen Missionen wird die DLK aka Redvortuig aka Hoogwerker falsch angezeigt 
ID 54, 454, 67, 61
BRAND IN SPORTHAL
Kat op Dak
Omgewaaide bouwsteiger
Brand in slaapkamer

**Comment by KBOE2** [comment]
Fixed with 749db44
