### ISSUE TITLE
Vorschlag: Anzahl der Wachen

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#54]
## Vorschlag

![grafik](https://cloud.githubusercontent.com/assets/28895574/26486606/184eaa68-41fc-11e7-9bea-515ec3120715.png)

Bei der Übersicht werden 19 Wachen angezeigt, dies ergibt sich durch 14 Rettungswachen und 5 SEG-Wachen. Die SEG-Wachen sind aber im Dashboard unter "Sonstiges" geführt.

Vorschlag:
Entweder die SEG-Wachen zu den Rettungswachen dazu nehmen, oder in der Übersicht die SEG-Wachen auf die zweite Spalte "sonstige Gebäude" schieben.

**Comment by lostdesign** [comment]
Das Dashboard ist aus der zeit in der es weder SEG noch Wasserrettung gab - wird noch als eigener Balken hinzugefügt.
