### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by SilentSto** [LSS-Manager/lss-manager-v3#545]
Hey hey, Wie sieht es aus mit der Möglichkeit einer Mobilen Version?

MfG SilentSto

**Comment by KBOE2** [comment]
Wenn du die Zeit, Lust und Geduld hast, darfst du das gerne machen.
Für die App ist es sowieso nicht wirklich möglich, im Browser funktionieren manche Funktionen ein wenig.
