### ISSUE TITLE
Wrong value of credits. "Personen onwel door hitte"

### ISSUE THREAD

**Issue by Piet2001** [LSS-Manager/lss-manager-v3#547]
In the missionhelper is viewed 450 and that should be 1100

**Comment by Piet2001** [comment]
https://cdn.discordapp.com/attachments/607912398237466624/631028381483401216/unknown.png

https://cdn.discordapp.com/attachments/506509256359542787/631027613103554565/Aantekening_2019-10-08_091804.png

**Comment by Suchty112** [comment]
Vielen Dank für den Fehler. Da wurde wohl nachträglich seitens des Entwickler Teams was geändert. Zu Spätestens Freitag, sollte der Fehler behoben sein.

Hartelijk dank voor de vergissing. Het ontwikkelaarsteam heeft waarschijnlijk iets veranderd na de bug. Uiterlijk op vrijdag zou de bug verholpen moeten zijn.

Thank you so much for the mistake. The developer team probably changed something after the bug. By Friday at the latest, the bug should be fixed.

**Comment by Piet2001** [comment]
First it was 450 but it has changed in the game at aug 30th.
So I thing LSSM has not taking over the changing. 
But thanks that you will fix it.

**Comment by Suchty112** [comment]
is fixed with https://github.com/LSS-Manager/lss-manager-v3/commit/e37515b119dcfae27fd479c316f56eac19766ff3

**Comment by Piet2001** [comment]
Now I see that also the values of the MMT incorrect is.

**Comment by Suchty112** [comment]
> By Friday at the latest, the bug should be fixed.

 look here https://github.com/LSS-Manager/lss-manager-v3/commit/e37515b119dcfae27fd479c316f56eac19766ff3#diff-255e350a56e4ccbee256714525488fdfR8054

**Comment by Piet2001** [comment]
Oke. Thanks. I haven't see that. Next time I will dubble check the code.
