### ISSUE TITLE
Layout01 mit neuem Menü

### ISSUE THREAD

**Issue by Tsumiki-Chan** [LSS-Manager/lss-manager-v3#55]
Wenn man das Layout01 aktiviert, dann buggt das Menü vom LSS-Manager ein bisschen rum.

![mirko git gud & use markdown](http://i.imgur.com/1FMJJEL.png)

**Comment by FlorianRhausen** [comment]
Verhalten kann ich bestätigen - dachte es wäre so gewollt ;-)

**Comment by Tsumiki-Chan** [comment]
@FlorianRhausen Ne, ist nicht so gedacht. Da hab ich gestern zu wenig getestet, als ich das neue Menü eingebaut habe :)

**Comment by lostdesign** [comment]
fixed.
