### ISSUE TITLE
Anzeigefehler im LAYOUT 04

### ISSUE THREAD

**Issue by nairolfff** [LSS-Manager/lss-manager-v3#56]
Fehlermeldung: Anzeigefehler bei Verbandsevent

![asdf](http://i.imgur.com/RIqeosU.png)

Aktivierte Module:

LAYOUT 04
NOTIFICATION ALERT
MISSIONOUT
EINSÄTZE FREIGEBEN
EINSÄTZE SUCHEN

Mögliche Lösung / Verbesserungsvorschlag:

...

Browser: Opera

Version: 45.0.2552.812

Beta Version: beta0.1

**Comment by lostdesign** [comment]
Dauert etwas bis ich das nach stellen kann - dafür brauch ich halt ein Event :D

**Comment by nairolfff** [comment]
Sonntag Nachmittag/Abend wäre wieder Event bei uns.
Weiß ja nicht ob dir das zeitlich passt :D

**Comment by lostdesign** [comment]
fixed

**Comment by nairolfff** [comment]
![fehler_event2](https://cloud.githubusercontent.com/assets/28982070/26763792/0053a674-495a-11e7-9ea6-cb2dacd68ac5.PNG)

Schaut schon besser aus, ist aber immer noch nicht optimal.

**Comment by lostdesign** [comment]
Ich werde die Meldungen gleich unter der Navigation anzeigen lassen. Ist wohl die beste Lösung.
