### ISSUE TITLE
Fehlermeldung beim Umbenennen der Fahrzeuge

### ISSUE THREAD

**Issue by Topix1** [LSS-Manager/lss-manager-v3#568]
Ich habe gerade mehrere Wachen gebaut und die Fahrzeuge mit dem Script umbenannt. Bei der ersten Wache klappt es und bei der nächsten kommt jeweils eine Fehlermeldung. Erst wenn ich das Spiel resette, kann ich die nächste Wache bearbeiten und die Fahrzeuge mit dem Script umbenennen.
Ich habe ein Screenshot gemacht und versuche gleich mal, das hier einzufügen.

![Fehler](https://user-images.githubusercontent.com/19910622/68277874-70fa2400-0070-11ea-8aee-43fd226bedf6.JPG)

**Comment by KBOE2** [comment]
Jau, das System braucht nach dem Bau/Kauf eines Gebäudes/Fahrzeuges bis zu 5 Minuten um das zu registrieren. Ein Seiten-Reload hilft hier aus, für alle, die nicht warten möchten.
=> Kein Fehler, nur ein Schutz extremer Belastung der API.
