### ISSUE TITLE
"Absenden" Button für eine Rückmeldung ist grau

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#57]
Fehlermeldung:
Der Absenden Button für eine Rückmeldung ist hellgrau und man erkennt "Absenden" nur sehr schlecht.

Aktivierte Module:

MissionOut
Einsätze freigeben
Einsätze suchen
Dashboard
fahrzeuge umbennen
Show Back Alarm Above

Browser: Chrome
Version:Version 58.0.3029.96 (64-bit)
Beta Version: 0,1

**Comment by DLRG-Dominik** [comment]
kein Layout aktiviert?

**Comment by brennerr** [comment]
Bin unentschieden und teste viel aus

**Comment by DLRG-Dominik** [comment]
ok, frage falsch angekommen. welches hast du zu dem zeitpunkt an?

**Comment by brennerr** [comment]
Kam richtig an aber ich hab gedacht meine Antwort ergibt sich daraus ^^
Zum Zeitpunkt hatte ich kein Layout an

**Comment by lostdesign** [comment]
Duplikat #12
