### ISSUE TITLE
Vorschlag: Gruppierung von Fahrzeugklassen bei der Heatmap

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#58]
Würde es durchaus für gut befinden, wenn man bei der Heatmap bestimmte Gruppen von Fahrzeugen zusammenfassen könnte. Der SW bsp. findet sich in vier vers. Formen wieder und so ist es schwer zu prüfen wo denn noch welche fehlen wenn man unterschiedliche SW baut.

Bei den LF höchstens zwischen LF und HLF aber das ist optional würde ich sagen.

**Comment by MrWeezle** [comment]
Auch die Abrollbehölter dann in die entsprechende Gruppe mit aufnehmen.

**Comment by jalibu** [comment]
In der aktuellen Version (für den LSS-Manager AppStore) habe ich folgende Fahrzeug-Gruppen eingefügt:

- Löschfahrzeuge
- Tanklöschfahrzeuge
- Schlauchwagen
- Öl (GW + AB)
- Dekon-P (GW + AB)
- Rüstwagen (RW + AB)
- Atemschutz (GW + AB)
- ELW 1+2

Habe ich etwas vergessen? Gibt es weitere Wünsche/Vorschläge?

**Comment by brennerr** [comment]
Die Standarteinstellung des Radius, hat die einen Hintergrund oder ist die zufällig so festgelegt? Könnte man die nicht standartmäßig auf den Radius stellen, in denen um eine Wache Einsätze auftreten?
So könnte man ja noch besser prüfen ob noch Fahrzeuge gebraucht werden an einem Standort. Ist das verständlich was ich meine?
