### ISSUE TITLE
Wachenplanung überdeckt FMS 5

### ISSUE THREAD

**Issue by OiledAmoeba** [LSS-Manager/lss-manager-v3#6]
## Fehlermeldung:
Wenn ich die Wachenplanung **und** FMS5-in-Karte aktiviert habe, liegt die Planung über den FMS5. Da die Planung nicht verschoben werden kann, ist der FMS5 in vielen Fällen nicht mehr klickbar.

## Aktivierte Module:
- 

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Browser: 
Google Chrome
#### Version: 
58.0.3029.110 (64-bit)
#### Beta Version: 
0.1

**Comment by lostdesign** [comment]
fixed
