### ISSUE TITLE
Vorschlag: Nach Datum suchen

### ISSUE THREAD

**Issue by nairolfff** [LSS-Manager/lss-manager-v3#60]
Servus,
Hatte diesen Vorschlag dem @lostdesign schon einmal geschrieben, möchte das nur hier mal Vorschlagen.

Meine Idee wäre die Einsätze auch nach Datum zu suchen bzw. sortieren.
Wäre eine riesige Erleichterung am Abend die ganze Verbandsfreigaben zu beenden.

**Comment by Thomas21030** [comment]
Das wäre ein Traum, besondersbei über 300 VB Einsätze alles alte vom  vor Tag direkt zusammen zuhaben fertig  abarbeiten können;-)

**Comment by KBOE2** [comment]
Ist mal zu #537 zusammengefasst
