### ISSUE TITLE
Initalisierung im Forum,Toplist usw

### ISSUE THREAD

**Issue by nairolfff** [LSS-Manager/lss-manager-v3#61]
Fehlermeldung:  Wenn man das Verbandsforum, die Toplist und ähnliches aufruft kommt immer wieder die Initialisierung des NOTIFICATION ALERT.
Ich denke nicht, dass das gewollt ist.

http://imgur.com/a/mUqFc

Aktivierte Module:

LAYOUT 04
NOTIFICATION ALERT
MISSIONOUT
EINSÄTZE FREIGEBEN
EINSÄTZE SUCHEN

Mögliche Lösung / Verbesserungsvorschlag:

...

Browser: Opera

Version: 45.0.2552.881

Beta Version: beta0.1

**Comment by Tsumiki-Chan** [comment]
Hallo,
nein, das ist nicht so gedacht. Solange das nicht in den Einsätzen passiert weiß ich auch wo der fehler liegt.

Vielen dank für's melden. 😄
