### ISSUE TITLE
Anzeigefehler bei Redesign

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#62]
## Fehlermeldung:
Bei aktivierten Redesign wird das rechte Menü versetzt angezeigt und die Karte "klebt" am linken Rand
![image](https://cloud.githubusercontent.com/assets/6639017/26531249/986afb58-43e5-11e7-92de-abad00d856c6.png)

![image](https://cloud.githubusercontent.com/assets/6639017/26531259/cd5c7364-43e5-11e7-8ccb-7bf65990d86b.png)

## Aktivierte Module:
- LAYOUT 01 v1.1
- MISSIONOUT 
- EIGENE VGE SPEICHERN
- REDESIGN 01 alpha-0.1
- FMS 5 IN DER KARTE
- CLOCK
- EINSÄTZE FREIGEBEN
- EINSÄTZE SUCHEN
- DASHBOARD
- FAHRZEUGE UMBENNENEN
- SHOW BACK ALARM ABOVE

#### Bildschirm: 15,6" 1366x768 Pixel

**Comment by lostdesign** [comment]
redesign wird neu geschrieben

**Comment by MrWeezle** [comment]
Fehler kommt auch ohne aktiviertes Redesign
