### ISSUE TITLE
WR Wachen anzahl 

### ISSUE THREAD

**Issue by JonasKilian** [LSS-Manager/lss-manager-v3#63]
## Fehlermeldung:
Im Dashboard werden mir 7 WR wache angezeigt obwohl ich nur 2 Habe 
## Aktivierte Module:
-Dashboard

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Siehe Chat - hab ich gerade eben gesagt, arbeite gerade aktiv daran :D

**Comment by JonasKilian** [comment]
Bin nicht so schnell im Lesen
