### ISSUE TITLE
Modul: Show Back Alarm above

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#64]
## Fehlermeldung:
Wenn ich das o. g. Modul aktiviere, ist der Rückalarmierungsbutton weiterhin unten

## Aktivierte Module:
- Layout01
- FMS5 in Karte
- Clock
- Dashboard
- Fahrzeug umbenennen
- Einsätze freigeben
- Einsätze suchen
- MissionOut

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: 0.1

**Comment by Mausmajor** [comment]
Sollte im nächsten update gefixt sein. Sonnst bitte nochmal ein issue auf machen
