### ISSUE TITLE
Renaming vehicles

### ISSUE THREAD

**Issue by larssieboy18** [LSS-Manager/lss-manager-v3#644]
Hi,

Whenever I try to rename vehicles, it gives me the following error:
![image](https://user-images.githubusercontent.com/9215689/76656189-5af4f680-656f-11ea-902d-929c2eadda61.png)

Is there any way to work around this and/or fix this? If you need any more information please let me know!

Best regards,
Lars

**Comment by KBOE2** [comment]
Please reload the page. This Error occurs when you try to rename a vehicle before the manager has recognized it. That usually happens up to 5 minutes after you bought it. 5 Minutes or reloading the game bot helps.
