### ISSUE TITLE
The text in my credit expansion is a different language to english and i can reset it

### ISSUE THREAD

**Issue by BenDrysdale2019** [LSS-Manager/lss-manager-v3#655]
I can't understand the text in the game due to it being a different language and this only works only when the credit expansion is on and i can change the language.

**Comment by KBOE2** [comment]
Could you please try to reload the page a few times with ctrl+F5 and report wether it is still not correct.

**Comment by Suchty112** [comment]
oh sry, i found the mistake. is fixxed in few minutes

**Comment by Suchty112** [comment]
> Could you please try to reload the page a few times with ctrl+F5 and report wether it is still not correct.

Please do that, and you should be fine.
