### ISSUE TITLE
Bug bei Einstellungen - Notification-Alarm

### ISSUE THREAD

**Issue by AdvocatusDei** [LSS-Manager/lss-manager-v3#66]
Ich habe soeben einen Bug entdeckt.

Ich kann "Chatnachrichten als Info-Popup" nicht abschalten. der Regler geht nicht nach links.

![](https://picload.org/image/riorliar/alert.png)

Layout 1
Missionout
Eigene VGE´s speichern
FMS 5 in Karte
Clock
Notification-Alert
Einsätze freigeben
Einsätze suchen
Alarmmaken Steurung 
Dashboard

Browser Chrome Version 58.0.3029.110 (64-bit)

Bug besteht nach Update auf LLS Manager V3 3.1.7 weiter

**Comment by Tsumiki-Chan** [comment]
Die Checkbox hat einen HTML-Fehler.
Ich kann den aber grad nicht fixen weil ich schon praktisch den PC aus habe.
![HTMl-Fehler](http://i.imgur.com/m5xQZ2P.png)

**Comment by DLRG-Dominik** [comment]
Wurde anscheinend schon gefixt und nicht geschlossen, jedenfalls ist der Fehler nicht in der Entwicklerversion drin.
