### ISSUE TITLE
FMS5 NEF Nachforderung wenn NEF auf Anfahrt

### ISSUE THREAD

**Issue by Mrvn9** [LSS-Manager/lss-manager-v3#676]
Wird bei einem Einsatz ein NEF nachgefordert, wird im Funk ein Nachforderungssprechfunk angezeigt, selbst wenn bereits ein NEF auf Anfahrt zum Einsatz ist. Gleiches gilt für LNA und OrgL.

**Comment by KBOE2** [comment]
Das liegt daran, dass wir ohne Serveranfragen nicht mit absoluter Sicherheit  feststellen können, ob bereits ein entsprechendes Fahrzeug auf Anfahrt ist.
Stell dir einfach vor, es ist wie im realen Leben: Das LF z.B. oder der RTW kommt am Patienten an, ohne zu wissen, was alles mit alarmiert wurde. Jetzt gibt er an die Leitstelle durch "Jo, wir brauchen nen NEF". Leitstelle sagt dann "Klaro, is bereits unterwegs, aber danke".
😉


Ich schließe mal hier, da das kein so wirklich lösbares Problem ist.
