### ISSUE TITLE
LSS wird nicht automatisch neu geladen

### ISSUE THREAD

**Issue by brennerr** [LSS-Manager/lss-manager-v3#68]
## Fehlermeldung:
Wenn man im AppStore ein Modul einschaltet und zu LSS zurückkehrt läd das Spiel ja automatisch neu. Wenn ich jedoch die unten genannten Module anhabe und dann lediglich noch das Layout 1 bis 4 aktiviere (also alle einzelt natürlich) , läd das LSS nicht neu sobald ich auf zurück drücke.

Ich weiß nicht ob das damit zusammen oder das so soll: 
Das Redesign ist ebenfalls "tot", egal ob ich es aktiviert habe oder nicht sehe ich es im LSS.

## Aktivierte Module:
- Missionout
- Einsätze suchen
- Einsätze freigeben
- Dashboard
- Fahrzeuge umbennen
- Show back alarm above
(- Layout 1-4)

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: 0.1

**Comment by lostdesign** [comment]
Es ist gewollt das nicht immer neu geladen wird - da es nicht immer zwingend nötig ist. Für das Redesign ein neues Issue aufmachen.
