### ISSUE TITLE
dashboard wrong language

### ISSUE THREAD

**Issue by Genovese78** [LSS-Manager/lss-manager-v3#689]
the file  /modules/lss-dashboard/dashboard.html

in the section
Fahrzeugaufteilung

show categories in wrong language (german instead of local language)

![lss-dashboard](https://user-images.githubusercontent.com/64377631/81750857-9730ce80-94ae-11ea-905a-15a8276e1ab9.png)

**Comment by Suchty112** [comment]
Unfortunately this is hardcoded in the html file.
But we will make it better for the next version (v4).
https://github.com/LSS-Manager/lss-manager-v3/blob/dev/modules/lss-dashboard/dashboard.html#L95
