### ISSUE TITLE
 Layout 4 in der Enge

### ISSUE THREAD

**Issue by Thomas21030** [LSS-Manager/lss-manager-v3#69]
## Fehlermeldung:
Das Layout 4 wird mir durchgehen so angezeigt
![layout4](https://cloud.githubusercontent.com/assets/28989752/26562678/cbe64292-44c8-11e7-8111-7b941d2caa70.JPG)

## Aktivierte Module:
-LAYOUT 04
NOTIFICATION ALERT
EINSÄTZE FREIGEBEN

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: ... 3.1.7

**Comment by Tsumiki-Chan** [comment]
@lostdesign Ist es so schwer die Verband-Buttons so zu bauen, dass sie nicht die divs beschränken? 🗡

**Comment by lostdesign** [comment]
@Thomas21030 ist das in der Beta 3.1.8 immernoch?

**Comment by lostdesign** [comment]
Behoben im nächsten Update.

**Comment by Thomas21030** [comment]
Ja würde sagen das ist immer noch so

![layout4neu](https://cloud.githubusercontent.com/assets/28989752/26681270/cf2eaf1e-46dc-11e7-8b58-e011cf78bf91.JPG)

**Comment by lostdesign** [comment]
*Behoben im nächsten Update* == 3.1.9
