### ISSUE TITLE
Reset AAO-Zähler button wrong language

### ISSUE THREAD

**Issue by Genovese78** [LSS-Manager/lss-manager-v3#690]
the button "Reset AAO-Zähler" in /modules/lss-AAO-Zaehler/aao-zaehler.js

use wrong language (german instead of local language)

![bottone_aao](https://user-images.githubusercontent.com/64377631/81751755-5639b980-94b0-11ea-870e-f548bbb0b7be.png)

**Comment by Suchty112** [comment]
There I will see if we can get translations for the countries :)

**Comment by Suchty112** [comment]
Is added with tomorrow's update.
https://github.com/LSS-Manager/lss-manager-v3/commit/bfce9c7078b850ad21c747b7f45988d3fdcc77d2
