### ISSUE TITLE
button Reset AAO-Zähler not working

### ISSUE THREAD

**Issue by Genovese78** [LSS-Manager/lss-manager-v3#691]
the button Reset AAO-Zähler reset the counter on AAO but not veichle selection

**Comment by KBOE2** [comment]
It isn't designed to reset the vehicle selection.
Vehicle selection reset is possible with an AAR (Alarm and Response Regulation) with the tick "Reset vehicle selection" set.
Maybe, we will ad an extra button in the next major version.
