### ISSUE TITLE
Suggestion: Countdown in incident overview

### ISSUE THREAD

**Issue by BattalionChiefBoden** [LSS-Manager/lss-manager-v3#692]
I would really like to have a countdown in the incident overview, that for running missions tells me how long for them to complete, so I don't have to open them one by one to see the time until completion. Attached is an example how I would love to see the TimeToCompletion:
![image](https://user-images.githubusercontent.com/65354552/81950302-0ec44200-9604-11ea-8bda-b3f3bfe93c8c.png)

**Comment by KBOE2** [comment]
There is already a standalone Script for that available in the german Forum: https://forum.leitstellenspiel.de/index.php?thread/13913-script-einsatzdauer-in-der-einsatzliste/
But we're planning to also add this in here or in the V.4 of LSSM.

**Comment by Piet2001** [comment]
Is this also now availible for the dutch version? Or does other versions have to wait for V.4

**Comment by BattalionChiefBoden** [comment]
> There is already a standalone Script for that available in the german Forum: https://forum.leitstellenspiel.de/index.php?thread/13913-script-einsatzdauer-in-der-einsatzliste/
> But we're planning to also add this in here or in the V.4 of LSSM.

Thank you. I will certainly check that.

**Comment by KBOE2** [comment]
> Is this also now availible for the dutch version? Or does other versions have to wait for V.4

I will Update the Script in a minute to support all the other versions.

**Comment by KBOE2** [comment]
> > Is this also now availible for the dutch version? Or does other versions have to wait for V.4
> 
> I will Update the Script in a minute to support all the other versions.

Version 1.0.3 makes it available for all versions (hopefully). Any further stuff to the "Einsatzdauer"-Script directly please in https://github.com/KBOE2/LSS-Scripts/issues or on the german forum.

**Comment by BattalionChiefBoden** [comment]
Super! I got it partially working by adding the url to the settings, but official support is more awesome!
![image](https://user-images.githubusercontent.com/65354552/81955263-29011e80-960a-11ea-940c-ae5a4b9da65a.png)
