### ISSUE TITLE
lssm.modules_sumDailyMissions do not sum

### ISSUE THREAD

**Issue by Genovese78** [LSS-Manager/lss-manager-v3#696]
at least, in italian, the sum doesn't work

![dailySum](https://user-images.githubusercontent.com/64377631/82131004-de7dce80-97d0-11ea-9655-b40f9090084f.png)

**Comment by Suchty112** [comment]
@Genovese78 What exactly is not working? The somma i prigionieri or something else?

**Comment by Genovese78** [comment]
don't sum patients and prisoners

in this example, on the third line, i have treated 5 patients

![patients](https://user-images.githubusercontent.com/64377631/85335768-d4d93c00-b4dd-11ea-8581-9d5df8f770d7.png)

**Comment by Suchty112** [comment]
Thanks again for the screenshot. I need the same text in the overview for the Prisoner. I already looked in the Facebook group, but there was no screenshot/image with this text

**Comment by Genovese78** [comment]
the fourth line is treatment and transport of patients

**Comment by Suchty112** [comment]
i need the text for the PRISONER not the Patients

**Comment by Genovese78** [comment]
I know, it was just a clarification
wait a few minutes, I'm arresting people right in these minutes: D

**Comment by Genovese78** [comment]
2 prisoners... :)

![detenuto2](https://user-images.githubusercontent.com/64377631/85338527-b75aa100-b4e2-11ea-95a0-fee4ff20249e.png)

**Comment by Suchty112** [comment]
Ok Should be fixed then with the update what probably comes tomorrow (23.6). I'm still trying a little bit with the script :D , but it is entered

**Comment by Genovese78** [comment]
ok thankyou :)
