### ISSUE TITLE
FMS5 Anordnung in Layout 1 und Layout 2 nicht korrekt

### ISSUE THREAD

**Issue by MrNobody92** [LSS-Manager/lss-manager-v3#7]
Wenn ich die Funksprüche anklicke, dann sind sie nicht oben links bündig nach unten sortiert, sondern von unten links nach oben.

## Aktivierte Module:
- 

## Mögliche Lösung / Verbesserungsvorschlag:
-

#### Beta Version: v1.1

**Comment by lostdesign** [comment]
Kannst du dazu noch ein Bild posten? Wo passiert das?

**Comment by Chris4135** [comment]
Wenn wir hier bei FMS5 sind, ich habe das Problem seit ich den S5 auf der Karte wieder deaktiviert habe ist er jetzt ganz unten mitten in den Funksprüchen. 

![imag1792](https://cloud.githubusercontent.com/assets/28855338/26347032/69e96e36-3fa8-11e7-8c18-9d7e8de2ed3c.jpg)

**Comment by MrNobody92** [comment]
Screenshot folgt nachher

**Comment by FlorianRhausen** [comment]
Das Problem taucht auch auf, wenn man kein Layout geladen hat (also ganz ohne Apps), also auf dem Standard spielt. Wenn man die FMS5 in die Karte integriert, ist das Problem gelöst.

**Comment by lostdesign** [comment]
Wir schauen die FMS5 mal an - scheinen doch mehrere Probleme zu machen. Liegt aber wahrscheinlich am CSS.

**Comment by FlorianRhausen** [comment]
![grafik](https://cloud.githubusercontent.com/assets/28895574/26354420/c1e5444a-3fc4-11e7-8e91-9cd48c04cf1e.png)
Wenn ich die FMS5-in Karte ausmache, sieht es so aus wie bei Chris. Aktiviere ich das Modul, sehen die FMS5 ganz normal aus. Also auch der Abstand stimmt dann.
![grafik](https://cloud.githubusercontent.com/assets/28895574/26354480/f0d2de7a-3fc4-11e7-946e-ea91098488f4.png)

**Comment by MrNobody92** [comment]
![fehler-fms5](https://cloud.githubusercontent.com/assets/28884935/26366614/0ab98a56-3fec-11e7-84ac-fe44f04ccef1.PNG)

Module: Uhrzeit, Tastaturalarmierung, Wachenplanung und Layout 1

**Comment by MrNobody92** [comment]
![fms5](https://cloud.githubusercontent.com/assets/28884935/26367400/bc380760-3fee-11e7-9b49-4256143d96dd.PNG)

**Comment by lostdesign** [comment]
Fixed.
