### ISSUE TITLE
Vorschlag: Autonachricht im Verbandschat bei Freigabe

### ISSUE THREAD

**Issue by AdvocatusDei** [LSS-Manager/lss-manager-v3#70]
Hallo ihr Lieben,

MrNobody92 und ich hätten folgenden Vorschlag

Sobald man in der Einsatzliste den Button für Verband freigeben betätigt, dass automatisch eine Nachricht im Verbandschat mit Glocke erscheint mit dem Einsatznamen und dem Ort.

Vielleicht zusätzlich mit der Option. Mitverdienen 1 LF schicken. Oder Mitverdienen egal was hinschicken.

Was haltet Ihr davon. 

LG

MrNobody92 und Advo

**Comment by FlorianRhausen** [comment]
ergänzend würde ich sagen, das man einen Text selbst definieren kann.

**Comment by lostdesign** [comment]
Geplant ist, das man in der Einsatzliste nach Freigabe den RMS Input bekommt. Sollte doch passen oder? Von mir aus könnte man noch einen beliebigen Standard Text definieren.

**Comment by AdvocatusDei** [comment]
Jap Lost, das währe mal super, dann kann jeder seinen eigenen standart eintragen, der dann immer kommt.

bei uns im Verband ists immer: 

Mitverdienen, 1 LF oder 1 FuStwa.

Daumen hoch!

**Comment by KBOE2** [comment]
Ist mal zu #537 zusammengefasst
