### ISSUE TITLE
ShareAlliancePost Error data.credits

### ISSUE THREAD

**Issue by JRH-1997** [LSS-Manager/lss-manager-v3#703]
In the ShareAlliancePost Script is there an error in the console about the data.credit is undefined. 

The error occurs at missions where there are only ambulances needed, because there are no credits defined for that mission. 
![afbeelding](https://user-images.githubusercontent.com/65117490/82753293-d6bbbc80-9dc4-11ea-91be-fc7fda7db0f1.png)

**Comment by KBOE2** [comment]
Fixed in Beta with db80ac6
Will be fixed for public soon.
