### ISSUE TITLE
Error Wachenhoverstati

### ISSUE THREAD

**Issue by JRH-1997** [LSS-Manager/lss-manager-v3#710]
An error when i use Wachenhoverstati:

![afbeelding](https://user-images.githubusercontent.com/65117490/83076558-10671e80-a076-11ea-8605-34bf76993fca.png)

**Comment by KBOE2** [comment]
Guess this is again some dutch specific thing. ^^

**Comment by KBOE2** [comment]
@JRH-1997 Could you please provide the full error lines so that we can see where exactly the error was thrown?

**Comment by JRH-1997** [comment]
![afbeelding](https://user-images.githubusercontent.com/65117490/83189947-f68b1180-a131-11ea-8922-6fabc45842d0.png)

**Comment by KBOE2** [comment]
Should be fixed with  ab77d54 
If the issue still persists, just reply in here and i will reopen.
