### ISSUE TITLE
Error ShareAlliancePost

### ISSUE THREAD

**Issue by JRH-1997** [LSS-Manager/lss-manager-v3#711]
The Missionhelper is showing this error with self made Alliance Missions: 
![afbeelding](https://user-images.githubusercontent.com/65117490/83187064-d9544400-a12d-11ea-880c-104d4c334cd9.png)

**Comment by KBOE2** [comment]
That seems to be an Error of shareAlliancePost.
Could you please in the future also include line number in screenshots? That would accelerate our bugfix possibilities :)

**Comment by JRH-1997** [comment]
![afbeelding](https://user-images.githubusercontent.com/65117490/83187621-baa27d00-a12e-11ea-9539-c67a721d1aeb.png)
The number that you can see now?

**Comment by KBOE2** [comment]
Yes. Thank you!
Fix will be on it's way!

**Comment by KBOE2** [comment]
Fixed in dev with 6c1a82e
