### ISSUE TITLE
No Average credits at only Amvulance missons

### ISSUE THREAD

**Issue by JRH-1997** [LSS-Manager/lss-manager-v3#716]
At the Share alliance post there is a an error with the only ambulance missions. 

TypeError: data.average_credits is null.

**Comment by KBOE2** [comment]
Also issue with DIY-Missions probably. *Note to myself*

**Comment by KBOE2** [comment]
Should be Fixed and available to public with next update since 8882623.
Issue will remain open until tested in running system.
