### ISSUE TITLE
Vorschlag: AAO Suche + Einzel-Fahrzeuge & Farbanpassung

### ISSUE THREAD

**Issue by Thomas21030** [LSS-Manager/lss-manager-v3#72]
## Beschreibung:

Erstmal ein großes Lob für die AAO-Suche, mal davon abgesehen das ich nun die komplette AAO  überarbeiten muss da ich sonnst häufiger 2 Stichworte klicken muss , aber sonst sehr schön gemacht 

1.)Nun, zu meinem Vorschlag, besteht die Möglichkeit die AAO-Suche auf die nur auf die Kategorien zu beschränken?

2.) Habe da ein par Farbfehler gefunden, die dafür sorg das man die AAO nicht lesen kann.
sie Sreenshot.

![aao suche](https://cloud.githubusercontent.com/assets/28989752/26670369/afcb8f28-46b1-11e7-916b-0d052dfbb43e.JPG)
![aao suche2](https://cloud.githubusercontent.com/assets/28989752/26670373/b4cddb66-46b1-11e7-8b50-3200ed6a4413.JPG)

## Mögliche Lösung:
- Durch die Beschränkung wird alles was keiner Kategorie zugewiesen wurde oben und/oder unten   angezeigt und man kann dort die einzelnen Fahrzeuge unterbringen und im Dropdown Menu die ganzen Stichworte der einzelnen Einsätze.

**Comment by lostdesign** [comment]
bzgl. Design ändert sich noch was - will daran noch arbeiten. Denke das wir noch Einstellungsmöglichkeiten bieten werden - wie die AAO Suche dann agiert.

**Comment by Tsumiki-Chan** [comment]
Das "Weiß auf weiß" sieht etwas komisch aus, da ja selbst der haken bzw. das Kreuz fehlt.
Gibt es hierzu ggf. eine Fehlermeldung in der Konsole oder kannst du mir die Einstellungen dieser AAO zukommen lassen? Ich konnte das in meinen Tests leider nicht reproduzieren

Zu den Kategorien hatte ich so meine 1-2 Ideen.

Idee 1: Ich baue wieder sebastians Tabs ein, ersetze aber die AAO's der Tabs wieder durch ein Dropdown
Idee 2: Der obige Dropdown enthält kategorien. Ggf auch so, dass man die ganze kategorie suchen kann

Vielleicht kannst du mir ja sagen, was angenehmer wäre (vom gefühl her)

**Comment by lostdesign** [comment]
@Tsumiki-Chan ist ein Hoverfehler - werde die CSS Bugs ausmerzen. 

Finde das man Einstellungen bieten sollte die entweder:
- die AAO durch eine Suchleiste ersetzt
- die AAO um die Suchleiste erweitert

Wie & wo kann man dann ja testen - variieren.

**Comment by Tsumiki-Chan** [comment]
@lostdesign Mir ist grad noch so die Idee gekommen, dass man das Dropdown abschalten könnte und man einfach nur eine Suchfunktion bekommt.

**Comment by lostdesign** [comment]
@Tsumiki-Chan das ist meine Idee, eine reine Suchleiste die drunter dann halt den Vorschlag liefert.

**Comment by Tsumiki-Chan** [comment]
Ich hätte das eher so gedacht, dass alles rausgeschmissen wird, was nicht auf den Suchbegriff passt (Siehe die Suche im Dashboard->Wachenplanung

**Comment by lostdesign** [comment]
Auch gut!

**Comment by Thomas21030** [comment]
Ich finde es wie jetzt ist schon gut fehlt halt nur eine Fläche bzw Butons für die Einzelnen-Fahrzeuge 

Die ganze AAO wieder anzeigen + Suchleiste ist doch dann mehr oder weniger doppelt gemoppelt 
Wenn das Dropdown  bzw die Suchleiste bleibt könnte ich mir für jeden Einsatz mehre Stichworte anlegen.

Wie z.Bsp: 
Museum  (FW)
Museum (FW+RD)
Museum (RD) 

oder wie schon vorhanden bei der Gasex  
![gasex extrem](https://cloud.githubusercontent.com/assets/28989752/26682811/150f1316-46e2-11e7-9024-c166ae99c808.JPG)

Gasex (kompl.)
Gasex (SF) ein Teil der SonderFHZ
Gasex (THW.) nur das THW
Gasex (RD) [in anderer Kategorie] nur RD
Hausw/ usw. -> Gasex  die AAO für die Aufstockung von z.B. Hauswand auf Gasex, damit nicht alles doppelt & 3-fach v.O. ist

**Comment by Tsumiki-Chan** [comment]
@Thomas21030 Ich habe eben mal meine Idee umgesetzt. Kannst ja mal schauen was ich angestellt habe.

**Comment by Thomas21030** [comment]
hupss was habe ich gemacht ;-(

**Comment by Thomas21030** [comment]
was hast du den gemacht?

**Comment by Tsumiki-Chan** [comment]
@lostdesign kann das zu?
