### ISSUE TITLE
Fahrzeuge umbenne

### ISSUE THREAD

**Issue by UnbekanntLSS** [LSS-Manager/lss-manager-v3#720]
Liebe Entwickler des LSSM,

ein Fahrzeug kann max. 150 Zeichen lange Bezeichnung erhalten.
Leider kürzt die APP "FAHRZEUGE UMBENENNEN" am anweden deutlich die länge ein. 

Ursprünglicher Name | Generierter Name | **Neuer/gekürzter Name**

Heros Berlin-Friedrichshain-Kreuzberg 1-LKW 7 Lkr 19 tm-1 | Heros Berlin Friedrichshain-Kreuzberg 1-LKW 7 Lkr 19 tm-1 | **Heros Berlin Friedrichshain-Kreuzberg 1-**

Wenn ich mich nicht verzählt habe, max. 40 Zeichen, kann der nur heruas geben.
Ich spiele das Leitstellenspiel.de
Ich bin der User https://www.leitstellenspiel.de/profile/559255
LG Alex

**Comment by KBOE2** [comment]
Ich frag da mal beim Dev-Team des Spiels nach, was genau die tatsächliche maximale Länge ist. Damals waren es jedenfalls nur 40 Zeichen, deshalb aktuell Beschränkung.

**Comment by UnbekanntLSS** [comment]
Ich kann dir gerne nen aktuellen Screen schicken mit der Länge. Aufgenommen letzte Nacht beim Zocken.

Von meinem iPhone gesendet

**Comment by KBOE2** [comment]
Jap, alles gut. Hab auch schon die Antwort ausm Team:
> laut Code sind es derzeit min 2 und max 150 Zeichen

Dann werd ich das mal bei uns ändern!

**Comment by KBOE2** [comment]
mit 652d376 geändert. Wird mit dem nächsten Update öffentlich sein!
