### ISSUE TITLE
Vorschlag: Einstellbare Position & Zoom-Level bei Pageload

### ISSUE THREAD

**Issue by jalibu** [LSS-Manager/lss-manager-v3#73]
Als Spieler möchte ich beim Aufruf der Seite eine möglichst gute Übersicht über meinen gesamten Leitstellenbereich.
Wenn man das Spiel heute lädt, so ist die Standard Position jedoch immer mit einem vorgegebenen Zoom-Level über der Leitstelle.
Wenn diese (wie bei mir) nicht zentral im Leitstellengebiet liegt, muss zur besseren Übersicht erst herausgezoomt und der Kartenbereich verschoben werden.
Bei der angekündigten Funktionalität "Mehrere Leitstellen" wird dieser Umstand weiter verschärft.

Abhilfe könnte eine (sehr einfach umsetzbare) Funktion sein "Kartenposition als Standard festlegen", welche dem Nutzer die Möglichkeit gibt die Anfangsposition selbst zu definieren.

**Comment by lostdesign** [comment]
Dann auf auf :D Kannst ja gleich selbst umsetzen 👍 Ist aber ein guter Vorschlag - würde das mal als allgemeines Map Plugin bezeichnen, dass dann mehrere Settings zur Karte liefert - u.a. Styles.

**Comment by FlorianRhausen** [comment]
Ich würde das ganze ergänzen wollen - mittels einem Button am Kartenrand der die Karte auf die Einsätze zentriert und soweit raus- oder reinzoomt, das alle Einsätze sichtbar sind oder anstelle eines Buttons, das man dieses Verhalten (wenn überhaupt möglich) als Standard der Karte mittels opt-in erklären kann.

**Comment by jalibu** [comment]
Umgesetzt mit https://github.com/LSS-Manager/lss-manager-v3/commit/53de78fb864d71618888ce59ea9675be8add32a3
