### ISSUE TITLE
No jQuery

### ISSUE THREAD

**Issue by panaceya** [LSS-Manager/lss-manager-v3#735]
log from console:
```text
Script error in [Greasemonkey script raw.githubusercontent.com/LSS Manager v3 Autoupdater; version 3.3.5.1]:
Error: LSS-Manager: No jQuery! Aborting!
```

**Comment by KBOE2** [comment]
Which Browser and which Version are you using?
On which site(s) exactly does this appear (for example only when viewing alliance etc.)?
Does this issue persist after reloading the page?

A few more information could help us resolving this problem...

**Comment by panaceya** [comment]
I`m use Firefox 77.0.1 (64-bit) under Windows 10 and Ubuntu/Linux

I see error in any time of visit main page of sites:
* https://www.dyspetcher101-game.com/#_=_
* https://www.dispetcher112.ru/#_=_
* https://www.missionchief.com/

Reload page acquire this error again.

**Comment by KBOE2** [comment]
Ok, thank you.
Does this only occur when being logged in, when you are not logged in or both?

**Comment by panaceya** [comment]
Logged of course.

**Comment by KBOE2** [comment]
Status Update:
This seems to be something that is caused by Greasemonkey.
The issue does not encounter when using [Tampermonkey](https://www.tampermonkey.net/) but I will see if we can fix this for Greasemonkey-Users!

**Comment by KBOE2** [comment]
I'm sorry to tell you that we cannot fix this as it is an issue by Greasemonkey itself.
Problem: Greasemonkey injects LSS-Manager Script before the game is fully loaded. This issue is not resolvable.
Solution: Use Tampermonkey instead.

I will close here as we cannot do anything about that!
