### ISSUE TITLE
Vorschlag. Kartenfilter (Ein und ausblenden von Einsätzen)

### ISSUE THREAD

**Issue by AdvocatusDei** [LSS-Manager/lss-manager-v3#74]
Hallo,

ich hätte da noch einen Vorschlag. Was haltet ihr davon wenn es einen Kartenfilter gäbe.

Z.b. bei Events wird die Karte ja schnell unübersichtlich. Mit dem Kartenfilter, könnte man dann z.b.

Auf eigene Aufträge klicken, und sieht auf der Karte auch nur noch die eigenen. Oder man klickt auf Event und sieht nur noch die vom Event. Oder Sicherheitswachen und man sieht nur noch die SW.

Ich würde mich über dieses Gimmick freuen. 

Vll sogar in Verbindung mit dem von mir bereits vorgeschlagenen und angenommen Addon (Einsatz Menü von Eagle).

LG 

Advo

**Comment by KBOE2** [comment]
Ist mal zu #537 zusammengefasst
