### ISSUE TITLE
Einsätze generieren Aufgeklappt

### ISSUE THREAD

**Issue by nairolfff** [LSS-Manager/lss-manager-v3#75]
Fehlermeldung:

Wenn neue Einsätze generieren sind diese immer aufgeklappt.
Kann man dies eventuell steuern?

http://imgur.com/WodhiTl

Aktivierte Module:

LAYOUT 04
NOTIFICATION ALERT
MISSIONOUT
EINSÄTZE FREIGEBEN
EINSÄTZE SUCHEN

Mögliche Lösung / Verbesserungsvorschlag:

Browser: Opera

Version: 45.0.2552.812

Beta Version: 3.1.8

**Comment by Tsumiki-Chan** [comment]
Müsste schon bekannt sein

**Comment by Mausmajor** [comment]
sollte im nächsten Update behoben sein
