### ISSUE TITLE
renameFZ | vehicle is undefined

### ISSUE THREAD

**Issue by Patti2101** [LSS-Manager/lss-manager-v3#756]
Beim umbenennen von Fahrzeugen in der jeweiligen Wache tritt folgender Fehler auf:

rename@https://proxy.lss-manager.de/v3/modules/lss-RenameFZ/renameFZ.user.js?uid=leitstellenspiel62675:15:668
dispatch@https://www.leitstellenspiel.de/assets/application-9784eca0e7251c46ea667b16c3705caf.js:28:4312
add/g.handle@https://www.leitstellenspiel.de/assets/application-9784eca0e7251c46ea667b16c3705caf.js:28:1017

Nach dem Neuladen der Seite tritt der Fehler nicht auf, aber dann direkt in der nächsten Wache wieder.

Außerdem gibt es einen kleinen Buchstabendreher: "Status: Namen und Forumlare erfolgreich generiert!"

**Comment by KBOE2** [comment]
Der Fehler tritt auf, wenn neu gekaufte Fahrzeuge oder Gebäude vom LSSM noch nicht erkannt wurden. Ein Neuladen des Spiels mit Strg+F5 hilft dagegen, alternativ bis zu 5 Minuten warten.

Danke für die Meldung des Buchstabendrehers, wird bei nächster Gelegenheit behoben :)

**Comment by Suchty112** [comment]
Buchstabendreher behoben. Kommt nachher um 16 Uhr online wenn das letzte Land online ist ;)
