### ISSUE TITLE
Weiße Seite bei Alarmierung mit Hotkey

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#78]
## Fehlermeldung:
In unregelmäßigen Abständen kommt es vor, dass mit dem Button "S" zum Alarmieren eine weiße Seite erscheint anstatt dem nächsten Einsatz. Über den normalen Button "Alarmieren und weiter" bzw. mit deaktiviertem Plugin und "S" für alarmieren funktioniert es problemlos.

![image](https://cloud.githubusercontent.com/assets/6639017/26757668/0444824e-48c4-11e7-8d36-037fd2b96f0e.png)

## Aktivierte Module:
LAYOUT 01
MISSIONOUT
EIGENE VGE SPEICHERN
REDESIGN 01
FMS 5 IN DER KARTE
CLOCK
EINSÄTZE SUCHEN
FAHRZEUGE UMBENNENEN
SHOW BACK ALARM ABOVE
KEYBOARD ALARMIERUNG v0.1 von lost

#### Beta Version: 3.2.0

**Comment by lostdesign** [comment]
### TODO
- [ ] remove 'S'
- [ ] remove 'W'
- [ ] add Enter
- [ ] add own key settings

**Comment by jalibu** [comment]
Das ist ein Bug im Spiel. Tritt auch ohne Mod auf.

**Comment by MrWeezle** [comment]
wie oben gesagt, ist das mir ohne Plugin nie passiert

**Comment by jalibu** [comment]
https://forum.leitstellenspiel.de/index.php/Thread/11608-Fehler-Zum-Nächsten-Fahrzeug-im-Status-5/?postID=186952#post186952

Können das nicht Duplikate sein?

**Comment by lostdesign** [comment]
^ es ist ein bekanntest Phänomen von LSS - die Tastaturalarmierung hat nur dafür gesorgt das es öfters aufgetreten ist.

**Comment by MrWeezle** [comment]
ok danke für die Info ^^
