### ISSUE TITLE
Vorschlag: AppStore als Tabelle

### ISSUE THREAD

**Issue by BjoernEnd** [LSS-Manager/lss-manager-v3#79]
## Beschreibung:
Ich finde den AppStore ein wenig aufgebläht. Wie wäre es, wenn man einfach eine Tabelle mit mehreren Spalten erstellt. So hätte man eine schöne übersichtliche Liste mit allen Modulen. Eventuell noch in Kategorien eingeteilt

## Mögliche Lösung:
- Tabelle mit folgenden Spalten:
--> Name - Beschreibung - Version/Coder - Link zu Github - Aktion

**Comment by Tsumiki-Chan** [comment]
@BjoernEnd 
https://a.uguu.se/yOurG6Skk8cu_2017-06-04_14-40-00.mp4

Was denkst du davon?

**Comment by BjoernEnd** [comment]
Sieht schon etwas besser aus. Platzsparender. Evtl. noch den Header mit der Beschreibung etwas einstauchen. Auf meinem 15" Mac Book nimmt dieser fast den ganzen Bildschirm ein *lach

**Comment by lostdesign** [comment]
![](https://imgur.com/fGbDNYr)
Hab mal radikal unnötige Informationen entfernt.
