### ISSUE TITLE
Vorschlag: Datum und Uhrzeit des Einsatzes anzeigen

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#80]
In der Einsatzansicht könnte man das Datum und die Uhrzeit wann der Einsatz generiert wurde anzeigen. Evtl. sogar mit Anzeige vor wieviel Minuten. Beispiel könnte etwa so aussehen:

![image](https://cloud.githubusercontent.com/assets/6639017/26765462/9e55c6e6-497c-11e7-8536-efaa9d1161bf.png)

**Comment by Tsumiki-Chan** [comment]
@lostdesign Hattest du das schon eingebaut?

**Comment by MrWeezle** [comment]
hab ich jetzt als Modul gemacht, hatte es vorher als eigenes Skript
