### ISSUE TITLE
Einsatztabs, Ausgabe ()

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#81]
Wenn ich die Einsatztabs im Appstore verwende, sieht das ganze dann so aus:

NF () KTP () VE () EVT () SW ()

Ich denke mal das zwischen den () Zahlen ausgelesen werden sollen. Möglicher Bug?

**Comment by lostdesign** [comment]
Ja ist ein 🐜, habs heute morgen mal eingefügt - wird aber heute behoben.

**Comment by CainDawson** [comment]
Oki Doki. :)

**Comment by lostdesign** [comment]
fixed.

**Comment by CainDawson** [comment]
Jetzt seh ich es garnicht mehr wenn ich es aktiviert habe, :)

**Comment by lostdesign** [comment]
Im nächsten Update.

**Comment by CainDawson** [comment]
Folgendes:

Aktuell ist es so:
NF (0/4) KTP (0/2) VE (0/0) EVT (0/0) SW (0/2)

Müsste aber aufgrund der Einsätze die nach und nach kommen so sein:
NF (2/6) KTP (0/2) VE (0/0) EVT (0/0) SW (0/2)

Es wird also noch nicht wirklich aktualisiert. :) Wenn ich F5 mache, dann ist es aktualisiert. :)

**Comment by Mausmajor** [comment]
Einsatzstabs gibt es nicht mehr
