### ISSUE TITLE
Vorschlag: Gebäude Übersicht - Rückalamieren als Icon

### ISSUE THREAD

**Issue by BjoernEnd** [LSS-Manager/lss-manager-v3#83]
## Beschreibung:
Meine Vorschläge Sprudeln momentan nur so raus *lach

Also was mich momentan auch noch Stört ist der Rückalamieren Button. Wäre es evtl. möglich, diesen einfach als ICON, VOR dem Fahrzeugnamen anzeigen zu lassen. Ich habe leider etwas längere Fahrzeugnamen und wie bekannt einen sehr kleinen Bildschirm. Der Deutsche ist ja immer einer, bei dem muss alles in Reih-und Glied stehen :-D. Naja es rückt ins unlesbare.

Wäre Super wenn Ihr das im Script irgendwie unter bekommen würdet.

## Mögliche Lösung:
- Schriftzug "Rückalamieren" ersetzen durch ein Icon

**Comment by lostdesign** [comment]
Ich setz mich mal dran.

**Comment by Mausmajor** [comment]
Werden wir nicht umsetzten, da es  zu Problemen kommt wenn der Button mal da ist und mal nicht.
