### ISSUE TITLE
Fehelnde Zahlen und Einsatzfreigaben

### ISSUE THREAD

**Issue by Edelweisser** [LSS-Manager/lss-manager-v3#839]
Hy,
mir ist gerade aufgefallen, das zumindest bei mir die Zahlen der Einsätze unten in Grün fehlen. z Bsp 0 von 200  jeweils als ein feld
Zum anderen sind Die Schalter  für die VGE freigabe und posten im Chat nicht mehr vorhanden. Seid Ihr daran am Arbeiten ?

Gruß
de Edel

**Comment by Suchty112** [comment]
Zum ersteren. Gescheckt ob der PremiumAcc noch läuft? das ist nämlich nix von uns ^^ . beim zweiten. addon aktiviert?
