### ISSUE TITLE
Keine Nummernanzeige bei Einsatztabs

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#84]
Bei aktiviertem Modul für Einsatztabs wird die Anzahl der jeweiligen Einsätze nicht angezeigt:
![image](https://cloud.githubusercontent.com/assets/6639017/26782791/7c6f69e6-49f5-11e7-95ec-5829d3f66fe2.png)

Aktivierte Module:

LAYOUT 01 v1.1
MISSIONOUT
EIGENE VGE SPEICHERN
REDESIGN 01 alpha-0.1
FMS 5 IN DER KARTE
CLOCK
EINSÄTZE FREIGEBEN
EINSÄTZE SUCHEN
DASHBOARD
FAHRZEUGE UMBENNENEN
SHOW BACK ALARM ABOVE
Browser: Chrome V58.0.3029.110

**Comment by lostdesign** [comment]
Duplikat #81
