### ISSUE TITLE
Script wie weg...

### ISSUE THREAD

**Issue by BruceBaumann** [LSS-Manager/lss-manager-v3#841]
Hallo zusamme, ich habe mir vor einigen Wochen das LLS Manager v3 Skript runtergeladen, heute wollte ich mal wieder bissel Spielen, am anfang ging es noch, doch dann war es aufeinmal wie weg. Ich seh das es aktiv ist, aber die Funktion ist nicht mehr da. Weiß jemand an was das liegt?

**Comment by jxn-30** [comment]
Ja, es gab seitens Cloudflare ein paar Probleme. Wir haben unsere Infrastruktur angepasst, es braucht aber noch ein bisschen, bis der LSSM wieder da is.

**Comment by Tsumiki-Chan** [comment]
https://forum.leitstellenspiel.de/index.php?thread/11166-lss-manager-v3/&postID=371622#post371622
https://forum.leitstellenspiel.de/index.php?thread/11166-lss-manager-v3/&postID=371638#post371638

Problem ist bekannt, erkannt und gebannt
