### ISSUE TITLE
Einsatzhelfer wird nicht angezeigt!

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#85]
Im Appstore gibt es den "Einsatzhelfer". Wird aber nicht angezeigt. Eventuell ein Bug?

**Comment by lostdesign** [comment]
Ist gerade noch in Entwicklung.

**Comment by CainDawson** [comment]
Ok, geht klar :)

**Comment by CainDawson** [comment]
Wie ich sehe ist es Implementiert. Scheint auch Ohne Fehler zu sein. :)
