### ISSUE TITLE
Erweiterung der Verbands-Bereitstellungsraum Anzeige

### ISSUE THREAD

**Issue by MrNobody92** [LSS-Manager/lss-manager-v3#86]
Ein Vorschlag von mir, wäre es die Anzeige unter dem Menüpunkt "Verband" -> "Bereitstellungsräume" zu erweitern um die beiden Spalten "verbleibende Dauer" und "eigene Fahrzeuge am BSR ja/nein".

Begründung: Zur Zeit ist die Ansicht nicht brauchbar. Sobald man in einem größeren Verband ist, muss man jeden BSR einzeln anklicken und schauen, ob Fahrzeuge von einem selbst vor Ort sind oder wie lange ist der BSR überhaupt noch offen. Damit man dies auf einen Blick sehen kann, wäre es schön wenn diese zwei Funktionen, in welcher Form auch immer, eingefügt werden könnten. 

![bereitstellungsraume](https://cloud.githubusercontent.com/assets/28884935/26794502/2e66ee36-4a22-11e7-9d7e-fa77de16c655.PNG)

**Comment by Mausmajor** [comment]
ist nicht umsetzbar, da die Daten nachgeladen werden müssten. BZW der User erst sämtliche BSR aufmachen müsste.
