### ISSUE TITLE
BUG: Fehlermeldung Einsatzhelfer bei Verbands-GSL

### ISSUE THREAD

**Issue by BjoernEnd** [LSS-Manager/lss-manager-v3#87]
## Fehlermeldung:
Habe gerade den Einsatzhelfer eingeschaltet und bei einem "GSL" im Verband einen Fehler bekommen. Aber ist denke ich mal logisch, da es keine "Hilfe für diesen Einsatz" gibt.

![bildschirmfoto 2017-06-05 um 19 09 56 2](https://cloud.githubusercontent.com/assets/28508122/26794657/da9401d0-4a22-11e7-8baf-ea57cdaaedcf.png)

## Aktivierte Module:
- CLOCK
- EINSATZHELFER
- EINSATZTABS
- EINSÄTZE FREIGEBEN
- EINSÄTZE SUCHEN
- LAYOUT 02
- MISSIONOUT
- REDESIGN 01

## Mögliche Lösung / Verbesserungsvorschlag:
- Zwischen abfrage einbauen, ob überhaupt Informationen verfügbar sind. Dann diesen Helfer ausblenden oder eine Meldung, dass es sich um eine GSL handelt oder ähnliches

#### Beta Version: 3.2.1

**Comment by CainDawson** [comment]
#85 hättest Du auch hier Schreiben können, da es sich um den Einsatzhelfer handelt. ;)
Duplikat somit. :)

**Comment by lostdesign** [comment]
Immer diese Kuhbar :D - wird eingebaut.

@CainDawson - nicht wirklich ein Duplikat - ist ein anderer Fehler.

**Comment by CainDawson** [comment]
Für mich sah es auf den Blick als Duplikat :D

**Comment by Suchty112** [comment]
Ist seit dem Refactoring des EH's weg. damit schließ ich dat mal :D
