### ISSUE TITLE
Einsatztabs

### ISSUE THREAD

**Issue by maxk1312** [LSS-Manager/lss-manager-v3#88]
Wenn ich die Einsatztabs aktiviert habe, habe ich keine Möglichkeit mehr, alle Einsätze auf einmal einzuklappen.

Aktivierte Module:

EINSATZTABS
EINSÄTZE FREIGEBEN
LAYOUT 02
MISSIONOUT
REDESIGN 01

**Comment by lostdesign** [comment]
Kein Fehler - ist einfach noch nicht hinzugefügt.

**Comment by Tsumiki-Chan** [comment]
@lostdesign Dein Modul verursacht den Fehler also hast du es zu fixen.

**Comment by Mausmajor** [comment]
Einsatzstabs gibt es nicht mehr
