### ISSUE TITLE
Anzeigefehler Layout 02

### ISSUE THREAD

**Issue by maxk1312** [LSS-Manager/lss-manager-v3#89]
Fehler: der Screenshot sagt glaub ich alles 
![](http://www.bilder-upload.eu/upload/0ca42c-1496693567.png)

aktiviert: Layout 02, EINSÄTZE FREIGEBEN, MISSIONOUT, SHOW BACK ALARM ABOVE

**Comment by lostdesign** [comment]
*IM NÄCHSTEN UPDATE FIXED*
