### ISSUE TITLE
Einsatzhelfer - Fehlende Einsätze

### ISSUE THREAD

**Issue by FlorianRhausen** [LSS-Manager/lss-manager-v3#91]
![grafik](https://cloud.githubusercontent.com/assets/28895574/26820682/f578228e-4aa3-11e7-8d7e-a1ba7eb30b15.png)

**Comment by FlorianRhausen** [comment]
Rüstwagen 1x 30%
Löschfahrzeuge 3x
ELW1 1x
NEF 40%

**Comment by Suchty112** [comment]
Je nachdem wie es @lostdesign geschrieben hat, hier wäre es aus der Standalone

https://github.com/Suchty112/LSS.Einsatzhelfer/blob/master/script.user.js#L73

Kannste gerne so übernehmen
(musste es so machen, da github die formatierung kaputt haut :/ )

**Comment by FlorianRhausen** [comment]
ok

**Comment by FlorianRhausen** [comment]
Bei Tankbetrug das selbe:
![grafik](https://cloud.githubusercontent.com/assets/28895574/26821888/59f76450-4aa8-11e7-8cc1-92d77f24f25b.png)

FuSTW x1

**Comment by lostdesign** [comment]
HilflosePersonaufWasser

**Comment by Suchty112** [comment]
Ist in #130 gefixxt, der teil ist soweit auch schon in der entwicklungsversion drin. Auffälligkeiten gab es soweit keine. Sollte wahrscheinlich in den nächsten Tagen für die Beta-Leute bzw für alle raus kommen.

Schönes Wochenende
