### ISSUE TITLE
Bug bei Event

### ISSUE THREAD

**Issue by AdvocatusDei** [LSS-Manager/lss-manager-v3#93]
Tachchen, gerade einen Bug entdeckt. Seht selbst dann muss ich ned so viel schreiben :P 

Ist ja ersichtlich :) 

![siehe](https://picload.org/image/ricicrar/managerbug.png)

Google Chrome Version 58.0.3029.110 (64-bit)
Win 10

LSS Manager Beta 3.2.1 (neues Script)

Layout 4
Clock
Dashboard
Eigene VGE´s Speichern
Einsatzhelfer
Einsätze Freigeben
FMS 5 auf Karte
Keyborad Alamierung
Mission out
Notification Alert
Show back alarm above
Wachenstatus

**Comment by Mausmajor** [comment]
sollte im Update gefixt sein
