### ISSUE TITLE
Bug in der App Einsatztabs

### ISSUE THREAD

**Issue by AdvocatusDei** [LSS-Manager/lss-manager-v3#94]
Tachchen, nach 4 Stunden spielen mit dem Addon Einsatztabs ist mir folgendes aufgefallen.

Siehe Bild: 
![](https://picload.org/image/riciidca/buggerle.png)

NF steht bei 0/0 es müsste aber 1/3 lauten sowie
EVT 1/57  stimmt auch nicht es sind 28/94

das heißt der Counter aktualisiert nicht richtig. Bei umschalten auch nicht.
Nur F5 drüclken bringt das Addon wieder zum aktualisieren, wie ihr hier sehen könnt.

![](https://picload.org/image/riciiagw/buggerle2.png)

LG Advo

**Comment by lostdesign** [comment]
Bilder verlinkt man mit `![TEXT](URL)`

**Comment by AdvocatusDei** [comment]
ok sry ich versuche das hernach mal

**Comment by Mausmajor** [comment]
Einsatzstabs gibt es nicht mehr

**Comment by AdvocatusDei** [comment]
Wie gibt es nicht mehr. Ich nutzte sie doch.....

**Comment by lostdesign** [comment]
Das Modul von Eagle war bescheiden, wir schreiben es neu.
