### ISSUE TITLE
Bug: Layout 4, 2 Display mode.

### ISSUE THREAD

**Issue by AdvocatusDei** [LSS-Manager/lss-manager-v3#95]
Ich glaube Screeny sagt alles: 

Display 1 Fenster komisch verschoben. Display 2 Karte nicht komplett auf dem Bildschirm. 

![gug](https://img5.picload.org/image/riiggwwi/2displaybug.png)

Chrome 58.0.3029.110 (64-bit)

LLS Manager B 3.2.2
Layout 4
Clock
Dashboard, 
Eigene VGE´s
Einsätze Suchen
FMS 5 in Karte
Missionout,
Notification alert
Back alarm
Wachen Status.

sry sollte es ein Duplikat sein :)

LG

Advo

**Comment by lostdesign** [comment]
Eigentlich sollte das Layout04 so auch nicht genutzt werden?

**Comment by AdvocatusDei** [comment]
Na dann ist das hinfällig. War nicht zu wissen, da ja keine beschreibungen mehr bei den apps dabei sind. 

Wurst dann close das ding mal.

Du empfiehlst für 2 Displays, am besten das Standartlayout von Sebastian oder?

**Comment by lostdesign** [comment]
Ich kann dafür ein eigenes Layout machen, das mit der externen Karte funktioniert.
