### ISSUE TITLE
Einsätze im LSS-Dark/Nightmode nicht sichtbar

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/lss-manager-v3#96]
## Fehlermeldung:
Auf der Startseite sind die Einsätze sogut wie nicht erkennbar wenn der Darkmode von LSS aktiviert ist und man den LSSM an hat

## Aktivierte Module:
- Clock
- Dashboard
- Einsatzhelfer
- Einsätze freigeben

## Mögliche Lösung / Verbesserungsvorschlag:
-Das Missionpanel so abändern wenn Darkmode von LSS an ist, man sie wieder lesen kann.

#### Beta Version: Glaube ja 

![fireshot screen capture 007 - leitstellenspiel_de - baue deine eigene leitstelle in deiner stadt - www_leitstellenspiel_de_](https://user-images.githubusercontent.com/1109899/26880555-11c84c6a-4b95-11e7-865f-abc522fa6b95.png)
![fireshot screen capture 008 - leitstellenspiel_de - baue deine eigene leitstelle in deiner stadt - www_leitstellenspiel_de_](https://user-images.githubusercontent.com/1109899/26880556-11c90c5e-4b95-11e7-909c-1c4fcf7b407d.png)

**Comment by lostdesign** [comment]
Fixed im nächsten Update.
