### ISSUE TITLE
Layout 4 und Hinweis auf Event

### ISSUE THREAD

**Issue by MrWeezle** [LSS-Manager/lss-manager-v3#97]
Bei aktiviertem Layout 4 wird der Hinweis, dass ein Event aktiv ist unterhalb der Einsatzkarte angezeigt. Dies sollte oberhalb zu sehen sein.

![image](https://user-images.githubusercontent.com/6639017/26884501-30fde418-4ba0-11e7-88b2-38848cb1e551.png)

**Comment by lostdesign** [comment]
@MrWeezle fixed? Bei mir trat das heute nicht mehr auf.

**Comment by MrWeezle** [comment]
Teste ich die Tage mal und geb dir Rückmeldung

**Comment by Suchty112** [comment]
Grad getestet. Geht wieder. Ist wieder oben. Ist schon verschoben und damit ein weiterer offener issue closed. hoffe ist so i.o @MrWeezle da seit über ein Monat keine rückmeldung mehr kam D:

**Comment by MrWeezle** [comment]
ja, hab bisher kein Event mehr gestartet bzw. war bei keinem dabei ^^
