### ISSUE TITLE
Verbandschat Aktualisiert sich nicht!

### ISSUE THREAD

**Issue by CainDawson** [LSS-Manager/lss-manager-v3#98]
Hey,
sobald einer im Verbandschat was schreibt, aktualisiert sich das nicht mehr bei mir. Evtl. ein Bug?

**Comment by Mausmajor** [comment]
Welche Module hast du aktiv?

**Comment by Tsumiki-Chan** [comment]
Wurde schonmal im Chat gemeldet. Das liegt iwo am Layout01 @Mausmajor

**Comment by Tsumiki-Chan** [comment]
Sollte in den nächsten 30 minuten behoben sein.

**Comment by CainDawson** [comment]
Auch von mir kurze Rückmeldung, geht wieder. Danke sehr !
